import { ObjectId } from "mongodb";
import { Crown, Medal, Sparkles, Trophy } from "lucide-react";
import { getDb } from "@/lib/db/mongo";
import { currentUserId } from "@/lib/auth/session";

type Row = { userId: string; points: number; predictions: number; exact: number; username: string; avatarUrl: string | null };
function initials(name: string) { const parts = name.trim().split(/\s+/).filter(Boolean); const chars = parts.length > 1 ? [parts[0][0], parts[1][0]] : [...(parts[0] ?? "ک")].slice(0, 2); return chars.join("‌"); }
async function leaderboard(): Promise<Row[]> {
  const db = await getDb();
  const stats = await db.collection<Record<string, unknown>>("leaderboardStats").find({ scope: { $in: ["GLOBAL", "global", "all"] } }).sort({ points: -1, totalPoints: -1 }).limit(100).toArray();
  const base = stats.length ? stats.map((item) => ({ userId: String(item.userId ?? ""), points: Number(item.points ?? item.totalPoints ?? 0), predictions: Number(item.predictions ?? item.predictionCount ?? 0), exact: Number(item.exact ?? item.exactScores ?? 0) })) : await db.collection<{ userId: string }>("predictions").aggregate<{ _id: string; predictions: number }>([{ $match: { userId: { $ne: "guest" } } }, { $group: { _id: "$userId", predictions: { $sum: 1 } } }, { $sort: { predictions: -1 } }, { $limit: 100 }]).toArray().then((items) => items.map((item) => ({ userId: item._id, points: 0, predictions: item.predictions, exact: 0 })));
  const ids = base.map((item) => item.userId).filter(ObjectId.isValid).map((id) => new ObjectId(id));
  const users = ids.length ? await db.collection<{ username: string; avatarUrl?: string | null }>("users").find({ _id: { $in: ids } }, { projection: { username: 1, avatarUrl: 1 } }).toArray() : [];
  const byId = new Map(users.map((user) => [String(user._id), user]));
  return base.map((item) => ({ ...item, username: byId.get(item.userId)?.username ?? "کاربر لوبلاک", avatarUrl: byId.get(item.userId)?.avatarUrl ?? null }));
}

export default async function LeaderboardPage() {
  const [rows, me] = await Promise.all([leaderboard(), currentUserId()]); const top = rows.slice(0, 3);
  return <main className="min-h-screen px-5 pb-28 pt-24 md:mr-72 md:px-10 md:pb-16 md:pt-28"><div className="mx-auto max-w-6xl"><section className="relative overflow-hidden rounded-[30px] border border-brand/20 bg-gradient-to-br from-brand/20 via-[#121714] to-[#090b0a] p-7 md:p-10"><div className="absolute -left-12 -top-20 h-56 w-56 rounded-full bg-brand/20 blur-3xl"/><div className="relative"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-[#e8c66a]/25 bg-[#e8c66a]/10 px-3 py-1 text-xs font-bold text-[#e8c66a]"><Crown size={14}/> تالار قهرمانان</div><h1 className="text-3xl font-black md:text-5xl">جدول رتبه‌بندی</h1><p className="mt-3 text-sm text-[var(--muted)]">جایگاه کاربران بر اساس امتیاز پیش‌بینی‌های رسمی</p></div></section>
    {rows.length ? <><div className="mt-8 grid gap-4 md:grid-cols-3">{top.map((row, index) => <Podium key={row.userId} row={row} rank={index + 1}/>)}</div><div className="mt-7 overflow-hidden rounded-[26px] border border-white/[.08] bg-[#111116]"><div className="grid grid-cols-[48px_1fr_72px_72px] gap-2 border-b border-white/[.07] px-4 py-3 text-[10px] font-bold text-[var(--muted)] md:grid-cols-[64px_1fr_120px_100px]"><span>رتبه</span><span>بازیکن</span><span>پیش‌بینی</span><span>امتیاز</span></div>{rows.map((row, index) => <div key={row.userId} className={`grid grid-cols-[48px_1fr_72px_72px] items-center gap-2 border-b border-white/[.05] px-4 py-4 text-sm last:border-0 md:grid-cols-[64px_1fr_120px_100px] ${row.userId === me ? "bg-brand/10" : ""}`}><b className="text-[var(--muted)]">{index + 1}</b><div className="flex min-w-0 items-center gap-3"><Avatar row={row}/><span className="truncate font-bold">{row.username}{row.userId === me && <small className="mr-2 text-brand">شما</small>}</span></div><span className="text-[var(--muted)]">{row.predictions}</span><b className="text-brand">{row.points}</b></div>)}</div></> : <div className="mt-8 rounded-[26px] border border-dashed border-white/10 p-14 text-center"><Trophy className="mx-auto mb-4 text-brand" size={34}/><h2 className="font-black">هنوز رتبه‌ای ثبت نشده</h2><p className="mt-2 text-sm text-[var(--muted)]">با ثبت اولین پیش‌بینی وارد جدول می‌شوی.</p></div>}
  </div></main>;
}
function Avatar({ row }: { row: Row }) { return <span className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full border border-white/15 bg-brand/15 text-[10px] font-black">{row.avatarUrl ? <img src={row.avatarUrl} alt={row.username} className="h-full w-full object-cover"/> : initials(row.username)}</span>; }
function Podium({ row, rank }: { row: Row; rank: number }) { const colors = ["text-[#e8c66a]", "text-[#d6dae1]", "text-[#c48a68]"]; return <div className={`relative rounded-[24px] border bg-[#111116] p-5 ${rank === 1 ? "border-[#e8c66a]/35 md:-translate-y-3" : "border-white/[.08]"}`}><div className="mb-5 flex items-center justify-between"><Medal className={colors[rank - 1]} size={22}/><span className="text-3xl font-black text-white/10">0{rank}</span></div><div className="flex items-center gap-3"><Avatar row={row}/><div className="min-w-0"><h3 className="truncate font-black">{row.username}</h3><p className="mt-1 flex items-center gap-1 text-xs text-[var(--muted)]"><Sparkles size={12} className="text-brand"/>{row.points} امتیاز</p></div></div></div>; }
