import { MongoClient, type Db } from "mongodb"; import { env } from "@/lib/env";
const globalForMongo=globalThis as unknown as {mongo?:MongoClient; mongoPromise?:Promise<MongoClient>};
function directUri(){if(!env.MONGODB_URI||!env.MONGODB_DIRECT_HOSTS)return undefined; const match=env.MONGODB_URI.match(/^mongodb\+srv:\/\/([^@]+)@([^/?]+)(?:\/[^?]*)?(?:\?.*)?$/); if(!match)return undefined; const replica=env.MONGODB_REPLICA_SET?`&replicaSet=${encodeURIComponent(env.MONGODB_REPLICA_SET)}`:""; return `mongodb://${match[1]}@${env.MONGODB_DIRECT_HOSTS}/?authSource=admin&tls=true${replica}`;}
async function connect(){if(!env.MONGODB_URI)throw new Error("MONGODB_URI is not configured"); const fallback=directUri(); const client=globalForMongo.mongo??new MongoClient(fallback??env.MONGODB_URI,{serverSelectionTimeoutMS:10_000}); try{return await client.connect();}catch(error){if(!fallback)throw error; const srv=new MongoClient(env.MONGODB_URI,{serverSelectionTimeoutMS:10_000}); await srv.connect(); return srv;}}
export async function getDb():Promise<Db>{if(!env.MONGODB_URI)throw new Error("MONGODB_URI is not configured"); if(!globalForMongo.mongoPromise){globalForMongo.mongoPromise=connect().then(client=>{globalForMongo.mongo=client; return client;}).catch(error=>{globalForMongo.mongoPromise=undefined; throw error;});} return (await globalForMongo.mongoPromise).db();}
export async function ensureIndexes(){const db=await getDb(); await Promise.all([
 db.collection("users").createIndex({normalizedUsername:1},{unique:true}),db.collection("sessions").createIndex({tokenHash:1},{unique:true}),db.collection("sessions").createIndex({expiresAt:1},{expireAfterSeconds:0}),
 db.collection("teams").createIndex({provider:1,providerTeamId:1},{unique:true}),db.collection("matches").createIndex({provider:1,providerMatchId:1},{unique:true}),db.collection("matches").createIndex({leagueCode:1,seasonStartYear:1,matchday:1}),db.collection("matches").createIndex({roundId:1,status:1,kickoffAt:1}),
 db.collection("predictions").createIndex({userId:1,matchId:1},{unique:true}),db.collection("predictionLockSnapshots").createIndex({predictionId:1},{unique:true}),db.collection("predictionLockSnapshots").createIndex({clubIdAtLock:1,matchId:1}),
 db.collection("predictionScores").createIndex({userId:1,matchId:1},{unique:true}),db.collection("predictionScores").createIndex({seasonStartYear:1,leagueCode:1,matchday:1,clubIdAtLock:1}),
 db.collection("leaderboardStats").createIndex({userId:1,scope:1},{unique:true}),db.collection("clubs").createIndex({ownerId:1},{unique:true}),db.collection("clubs").createIndex({state:1,discoveryMode:1}),db.collection("clubMemberships").createIndex({userId:1},{unique:true,partialFilterExpression:{leftAt:null},name:"active_membership_per_user"}),db.collection("clubMemberships").createIndex({clubId:1,leftAt:1}),db.collection("clubJoinRequests").createIndex({userId:1,clubId:1,status:1},{unique:true}),db.collection("clubInvitations").createIndex({clubId:1,email:1,status:1}),db.collection("clubInvitations").createIndex({tokenHash:1},{unique:true}),
 db.collection("seasons").createIndex({startYear:1},{unique:true}),db.collection("leagueSeasons").createIndex({leagueCode:1,seasonId:1},{unique:true}),db.collection("rounds").createIndex({leagueSeasonId:1,number:1},{unique:true}),db.collection("rounds").createIndex({status:1}),
 db.collection("footballApiQuota").createIndex({day:1},{unique:true}),db.collection("syncRuns").createIndex({provider:1,startedAt:-1})]);}
