import Link from "next/link";
import { ArrowLeft, CalendarDays, ChartNoAxesCombined, Flame, Trophy } from "lucide-react";
import { LEAGUES } from "@/lib/football/leagues";
import { getMatches, getPredictions } from "@/lib/football/data";
import { PredictionCard } from "@/components/PredictionCard";
import { currentUserId } from "@/lib/auth/session";

export default async function Dashboard() {
  const matches = await getMatches({ limit: 12 });
  const predictions = await getPredictions(matches.map((match) => match.providerMatchId), (await currentUserId()) ?? "guest");
  return <main className="min-h-screen px-5 pb-28 pt-24 md:mr-72 md:px-10 md:pb-16 md:pt-28"><div className="mx-auto max-w-7xl">
    <section className="relative mb-8 overflow-hidden rounded-[30px] border border-brand/25 bg-gradient-to-br from-brand/20 via-[#151519] to-[#0c0c0f] p-7 shadow-glow md:p-10"><div className="absolute -left-16 -top-20 h-64 w-64 rounded-full bg-brand/20 blur-3xl"/><div className="relative flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-brand/30 bg-brand/10 px-3 py-1.5 text-xs font-bold text-brand"><Flame size={14}/> فصل جدید رقابت</div><h1 className="max-w-2xl text-3xl font-black leading-tight md:text-6xl">هر مسابقه،<br/><span className="text-brand">یک تصمیم</span> تازه.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-[var(--muted)]">بازی‌های واقعی پنج لیگ بزرگ اروپا را ببین و پیش‌بینی‌ات را قبل از شروع ثبت کن.</p></div><Link href="/leagues/GB1" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-brand px-5 py-3.5 text-sm font-black text-white transition hover:bg-brand-hover">مشاهده همه لیگ‌ها <ArrowLeft size={17}/></Link></div></section>
    <div className="mb-9 grid gap-3 sm:grid-cols-3"><Stat icon={<Trophy/>} label="امتیاز کل" value="—"/><Stat icon={<ChartNoAxesCombined/>} label="رتبه جهانی" value="—"/><Stat icon={<CalendarDays/>} label="مسابقه‌های پیش‌رو" value={String(matches.length)}/></div>
    <section><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold tracking-wide text-brand">فید مسابقه‌ها</p><h2 className="mt-1 text-2xl font-black">پیش‌بینی‌های امروز</h2></div><span className="text-xs text-[var(--muted)]">زمان ایران · منبع رسمی</span></div>{matches.length ? <div className="grid gap-5 lg:grid-cols-2">{matches.map((match, index) => <PredictionCard key={match.providerMatchId} match={match} initial={predictions.get(match.providerMatchId)} index={index}/>)}</div> : <div className="rounded-[26px] border border-dashed border-white/10 p-12 text-center text-sm text-[var(--muted)]">در حال حاضر مسابقه واقعی در پنجره پیش‌رو ثبت نشده است.</div>}</section>
    <section className="mt-12"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">پنج لیگ بزرگ</h2><Link href="/leagues/GB1" className="text-xs text-brand">مشاهده همه ←</Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{LEAGUES.map((league, i) => <Link key={league.code} href={`/leagues/${league.code}`} className="group rounded-2xl border border-white/[.08] bg-[#111116] p-4 transition hover:-translate-y-1 hover:border-brand/50"><span className="text-[11px] font-black text-brand">{String(i + 1).padStart(2, "0")}</span><h3 className="mt-6 font-bold">{league.faName}</h3><span className="mt-3 block text-xs text-[var(--muted)] group-hover:text-white">ورود به لیگ ←</span></Link>)}</div></section>
  </div></main>;
}
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-4 rounded-2xl border border-white/[.08] bg-[#111116] p-5"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand/10 text-brand">{icon}</span><span><small className="block text-xs text-[var(--muted)]">{label}</small><b className="mt-1 block text-2xl">{value}</b></span></div>; }
