import { getDb } from "@/lib/db/mongo";
import { scheduleMatchReminder } from "./qstash";
import { env } from "@/lib/env";
import { teamName } from "@/lib/football/team-names";
import { readableFa } from "@/lib/text";

export async function scheduleUpcomingReminders(){const db=await getDb(),matches=await db.collection<{providerMatchId:string;kickoffAt:Date;status:string}>("matches").find({kickoffAt:{$gt:new Date()},status:"SCHEDULED"}).toArray();let scheduled=0;for(const m of matches){const at=new Date(new Date(m.kickoffAt).getTime()-1800000);if(at<=new Date())continue;try{if(await scheduleMatchReminder(m.providerMatchId,at))scheduled++}catch(e){console.error("match_reminder_scheduling_failed",{matchId:m.providerMatchId,error:e instanceof Error?e.message:"unknown"})}}return scheduled;}
export async function processMatchReminder(matchId:string){const db=await getDb(),match=await db.collection<any>("matches").findOne({providerMatchId:matchId});if(!match||match.status!=="SCHEDULED")return {sent:0,skipped:"match"};const delta=new Date(match.kickoffAt).getTime()-Date.now();if(delta<1200000||delta>2400000)return {sent:0,skipped:"stale"};const users=await db.collection<any>("externalIdentities").aggregate([{$match:{provider:"TELEGRAM",canMessage:true}},{$lookup:{from:"notificationPreferences",localField:"userId",foreignField:"userId",as:"p"}},{$match:{"p.telegramPredictionRemindersEnabled":true}},{$lookup:{from:"predictions",let:{uid:"$userId"},pipeline:[{$match:{$expr:{$and:[{$eq:["$userId","$$uid"]},{$eq:["$matchId",matchId]}]}}}],as:"prediction"}},{$match:{prediction:{$size:0}}}]).toArray();let sent=0;for(const identity of users){const reservation=await db.collection("notificationDeliveries").updateOne({userId:identity.userId,matchId,channel:"TELEGRAM",type:"MISSING_PREDICTION_30_MIN"},{$setOnInsert:{userId:identity.userId,matchId,channel:"TELEGRAM",type:"MISSING_PREDICTION_30_MIN",status:"PROCESSING",createdAt:new Date(),updatedAt:new Date()}},{upsert:true});if(!reservation.upsertedCount)continue;try{const language=identity.p?.[0]?.language==="en"?"en":"fa";const result=await sendTelegram(String(identity.chatId||identity.providerUserId),match,language);await db.collection("notificationDeliveries").updateOne({userId:identity.userId,matchId,channel:"TELEGRAM",type:"MISSING_PREDICTION_30_MIN"},{$set:{status:"SENT",sentAt:new Date(),externalMessageId:String(result.message_id),updatedAt:new Date()}});sent++}catch(e){await db.collection("notificationDeliveries").updateOne({userId:identity.userId,matchId,channel:"TELEGRAM",type:"MISSING_PREDICTION_30_MIN"},{$set:{status:"FAILED",errorCode:e instanceof Error?e.message:"TELEGRAM_ERROR",updatedAt:new Date()}})}}return {sent};}
async function sendTelegram(chatId:string,m:any,language:"fa"|"en"){if(!env.TELEGRAM_BOT_TOKEN)throw Error("TELEGRAM_NOT_CONFIGURED");const home=language==="fa"?readableFa(teamName("fa",Number(m.homeTeam?.id),m.homeTeam?.name||"Home")):m.homeTeam?.name||"Home";const away=language==="fa"?readableFa(teamName("fa",Number(m.awayTeam?.id),m.awayTeam?.name||"Away")):m.awayTeam?.name||"Away";const text=language==="fa"?`⚽ یادآوری پیش‌بینی\n\n${home} مقابل ${away}، ۳۰ دقیقه دیگر شروع می‌شود.\n\nهنوز پیش‌بینی خود را ثبت نکرده‌اید.`:`⚽ Prediction reminder\n\n${home} vs ${away} starts in 30 minutes.\n\nYou haven't submitted your prediction yet.`;const res=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text,reply_markup:{inline_keyboard:[[{text:language==="fa"?"ثبت پیش‌بینی":"Make prediction",web_app:{url:`${env.NEXT_PUBLIC_APP_URL}/matches?match=${encodeURIComponent(m.providerMatchId)}`}}]]}})});const d=await res.json().catch(()=>null);if(!res.ok||!d?.ok)throw Error(d?.description||`TELEGRAM_${res.status}`);return d.result;}
