import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { env } from "@/lib/env";
import { getDb, withMongoTransaction } from "@/lib/db/mongo";
export type Provider = "TELEGRAM" | "BALE";
export type PlatformUser = { id:string; username?:string; displayName?:string; allowsWrite?:boolean; chatId?:string };
const secret=()=>env.SESSION_SECRET||"development-secret-change-me"; const hash=(v:string)=>createHash("sha256").update(v).digest("hex"); const sign=(v:string)=>createHmac("sha256",secret()).update(v).digest("base64url");
const equal=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
export function identitySlotConflict(existingUserId:string|undefined,targetUserId:string,existingProviderUserId:string|undefined,providerUserId:string){return Boolean((existingUserId&&existingUserId!==targetUserId)||(existingProviderUserId&&existingProviderUserId!==providerUserId));}
export function verifyInitData(raw:string,provider:Provider,now=Date.now()):PlatformUser{const bot=provider==="TELEGRAM"?env.TELEGRAM_BOT_TOKEN:env.BALE_BOT_TOKEN;if(!bot||!raw||raw.length>20000)throw Error("PLATFORM_AUTH_INVALID");const p=new URLSearchParams(raw),received=p.get("hash"),auth=Number(p.get("auth_date"));if(!received||!Number.isFinite(auth)||now/1000-auth>3600||auth-now/1000>60)throw Error(auth?"PLATFORM_AUTH_EXPIRED":"PLATFORM_AUTH_INVALID");const check=[...p.entries()].filter(([k])=>k!=="hash").sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");const key=createHmac("sha256","WebAppData").update(bot).digest(),expected=createHmac("sha256",key).update(check).digest("hex");if(!equal(expected,received))throw Error("PLATFORM_AUTH_INVALID");let u:Record<string,unknown>;try{u=JSON.parse(p.get("user")||"{}")}catch{throw Error("PLATFORM_AUTH_INVALID")}if(!u.id)throw Error("PLATFORM_AUTH_INVALID");return{id:String(u.id),username:typeof u.username==="string"?u.username:undefined,displayName:[u.first_name,u.last_name].filter(v=>typeof v==="string").join(" ")||undefined,allowsWrite:u.allows_write_to_pm===true,chatId:String(u.id)};}
export function pendingCookie(user:PlatformUser,provider:Provider){const data=Buffer.from(JSON.stringify({provider,user,expiresAt:Date.now()+600000})).toString("base64url");return `${data}.${sign(data)}`;}
export const makePendingPlatformCookie = pendingCookie;
export function readPending(value?:string){if(!value)return null;const [data,sig]=value.split(".");if(!data||!sig||!equal(sign(data),sig))return null;try{const v=JSON.parse(Buffer.from(data,"base64url").toString()) as {provider:Provider;user:PlatformUser;expiresAt:number};return v.expiresAt>Date.now()?v:null}catch{return null;}}
export async function attachIdentity(userId:string,provider:Provider,user:PlatformUser){const db=await getDb(),now=new Date();try{await withMongoTransaction(async(_db,session)=>{const existing=await db.collection<any>("externalIdentities").findOne({provider,providerUserId:user.id},{session});const own=await db.collection<any>("externalIdentities").findOne({userId,provider},{session});if(identitySlotConflict(existing&&String(existing.userId),userId,own&&String(own.providerUserId),user.id))throw Error("PLATFORM_IDENTITY_CONFLICT");await db.collection("externalIdentities").updateOne({provider,providerUserId:user.id},{$set:{userId,provider,providerUserId:user.id,providerUsername:user.username??null,providerDisplayName:user.displayName??null,chatId:user.chatId??null,canMessage:user.allowsWrite===true,lastSeenAt:now,updatedAt:now},$setOnInsert:{linkedAt:now,createdAt:now}},{upsert:true,session})});const preferenceField=provider==="TELEGRAM"?"telegramPredictionRemindersEnabled":"balePredictionRemindersEnabled";const defaults=provider==="TELEGRAM"?{userId,createdAt:now,telegramReminderScope:"GLOBAL_LEADERBOARD",[preferenceField]:true}:{userId,createdAt:now,[preferenceField]:true};await db.collection("notificationPreferences").updateOne({userId},{$set:{updatedAt:now},$setOnInsert:defaults},{upsert:true})}catch(e){if(e instanceof Error&&e.message==="PLATFORM_IDENTITY_CONFLICT")throw e;if((e as {code?:number})?.code===11000)throw Error("PLATFORM_IDENTITY_CONFLICT");throw e}}
export async function createLinkToken(userId:string,provider:Provider){const token=randomBytes(32).toString("base64url");await getDb().then(db=>db.collection("accountLinkTokens").insertOne({userId,provider,tokenHash:hash(token),expiresAt:new Date(Date.now()+600000),usedAt:null,createdAt:new Date()}));return token;}
export async function consumeLinkToken(token:string,provider:Provider,userId:string,user:PlatformUser){const db=await getDb(),row=await db.collection("accountLinkTokens").findOne({tokenHash:hash(token),provider,userId,usedAt:null,expiresAt:{$gt:new Date()}});if(!row)throw Error("LINK_TOKEN_INVALID");await attachIdentity(userId,provider,user);const consumed=await db.collection("accountLinkTokens").updateOne({_id:row._id,usedAt:null},{$set:{usedAt:new Date()}});if(!consumed.modifiedCount)throw Error("LINK_TOKEN_INVALID");}
export async function getIdentity(userId:string,provider:Provider){return getDb().then(db=>db.collection("externalIdentities").findOne({userId,provider},{projection:{_id:0,providerUsername:1,providerDisplayName:1,canMessage:1,linkedAt:1}}));}
