"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Check, Crown, ImagePlus, Link2, Loader2, Save, ShieldCheck, UserRoundCog } from "lucide-react";
import { motion } from "motion/react";
import { useRouter } from "next/navigation";
import { useLanguage } from "@/components/LanguageProvider";

export default function ClubSettings({ params }: { params: Promise<{ clubId: string }> }) {
  const router = useRouter(); const { t } = useLanguage(); const [clubId, setClubId] = useState(""); const [club, setClub] = useState<any>(null); const [members, setMembers] = useState<any[]>([]); const [image, setImage] = useState<string | null>(null); const [email, setEmail] = useState(""); const [invite, setInvite] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { params.then(({ clubId: id }) => { setClubId(id); fetch(`/api/clubs/${id}/members`).then((r) => r.json()).then((data) => { setClub(data.club); setMembers(data.members ?? []); setImage(data.club?.imageUrl ?? null); }); }); }, [params]);
  function chooseImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!/^image\/(png|jpe?g|webp)$/i.test(file.type) || file.size > 2 * 1024 * 1024) return setMessage(t("تصویر باید PNG، JPG یا WEBP و کمتر از ۲ مگابایت باشد.", "Choose a PNG, JPEG or WebP image under 2 MB.")); const reader = new FileReader(); reader.onload = () => setImage(String(reader.result)); reader.readAsDataURL(file); }
  async function saveImage(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch(`/api/clubs/${clubId}/settings`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ imageData: image }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setMessage(data.error ?? "Could not save Club image"); setMessage(t("تصویر باشگاه ذخیره شد.", "Club image saved.")); router.refresh(); }
  async function inviteMember(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/clubs/${clubId}/invitations`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Could not create invitation"); setInvite(data.inviteToken); setEmail(""); }
  async function transfer(userId: string) { if (!confirm(t("انتقال مالکیت به این عضو؟", "Transfer ownership to this member?"))) return; const response = await fetch(`/api/clubs/${clubId}/members`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "TRANSFER", userId }) }); if (response.ok) router.replace("/club"); else setMessage((await response.json()).error ?? "Could not transfer ownership"); }
  return <main className="min-h-screen px-4 pb-28 pt-20 md:px-8 md:pt-28"><div className="mx-auto max-w-3xl"><Link href="/club" className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-[var(--muted)] hover:text-brand"><ArrowLeft size={16} />{t("بازگشت به باشگاه", "Back to Club")}</Link><motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_90%_0%,rgba(32,184,121,.24),transparent_38%),linear-gradient(145deg,#142a1e,#08100b)] p-6 sm:p-8"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-brand/15 text-brand"><UserRoundCog size={24} /></div><div><p className="text-xs font-black tracking-[.2em] text-brand">CLUB ADMIN</p><h1 className="mt-1 text-3xl font-black">{club?.name ?? "Club"}</h1></div></div></motion.section>
    <form onSubmit={saveImage} className="mt-4 rounded-[1.75rem] border border-white/10 bg-[#101812] p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-brand"><ImagePlus size={18} /><h2 className="font-black">{t("هویت تصویری", "Visual identity")}</h2></div><p className="mt-2 text-sm leading-7 text-[var(--muted)]">{t("یک نشان گرد انتخاب کنید تا باشگاه شما در همه‌جا قابل تشخیص باشد.", "Choose a circular crest so your Club is instantly recognizable everywhere.")}</p></div><Crown className="text-[#eacb70]" size={20} /></div><div className="mt-6 flex flex-col items-center gap-5 sm:flex-row"><div className="relative h-32 w-32 shrink-0 rounded-full border-2 border-brand/60 bg-[#102119] p-1 shadow-[0_0_0_8px_rgba(32,184,121,.08)]"><div className="grid h-full w-full place-items-center overflow-hidden rounded-full bg-[radial-gradient(circle_at_30%_20%,#2c9d6d,#102119_72%)] text-3xl font-black">{image ? <img src={image} alt="Club preview" className="h-full w-full object-cover" /> : club?.name?.slice(0, 2).toUpperCase()}</div><label className="absolute bottom-1 right-0 grid h-9 w-9 cursor-pointer place-items-center rounded-full border-2 border-[#101812] bg-brand text-[#07100b] shadow-lg"><ImagePlus size={16} /><input type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseImage} className="sr-only" /></label></div><div><p className="text-sm font-black">{t("نشان باشگاه", "Club crest")}</p><p className="mt-1 text-xs leading-6 text-[var(--muted)]">{t("مربع انتخاب کنید؛ تصویر به شکل دایره نمایش داده می‌شود.", "Choose a square image; it will be displayed as a circle.")}</p><button type="submit" disabled={busy} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-brand px-4 py-3 text-sm font-black text-[#07100b] disabled:opacity-60">{busy ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />}{t("ذخیره نشان", "Save crest")}</button></div></div>{message && <p className="mt-4 rounded-xl bg-brand/10 p-3 text-sm text-brand">{message}</p>}</form>
    <form onSubmit={inviteMember} className="mt-4 rounded-[1.75rem] border border-white/10 bg-[#101812] p-5 sm:p-7"><div className="flex items-center gap-2 text-brand"><Link2 size={18} /><h2 className="font-black">{t("دعوت عضو", "Invite a member")}</h2></div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="player@example.com" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-brand" /><button className="rounded-xl bg-brand px-4 py-3 text-sm font-black text-[#07100b]">{t("ساخت لینک", "Create link")}</button></div>{invite && <div className="mt-3 flex items-center gap-2 rounded-xl bg-brand/10 p-3 text-xs text-brand"><Check size={15} /><span className="break-all">{typeof window !== "undefined" ? `${window.location.origin}/invite/${invite}` : invite}</span></div>}</form>
    <section className="mt-4 rounded-[1.75rem] border border-white/10 bg-[#101812] p-5 sm:p-7"><div className="flex items-center gap-2 text-brand"><Crown size={18} /><h2 className="font-black">{t("انتقال مالکیت", "Transfer ownership")}</h2></div><p className="mt-2 text-sm leading-7 text-[var(--muted)]">{t("مالک جدید باید عضو فعلی باشگاه باشد.", "The new owner must already be a current Club member.")}</p><div className="mt-4 space-y-2">{members.filter((member) => member.role !== "OWNER").map((member) => <button key={member.userId} onClick={() => transfer(member.userId)} className="flex w-full items-center justify-between rounded-xl border border-white/10 p-3 text-start transition hover:border-brand/50 hover:bg-brand/[.05]"><span className="font-bold">{member.user?.username ?? "Member"}</span><span className="text-xs font-black text-brand">{t("انتقال", "Transfer")}</span></button>)}</div></section>
  </div></main>;
}
