import Link from "next/link";
import { notFound } from "next/navigation";
import { ObjectId } from "mongodb";
import { ShieldCheck } from "lucide-react";
import { getDb } from "@/lib/db/mongo";
import { currentUserId } from "@/lib/auth/session";
import { requireClubMember } from "@/lib/domain/clubs";
import { LEAGUES } from "@/lib/football/leagues";
import { T } from "@/components/LanguageProvider";
import { LocaleChevron } from "@/components/LocaleChevron";
import { BackButton } from "@/components/BackButton";
export const dynamic = "force-dynamic";
export default async function ClubMatchCentre({ params }: { params: Promise<{ clubId: string }> }) { const { clubId } = await params; if (!ObjectId.isValid(clubId)) notFound(); const userId = await currentUserId(); if (!userId) notFound(); const db = await getDb(); let club; try { ({ club } = await requireClubMember(db, clubId, userId)); } catch { notFound(); } const year = Number((await db.collection("matches").findOne({}, { sort: { seasonStartYear: -1 }, projection: { seasonStartYear: 1 } }))?.seasonStartYear ?? new Date().getUTCFullYear()); return <main className="min-h-screen px-5 pb-28 pt-24 md:px-8 md:pt-32"><div className="mx-auto max-w-5xl"><BackButton label="Your Club"/><section className="mt-1 rounded-[2rem] border border-white/[.08] bg-[radial-gradient(circle_at_90%_0%,rgba(32,184,121,.25),transparent_38%),linear-gradient(145deg,#14251c,#0a0f0c)] p-7 md:p-9"><div className="flex items-start justify-between gap-4"><div><div className="inline-flex items-center gap-2 rounded-full border border-brand/30 bg-brand/10 px-3 py-1.5 text-xs font-black text-brand"><ShieldCheck size={14}/><T fa="رقابت باشگاه" en="CLUB COMPETITION"/></div><h1 className="mt-4 text-4xl font-black">{club.name}</h1><p className="mt-2 text-sm text-white/60"><T fa={`مرکز مسابقات · ${year}/${String(year + 1).slice(-2)}`} en={`Match Centre · ${year}/${String(year + 1).slice(-2)}`}/></p></div><Link href={`/club/${clubId}/members`} className="grid h-11 w-11 place-items-center rounded-xl border border-white/10 text-[var(--muted)] hover:border-brand/50 hover:text-brand" aria-label="Members"><LocaleChevron/></Link></div></section><div className="mt-6 grid gap-4 sm:grid-cols-2">{LEAGUES.map((league) => <Link key={league.code} href={`/club/${clubId}/league/${league.code}`} className="group flex items-center gap-4 rounded-2xl border border-white/10 bg-[#101512] p-5 transition hover:-translate-y-1 hover:border-brand/50 hover:shadow-[0_16px_40px_rgba(32,184,121,.1)]"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/[.04] p-2"><img src={league.logo} alt="" className="league-logo h-full w-full object-contain"/></span><span className="min-w-0 flex-1"><b className="block text-lg"><T fa={league.faName} en={league.enName}/></b><small className="mt-1 block text-[var(--muted)]"><T fa="رقابت خودکار فعال است" en="Automatically enabled"/></small></span><LocaleChevron className="text-[var(--muted)] transition group-hover:text-brand"/></Link>)}</div></div></main>; }
