import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";

const slugs = ["football-predictions", "how-scoring-works", "telegram-football-predictions", "bale-football-predictions"] as const;
type Slug = typeof slugs[number];
export function generateStaticParams() { return ["fa", "en"].flatMap((locale) => slugs.map((slug) => ({ locale, slug }))); }
function valid(locale: string, slug: string): locale is "fa" | "en" { return (locale === "fa" || locale === "en") && slugs.includes(slug as Slug); }
function copy(locale: "fa" | "en", slug: Slug) { const fa = locale === "fa"; const data: Record<Slug, { enTitle: string; faTitle: string; enDescription: string; faDescription: string; enBody: string; faBody: string }> = {
  "football-predictions": { enTitle: "Football Predictions", faTitle: "پیش‌بینی فوتبال", enDescription: "Predict football match scores, compare results, and compete on LowBlock leaderboards.", faDescription: "نتیجه مسابقات فوتبال را پیش‌بینی کنید، امتیاز بگیرید و در جدول‌های LowBlock رقابت کنید.", enBody: "Choose the expected score for both teams before kick-off. Accurate predictions help you climb global, league, weekly, and club leaderboards.", faBody: "نتیجه مورد انتظار هر دو تیم را قبل از شروع بازی انتخاب کنید. پیش‌بینی‌های دقیق به شما کمک می‌کنند در جدول‌های جهانی، لیگ‌ها، هفتگی و باشگاهی صعود کنید." },
  "how-scoring-works": { enTitle: "How Football Prediction Scoring Works", faTitle: "نحوه امتیازدهی پیش‌بینی فوتبال", enDescription: "Learn how LowBlock scores football predictions and ranks players.", faDescription: "با نحوه محاسبه امتیاز پیش‌بینی فوتبال و رتبه‌بندی بازیکنان در LowBlock آشنا شوید.", enBody: "LowBlock rewards predictions that are close to the final result. Predictions lock when the match starts so every player competes fairly.", faBody: "LowBlock به پیش‌بینی‌هایی که به نتیجه نهایی نزدیک‌تر هستند امتیاز می‌دهد. با شروع مسابقه، پیش‌بینی‌ها قفل می‌شوند تا رقابت برای همه عادلانه باشد." },
  "telegram-football-predictions": { enTitle: "Telegram Football Predictions", faTitle: "پیش‌بینی فوتبال در تلگرام", enDescription: "Play LowBlock football predictions through Telegram and follow the global leaderboard.", faDescription: "از طریق تلگرام در پیش‌بینی فوتبال LowBlock شرکت کنید و جدول جهانی را دنبال کنید.", enBody: "Connect your Telegram identity to one LowBlock account, submit predictions, and receive reminders for matches you have not predicted.", faBody: "هویت تلگرام خود را به یک حساب LowBlock متصل کنید، پیش‌بینی ثبت کنید و برای مسابقاتی که پیش‌بینی نکرده‌اید یادآوری دریافت کنید." },
  "bale-football-predictions": { enTitle: "Bale Football Predictions", faTitle: "پیش‌بینی فوتبال در بله", enDescription: "Play LowBlock football predictions through Bale and compete with the global community.", faDescription: "از طریق بله در پیش‌بینی فوتبال LowBlock شرکت کنید و با جامعه جهانی رقابت کنید.", enBody: "Connect your Bale account to LowBlock and keep your predictions, awards, and leaderboard history together.", faBody: "حساب بله خود را به LowBlock متصل کنید تا پیش‌بینی‌ها، افتخارات و سابقه جدول امتیازات شما یکجا حفظ شود." },
}; const item = data[slug]; return { title: fa ? item.faTitle : item.enTitle, description: fa ? item.faDescription : item.enDescription, body: fa ? item.faBody : item.enBody }; }

export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; if (!valid(locale, slug)) return {}; const item = copy(locale, slug as Slug); return { title: item.title, description: item.description, alternates: { canonical: `/${locale}/${slug}`, languages: { fa: `/fa/${slug}`, en: `/en/${slug}`, "x-default": `/en/${slug}` } }, openGraph: { title: `${item.title} | LowBlock`, description: item.description, type: "website" } }; }

export default async function LocalizedSeoPage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale, slug } = await params; if (!valid(locale, slug)) notFound(); const item = copy(locale, slug as Slug); const fa = locale === "fa"; return <main dir={fa ? "rtl" : "ltr"} lang={fa ? "fa" : "en"} className="min-h-screen px-4 pb-28 pt-24 md:px-8 md:pt-32"><article className="mx-auto max-w-3xl rounded-[2rem] border border-white/10 bg-white/[.03] p-7 md:p-12"><p className="text-xs font-black tracking-[.2em] text-brand">LOWBLOCK</p><h1 className="mt-4 text-4xl font-black">{item.title}</h1><p className="mt-5 text-base leading-8 text-white/65">{item.body}</p><h2 className="mt-10 text-2xl font-black">{fa ? "رقابت عادلانه و قابل پیگیری" : "Fair, trackable competition"}</h2><p className="mt-3 leading-8 text-white/65">{fa ? "امتیازها، پیش‌بینی‌ها و افتخارات شما در حساب LowBlock ثبت می‌شوند و می‌توانید عملکرد خود را در مسابقات مختلف دنبال کنید." : "Your points, predictions, and awards stay connected to your LowBlock account so you can follow your performance across competitions."}</p><div className="mt-8 flex flex-wrap gap-4 text-sm font-bold text-brand"><Link href={`/${locale}`}>{fa ? "صفحه اصلی" : "Home"}</Link><Link href="/matches">{fa ? "مشاهده مسابقات" : "View matches"}</Link><Link href={`/${locale}/football-predictions`}>{fa ? "پیش‌بینی فوتبال" : "Football predictions"}</Link></div></article></main>; }
