import { notFound } from "next/navigation";
import { ObjectId } from "mongodb";
import { getDb } from "@/lib/db/mongo";
import { getCanonicalLeaderboard } from "@/lib/domain/leaderboards";
import { T } from "@/components/LanguageProvider";
export const dynamic = "force-dynamic";
export default async function PublicProfile({ params }: { params: Promise<{ username: string }> }) {
  const { username } = await params; const db = await getDb(); const user = await db.collection<any>("users").findOne({ normalizedUsername: username.toLowerCase() }, { projection: { username: 1, avatarUrl: 1, bio: 1 } }); if (!user) notFound();
  const year = Number((await db.collection("matches").findOne({}, { sort: { seasonStartYear: -1 }, projection: { seasonStartYear: 1 } }))?.seasonStartYear ?? new Date().getUTCFullYear()); const global = await getCanonicalLeaderboard(db, { seasonStartYear: year }, 1000); const row = global.find(item => item.userId === String(user._id)); const userId = String(user._id); const totalPredictions = await db.collection("predictions").countDocuments({ userId }); const exact = await db.collection("predictionScores").countDocuments({ userId, exactScore: true }); const membership = await db.collection<any>("clubMemberships").findOne({ userId, leftAt: null }); const club = membership && ObjectId.isValid(membership.clubId) ? await db.collection<any>("clubs").findOne({ _id: new ObjectId(membership.clubId) }, { projection: { name: 1, visibility: 1 } }) : null;
  const metrics: Array<[string | number, string]> = [[row?.rank ?? "—", "Rank"], [row?.points ?? 0, "Season points"], [totalPredictions, "Predictions"], [exact, "Exact"]];
  return <main className="min-h-screen px-5 pb-28 pt-24 md:px-8 md:pt-32"><div className="mx-auto max-w-2xl"><section className="rounded-3xl border border-white/10 bg-[linear-gradient(145deg,#14251c,#0a0f0c)] p-7 text-center"><div className="mx-auto grid h-20 w-20 place-items-center overflow-hidden rounded-full border-2 border-brand/30 bg-brand/10 text-xl font-black">{user.avatarUrl ? <img src={user.avatarUrl} alt="" className="h-full w-full object-cover"/> : user.username.slice(0, 2).toUpperCase()}</div><h1 className="mt-4 text-3xl font-black">{user.username}</h1><p className="mt-1 text-sm text-[var(--muted)]">@{user.username}</p>{user.bio && <p className="mt-4 text-sm text-white/70">{user.bio}</p>}</section><section className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{metrics.map(([value, label]) => <div key={label} className="rounded-2xl border border-white/10 bg-[#101512] p-4 text-center"><b className="block text-2xl text-brand">{value}</b><small className="text-[var(--muted)]"><T fa={label === "Season points" ? "امتیاز فصل" : label === "Predictions" ? "پیش‌بینی" : label === "Exact" ? "دقیق" : "رتبه"} en={label}/></small></div>)}</section>{club && club.visibility !== "PRIVATE" && <section className="mt-4 rounded-2xl border border-white/10 bg-[#101512] p-5"><p className="text-xs font-black tracking-[.16em] text-brand">CURRENT CLUB</p><h2 className="mt-2 text-xl font-black">{club.name}</h2></section>}</div></main>;
}
