import NextLink from "next/link";
import { ObjectId } from "mongodb";
import { currentUserId } from "@/lib/auth/session";
import { getDb } from "@/lib/db/mongo";
import { getCanonicalLeaderboard } from "@/lib/domain/leaderboards";
import { getMatches, getPredictions } from "@/lib/football/data";
import { HomeFixtureSlider } from "@/components/HomeFixtureSlider";
import { HomeHeroSlang } from "@/components/HomeHeroSlang";
import { FEATURED_COMPETITION_CODES, LEAGUES as ALL_LEAGUES } from "@/lib/football/leagues";
import { T } from "@/components/LanguageProvider";

export const dynamic = "force-dynamic";
const featuredLeagues = FEATURED_COMPETITION_CODES.map((code) => ALL_LEAGUES.find((league) => league.code === code)!).filter(Boolean);
const LEAGUES = featuredLeagues;

function Link({ href, ...props }: React.ComponentProps<typeof NextLink>) {
  const target = href === "/lowblock" && props.className === "text-xs font-bold text-brand" ? "/leagues" : href;
  return <NextLink href={target} {...props} />;
}

export default async function Home() {
  const userId = await currentUserId(); const fetchedMatches = await getMatches({ limit: 20 }); const eligibleMatches = fetchedMatches.filter((match) => match.status === "SCHEDULED" && new Date(match.kickoffAt).getTime() > Date.now()); const allPredictions = await getPredictions(eligibleMatches.map((match) => match.providerMatchId), userId ?? "guest"); const matches = eligibleMatches.filter((match) => !allPredictions.has(match.providerMatchId)).slice(0, 5); const predictions = new Map([...allPredictions].filter(([matchId]) => matches.some((match) => match.providerMatchId === matchId))); const allPredicted = userId !== null && eligibleMatches.length > 0 && matches.length === 0;
  let username = ""; let rank: number | string = "—"; let points = 0; let exact = 0; let club: any = null;
  if (userId) { const db = await getDb(); const user = await db.collection<any>("users").findOne({ _id: new ObjectId(userId) }, { projection: { username: 1 } }); username = user?.username ?? ""; const year = Number((await db.collection("matches").findOne({}, { sort: { seasonStartYear: -1 }, projection: { seasonStartYear: 1 } }))?.seasonStartYear ?? new Date().getUTCFullYear()); const mine = (await getCanonicalLeaderboard(db, { seasonStartYear: year }, 1000)).find((row) => row.userId === userId); rank = mine?.rank ?? "—"; points = mine?.points ?? 0; exact = mine?.exact ?? 0; const membership = await db.collection<any>("clubMemberships").findOne({ userId, leftAt: null }); club = membership ? await db.collection<any>("clubs").findOne({ _id: new ObjectId(membership.clubId) }, { projection: { name: 1 } }) : null; }
  return <main className="min-h-screen pb-24 pt-20"><div className="mx-auto max-w-7xl px-4 md:px-8">
    <section className="home-hero relative mt-5 overflow-hidden rounded-[2rem] border border-white/[.08] p-6 md:p-10"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-brand/10 blur-3xl" /><div className="relative"><p className="text-xs font-black tracking-[.2em] text-brand">{username ? <T fa={`سلام ${username}`} en={`Hello, ${username}`} /> : <T fa="به LowBlock خوش آمدید" en="Welcome to LowBlock" />}</p><h1 className="mt-3 max-w-2xl text-4xl font-black leading-tight md:text-6xl"><HomeHeroSlang /></h1><p className="mt-4 max-w-xl text-sm leading-7 text-white/60"><T fa="هر پیش‌بینی شما برای LowBlock، لیگ‌ها و باشگاهتان امتیاز دارد." en="Every prediction contributes to LowBlock, leagues and your Club." /></p><div className="mt-7 flex flex-wrap gap-3"><Link href="/matches" className="rounded-xl bg-brand px-5 py-3 text-sm font-black"><T fa="پیش‌بینی مسابقه" en="Predict matches" /></Link><Link href="/lowblock" className="rounded-xl border border-white/10 bg-white/[.04] px-5 py-3 text-sm font-black"><T fa="جدول کلی" en="Global standings" /></Link></div></div></section>
    {userId && <section className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label={<T fa="رتبه کلی" en="Global rank" />} value={`#${rank}`} /><Metric label={<T fa="امتیاز فصل" en="Season points" />} value={String(points)} /><Metric label={<T fa="پیش‌بینی دقیق" en="Exact picks" />} value={String(exact)} /><Link href={club ? "/club" : "/club/create"} className="rounded-2xl border border-brand/20 bg-brand/10 p-4"><small className="text-brand">{club ? <T fa="باشگاه شما" en="Your Club" /> : <T fa="ساخت باشگاه" en="Create a Club" />}</small><b className="mt-1 block truncate text-lg">{club?.name ?? <T fa="هویت تیمی خود را بسازید" en="Build your team identity" />}</b></Link></section>}
    <section className="mt-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[.16em] text-brand"><T fa="رقابت‌ها" en="Competitions" /></p><h2 className="mt-2 text-2xl font-black"><T fa="رقابت‌های فعال" en="Find your competition" /></h2></div><Link href="/lowblock" className="text-xs font-bold text-brand"><T fa="مشاهده همه" en="View all" /></Link></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{LEAGUES.map((league) => <Link key={league.code} href={`/leagues/${league.code}`} className="group rounded-2xl border border-white/10 bg-[#101512] p-4 transition hover:-translate-y-1 hover:border-brand/40"><img src={league.logo} alt="" className="h-10 w-10 rounded-xl object-cover grayscale brightness-0 invert transition group-hover:grayscale-0 group-hover:brightness-100" /><span className="mt-4 block text-sm font-bold"><T fa={league.faName} en={league.enName} /></span></Link>)}</div></section>
    <section className="mt-8 pb-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[.16em] text-brand"><T fa="بازی‌های پیش رو" en="UPCOMING MATCHES" /></p><h2 className="mt-2 text-2xl font-black"><T fa="پیش‌بینی‌های بعدی" en="Upcoming predictions" /></h2></div><Link href="/matches" className="text-xs font-bold text-brand"><T fa="پیش‌بینی کنید" en="Predict" /></Link></div><HomeFixtureSlider matches={matches} predictions={Object.fromEntries(predictions)} allPredicted={allPredicted} /></section>
  </div></main>;
}

function Metric({ label, value }: { label: React.ReactNode; value: string }) { return <div className="metric-tile group relative overflow-hidden rounded-[1.35rem] border border-white/[.1] bg-[linear-gradient(145deg,rgba(25,52,38,.82),rgba(10,17,13,.9))] p-4 shadow-[0_14px_40px_rgba(0,0,0,.18)] transition duration-300 hover:-translate-y-1 hover:border-brand/45"><span className="metric-tile-glow"/><span className="relative block h-1 w-10 rounded-full bg-brand/70 transition-all duration-300 group-hover:w-16"/><small className="relative mt-3 block truncate text-[10px] font-black tracking-wide text-white/50">{label}</small><b className="relative mt-1 block text-2xl font-black tracking-tight text-white">{value}</b><span className="relative mt-3 block h-1 overflow-hidden rounded-full bg-white/10"><span className="block h-full w-2/3 rounded-full bg-gradient-to-r from-brand/30 to-brand"/></span></div>; }
