"use client";
import { useEffect, useState } from "react";
import { Share2, Trophy } from "lucide-react";
import { shareAward } from "@/lib/awards/share";
import { useLanguage } from "@/components/LanguageProvider";
import { getAwardLabel, getAwardPeriod } from "@/lib/awards/presentation";

type Award = { id: string; competitionName: string; type?: string; periodId?: string; roundNumber?: number; seasonStartYear?: number; trophyUrl: string };
export function AwardsSection() {
  const { t, language } = useLanguage(); const [awards, setAwards] = useState<Award[]>([]); const [selected, setSelected] = useState<Award | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/awards").then(r => r.ok ? r.json() : null).then(data => setAwards(data?.awards ?? [])).catch(() => undefined); }, []);
  async function share() { if (!selected) return; try { const result = await shareAward(selected.id, language); setMessage(result === "saved" ? t("تصویر ذخیره شد؛ لینک LowBlock کپی شد.", "Image saved; LowBlock link copied.") : t("با موفقیت به اشتراک گذاشته شد.", "Shared successfully.")); } catch { setMessage(t("اشتراک‌گذاری لغو شد یا در دسترس نیست.", "Sharing was cancelled or unavailable.")); } }
  const title = (award: Award) => getAwardLabel(award.type, language); const period = (award: Award) => getAwardPeriod(award, language);
  return <section className="mt-4 rounded-2xl border border-white/[.08] bg-[#101512] p-5 md:p-7"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand/15 text-brand"><Trophy size={19}/></span><div><p className="text-xs font-black tracking-[.18em] text-brand">{t("جوایز", "AWARDS")}</p><h2 className="mt-1 text-xl font-black">{t("مجموعه شما", "Your collection")}</h2></div></div>{awards.length === 0 ? <p className="mt-5 text-sm text-[var(--muted)]">{t("جوایز شما اینجا نمایش داده می‌شود.", "Your earned awards will appear here.")}</p> : <div className="mt-5 grid gap-3 sm:grid-cols-2">{awards.map(award => <button key={award.id} type="button" onClick={() => { setMessage(""); setSelected(award); }} className="flex items-center gap-3 rounded-2xl border border-brand/15 bg-brand/[.05] p-3 text-left transition hover:border-brand/40"><img src={award.trophyUrl} alt={`${title(award)} ${award.competitionName}`} loading="lazy" className="h-20 w-20 object-contain"/><span><b className="block">{award.competitionName}</b><small className="mt-1 block text-[var(--muted)]">{title(award)}</small><small className="mt-1 block text-xs text-white/55">{award.seasonStartYear ? `${award.seasonStartYear}/${String(award.seasonStartYear + 1).slice(-2)} · ` : ""}{period(award)}</small></span></button>)}</div>}{selected && <div className="fixed inset-0 z-[95] grid place-items-center bg-black/80 p-4" role="dialog" aria-modal="true" aria-label={`${title(selected)} award`} onClick={() => setSelected(null)}><div className="w-full max-w-md rounded-3xl border border-brand/25 bg-[#0b130f] p-6 text-center" onClick={e => e.stopPropagation()}><img src={selected.trophyUrl} alt={`${title(selected)} ${selected.competitionName}`} className="mx-auto h-64 w-full object-contain"/><h3 className="text-xl font-black">{selected.competitionName}</h3><p className="mt-1 text-sm text-white/55">{title(selected)} · {period(selected)}</p><div className="mt-6 flex justify-center gap-3"><button type="button" onClick={share} className="inline-flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-black text-[#06120c]"><Share2 size={16}/>{t("اشتراک‌گذاری", "SHARE")}</button><button type="button" onClick={() => setSelected(null)} className="rounded-xl border border-white/15 px-5 py-3 text-sm font-black">{t("بستن", "CLOSE")}</button></div>{message && <p className="mt-4 text-xs text-brand">{message}</p>}</div></div>}</section>;
}
