"use client";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { Share2 } from "lucide-react";
import { shareAward } from "@/lib/awards/share";
type Award = { id: string; competitionName: string; roundNumber: number; seasonStartYear: number };
type Phase = "darkening" | "hero" | "details";
const sprayPieces = Array.from({ length: 18 }, (_, index) => index);
function whenPageIsReady() { return new Promise<void>(resolve => { const ready = () => { void document.fonts?.ready.then(() => resolve()); }; if (document.readyState === "complete") ready(); else window.addEventListener("load", ready, { once: true }); }); }
export function AwardReveal() {
  const pathname = usePathname(); const [awards, setAwards] = useState<Award[]>([]); const [index, setIndex] = useState(0); const [phase, setPhase] = useState<Phase>("darkening"); const [imageReady, setImageReady] = useState(false); const [darkReady, setDarkReady] = useState(false); const [exiting, setExiting] = useState(false); const [busy, setBusy] = useState(false); const continueRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { let active = true; void whenPageIsReady().then(() => { if (!active) return; const repeatDemo = process.env.NODE_ENV !== "production" && pathname === "/" ? "?repeatDemo=1" : ""; return fetch(`/api/awards/unrevealed${repeatDemo}`).then(r => r.ok ? r.json() : null).then(data => { if (active && data?.awards?.length) { setAwards(data.awards); setIndex(0); setPhase("darkening"); setImageReady(false); setDarkReady(false); setExiting(false); } }); }).catch(() => undefined); return () => { active = false; }; }, [pathname]);
  useEffect(() => { if (!awards.length) return; const timer = window.setTimeout(() => setDarkReady(true), 1000); return () => window.clearTimeout(timer); }, [awards.length, index]);
  useEffect(() => { if (!imageReady || !darkReady || !awards.length) return; if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) { setPhase("details"); continueRef.current?.focus(); return; } setPhase("hero"); const timer = window.setTimeout(() => { setPhase("details"); continueRef.current?.focus(); }, 2700); return () => window.clearTimeout(timer); }, [imageReady, darkReady, awards.length, index]);
  if (!awards.length || !awards[index]) return null; const award = awards[index];
  async function finish() { setExiting(true); window.setTimeout(async () => { await fetch(`/api/awards/${award.id}/reveal`, { method: "PATCH" }).catch(() => undefined); if (index + 1 >= awards.length) setAwards([]); else { setIndex(index + 1); setPhase("darkening"); setImageReady(false); setDarkReady(false); setExiting(false); } }, 360); }
  async function share() { setBusy(true); try { await shareAward(award.id); } finally { setBusy(false); } }
  return <div className={`award-reveal-backdrop award-phase-${phase} ${exiting ? "award-reveal-exiting" : ""}`} role="dialog" aria-modal="true" aria-labelledby="award-reveal-title" onKeyDown={event => { if (event.key === "Escape") void finish(); }}><div className="award-spray award-spray-left" aria-hidden="true">{sprayPieces.map(piece => <i key={piece} />)}</div><div className="award-spray award-spray-right" aria-hidden="true">{sprayPieces.map(piece => <i key={piece} />)}</div><main className="award-reveal-stage"><div className="award-reveal-glow"/><img src={`/api/awards/${award.id}/trophy`} alt={`${award.competitionName} Round Winner, ${award.seasonStartYear}/${String(award.seasonStartYear + 1).slice(-2)} Matchday ${award.roundNumber}`} className="award-reveal-trophy" onLoad={async event => { await event.currentTarget.decode().catch(() => undefined); setImageReady(true); }}/><div className="award-reveal-copy"><p className="award-reveal-kicker">{award.competitionName}</p><h2 id="award-reveal-title">ROUND WINNER</h2><p className="award-reveal-meta">{award.seasonStartYear}/{String(award.seasonStartYear + 1).slice(-2)} · MD{String(award.roundNumber).padStart(2, "0")}</p><p className="award-reveal-scope">LOW BLOCK LEVEL</p><div className="award-reveal-actions"><button type="button" disabled={busy} onClick={share} className="award-share-button"><Share2 size={17}/>SHARE YOUR WIN</button><button ref={continueRef} type="button" onClick={finish} className="award-continue-button">CONTINUE</button></div></div></main></div>;
}
