"use client";
import { useState } from "react";
import { BarChart3, CalendarDays } from "lucide-react";
import { MatchAnalytics } from "@/components/MatchAnalytics";
import { useLanguage } from "@/components/LanguageProvider";
import { formatIranDate, formatIranTime } from "@/lib/football/time";
import { teamName } from "@/lib/football/team-names";
type Fixture = { providerMatchId: string; kickoffAt: string; status: string; homeGoals: number | null; awayGoals: number | null; homeTeam: { id: number; name: string; logoUrl: string | null }; awayTeam: { id: number; name: string; logoUrl: string | null } };
export function ClubRoundFixtures({ fixtures, clubId }: { fixtures: Fixture[]; clubId: string }) { const { language, t } = useLanguage(); const [selected, setSelected] = useState<string | null>(null); return <><section className="mt-5 space-y-3">{fixtures.map(fixture => { const finished = fixture.status === "FINISHED"; return <button key={fixture.providerMatchId} onClick={() => setSelected(fixture.providerMatchId)} className="group w-full rounded-2xl border border-white/10 bg-[#101512] p-4 text-start transition hover:-translate-y-0.5 hover:border-brand/50 hover:shadow-[0_16px_40px_rgba(32,184,121,.1)]"><div className="flex items-center justify-between text-[10px] text-[var(--muted)]"><span className="inline-flex items-center gap-1.5"><CalendarDays size={13}/>{formatIranDate(fixture.kickoffAt, language === "fa" ? "fa-IR" : "en-GB")} · {formatIranTime(fixture.kickoffAt, language === "fa" ? "fa-IR" : "en-GB")}</span><span className={fixture.status === "LIVE" ? "text-red-300" : finished ? "text-brand" : ""}>{fixture.status}</span></div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><Team fixture={fixture} home language={language}/><div><b className="block text-xl font-black">{fixture.homeGoals == null ? "—" : `${fixture.homeGoals} - ${fixture.awayGoals}`}</b><span className="mt-1 inline-flex items-center gap-1 text-[10px] text-brand opacity-80 transition group-hover:opacity-100"><BarChart3 size={12}/>{t("تحلیل مسابقه", "Match analysis")}</span></div><Team fixture={fixture} language={language}/></div></button>})}</section>{selected && <MatchAnalytics matchId={selected} clubId={clubId} onClose={() => setSelected(null)}/>}</> }
function Team({ fixture, home, language }: { fixture: Fixture; home?: boolean; language: "fa" | "en" }) { const team = home ? fixture.homeTeam : fixture.awayTeam; return <div className="min-w-0"><img src={team.logoUrl ?? "/icon.png"} alt="" className="mx-auto h-10 w-10 object-contain"/><span className="mt-2 block truncate text-xs font-bold">{teamName(language, team.id, team.name)}</span></div>; }

