"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import gsap from "gsap";
import "./DepthCarousel.css";
export type DepthCarouselItem = { image: string; alt?: string; title?: string };
type Props = { items: DepthCarouselItem[]; cardWidth?: number; cardHeight?: number; radius?: number; depth?: number; spread?: number; tilt?: number; perspective?: number; visibleCards?: number; duration?: number; showControls?: boolean; showIndicators?: boolean; onChange?: (index: number) => void };
const wrap = (value: number, count: number) => ((value % count) + count) % count;
export default function DepthCarousel({ items, cardWidth = 300, cardHeight = 380, radius = 18, depth = 220, spread = 90, tilt = 22, perspective = 1400, visibleCards = 4, duration = 700, showControls = true, showIndicators = true, onChange }: Props) {
  const data = useMemo(() => items ?? [], [items]); const cards = useRef<(HTMLButtonElement | null)[]>([]); const position = useRef(0); const tween = useRef<gsap.core.Tween | null>(null); const [active, setActive] = useState(0);
  const layout = useCallback((pos: number) => { data.forEach((_, i) => { const el = cards.current[i]; if (!el) return; let distance = i - pos; if (data.length > 1) { distance = ((distance % data.length) + data.length) % data.length; if (distance > data.length / 2) distance -= data.length; } const behind = Math.max(0, distance); const visible = Math.abs(distance) <= visibleCards + .5; el.style.transform = `translate(-50%,-50%) translateX(${spread * distance}px) translateZ(${-depth * distance}px) rotateY(${tilt * Math.max(-1, Math.min(1, distance))}deg)`; el.style.opacity = visible ? String(Math.max(0, 1 - Math.max(0, -distance))) : "0"; el.style.filter = `brightness(${Math.max(.18, 1 - behind * .2)}) blur(${Math.min(6, behind * 1.5)}px)`; el.style.zIndex = String(2000 - Math.round(distance * 20)); el.style.pointerEvents = visible ? "auto" : "none"; }); }, [data, depth, spread, tilt, visibleCards]);
  const go = useCallback((raw: number) => { if (!data.length) return; const next = wrap(raw, data.length); let delta = next - wrap(position.current, data.length); if (data.length > 1) { if (delta > data.length / 2) delta -= data.length; if (delta < -data.length / 2) delta += data.length; } const proxy = { p: position.current }; tween.current?.kill(); tween.current = gsap.to(proxy, { p: position.current + delta, duration: duration / 1000, ease: "power3.out", onUpdate: () => { position.current = proxy.p; layout(proxy.p); }, onComplete: () => { position.current = next; layout(next); } }); setActive(next); onChange?.(next); }, [data, duration, layout, onChange]);
  useEffect(() => { layout(0); return () => { tween.current?.kill(); }; }, [layout]);
  if (!data.length) return null;
  return <div className="depth-carousel" style={{ perspective: `${perspective}px` }} role="group" aria-roledescription="carousel" aria-label="Awards"><div className="depth-carousel__stage">{data.map((item, i) => <button key={`${item.image}-${i}`} ref={el => { cards.current[i] = el; }} type="button" className="depth-carousel__card" style={{ width: cardWidth, height: cardHeight, borderRadius: radius }} onClick={() => go(i)} aria-label={item.title ?? item.alt ?? `Slide ${i + 1}`}><img src={item.image} alt={item.alt ?? ""} draggable={false}/>{item.title && <span className="depth-carousel__title">{item.title}</span>}</button>)}</div>{showControls && data.length > 1 && <><button type="button" className="depth-carousel__arrow depth-carousel__arrow--prev" onClick={() => go(active - 1)} aria-label="Previous award">‹</button><button type="button" className="depth-carousel__arrow depth-carousel__arrow--next" onClick={() => go(active + 1)} aria-label="Next award">›</button></>}{showIndicators && data.length > 1 && <div className="depth-carousel__dots">{data.map((item, i) => <button key={i} type="button" className={`depth-carousel__dot ${i === active ? "is-active" : ""}`} onClick={() => go(i)} aria-label={`Show ${item.title ?? `award ${i + 1}`}`} />)}</div>}</div>;
}
