"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, ArrowUpDown, Award, ChevronLeft, ChevronRight, ExternalLink, Shield, Trophy } from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";
import { UserAvatar } from "@/components/UserAvatar";
import { formatNumber } from "@/lib/text";

type Sort = "rank" | "username" | "predictions" | "exact" | "correct" | "misses" | "points" | "average" | "awards";
type Row = { userId: string; username: string; avatarUrl: string | null; clubId: string | null; clubName: string | null; predictions: number; exact: number; correct: number; misses: number; points: number; average: number; awards: number; rank: number; placeChange: number; previousRank: number | null };
type Props = { clubId?: string; clubName?: string; seasonStartYear?: number; weekly?: boolean; weekOffset?: number };

const labels = { rank: ["رتبه", "Rank"], username: ["بازیکن", "Player"], predictions: ["پیش‌بینی", "Picks"], exact: ["دقیق", "Exact"], correct: ["نتیجه صحیح", "Correct"], misses: ["از دست‌رفته", "Misses"], points: ["امتیاز", "Score"], average: ["میانگین/بازی", "Avg/match"], awards: ["افتخار", "Awards"] } as const;

export function DetailedLeaderboard({ clubId, clubName, seasonStartYear, weekly = false, weekOffset = 0 }: Props) {
  const { language, t } = useLanguage(); const [rows, setRows] = useState<Row[]>([]); const [viewerRow, setViewerRow] = useState<Row | null>(null); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [total, setTotal] = useState(0); const [sort, setSort] = useState<Sort>("rank"); const [direction, setDirection] = useState<"asc" | "desc">("desc"); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [scrollTop, setScrollTop] = useState(0);
  const pageSize = 25;
  const query = useMemo(() => { const q = new URLSearchParams({ page: String(page), pageSize: String(pageSize), sort, direction }); if (clubId) q.set("clubId", clubId); if (weekly) { q.set("weekly", "true"); if (weekOffset) q.set("week", "previous"); } else if (seasonStartYear) q.set("seasonStartYear", String(seasonStartYear)); return q.toString(); }, [clubId, page, sort, direction, weekly, weekOffset, seasonStartYear]);
  useEffect(() => { setLoading(true); setError(false); setScrollTop(0); fetch(`/api/leaderboards/detailed?${query}`).then(response => response.ok ? response.json() : Promise.reject()).then(data => { setRows(data.rows ?? []); setViewerRow(data.viewerRow ?? null); setPages(data.pages ?? 1); setTotal(data.total ?? 0); }).catch(() => { setRows([]); setViewerRow(null); setError(true); }).finally(() => setLoading(false)); }, [query]);
  function changeSort(next: Sort) { if (next === sort) setDirection(value => value === "asc" ? "desc" : "asc"); else { setSort(next); setDirection(next === "username" ? "asc" : "desc"); } setPage(1); }
  const n = (value: number) => formatNumber(value, language); const title = clubId ? (clubName || t("جدول گروه", "Group standings")) : weekly ? t("جدول هفتگی جهانی", "Global weekly standings") : t("جدول کامل جهانی", "Complete global standings");
  const visibleStart = Math.max(0, Math.floor(scrollTop / 76) - 4); const visibleRows = rows.slice(visibleStart, visibleStart + 33);
  return <section className="mt-8 overflow-hidden rounded-[2.25rem] border border-brand/20 bg-[radial-gradient(circle_at_50%_-20%,rgba(32,184,121,.28),transparent_42%),linear-gradient(155deg,#12261a,#080d0a)] shadow-[0_30px_100px_rgba(0,0,0,.28)]">
    <div className="border-b border-white/10 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.22em] text-brand">{clubId ? "GROUP COMPETITION" : "LOWBLOCK COMPETITION"}</p><h2 className="mt-2 text-2xl font-black text-white sm:text-3xl">{title}</h2><p className="mt-2 text-xs leading-5 text-white/50">{t("امتیازها، دقت، رتبه و افتخارات در یک جدول شفاف", "Points, accuracy, rank movement, and awards in one transparent table")}</p></div><div className="flex items-center gap-2 rounded-2xl border border-brand/25 bg-brand/10 px-3 py-2 text-xs font-black text-brand"><Trophy size={16}/>{n(total)} {t("بازیکن", "players")}</div></div><div className="mt-5 grid grid-cols-2 gap-2 text-[10px] font-bold text-white/55 sm:grid-cols-4"><Metric label={t("امتیاز کل", "Total score")} value={rows.length ? n(rows.reduce((sum, row) => sum + row.points, 0)) : "—"}/><Metric label={t("پیش‌بینی‌های دقیق", "Exact picks")} value={rows.length ? n(rows.reduce((sum, row) => sum + row.exact, 0)) : "—"}/><Metric label={t("میانگین امتیاز", "Average score")} value={rows.length ? (rows.reduce((sum, row) => sum + row.average, 0) / rows.length).toFixed(2) : "—"}/><Metric label={t("افتخارات", "Awards")} value={rows.length ? n(rows.reduce((sum, row) => sum + row.awards, 0)) : "—"}/></div></div>
    <div className="border-b border-white/10 bg-black/10 px-5 py-3 text-[10px] text-white/45 sm:px-7"><span className="text-brand">{t("راهنما:", "Tip:")}</span> {t("برای مرتب‌سازی روی عنوان هر ستون کلیک کنید.", "Click any column heading to sort ascending or descending.")}</div>
    {loading ? <Skeleton/> : error ? <div className="p-12 text-center text-sm text-red-200">{t("بارگذاری جدول ناموفق بود.", "Could not load the standings.")}</div> : !rows.length ? <div className="p-12 text-center text-sm text-white/50">{t("هنوز امتیازی ثبت نشده است.", "No scored predictions yet.")}</div> : <>
      <div className="h-[620px] overflow-auto" onScroll={event => setScrollTop(event.currentTarget.scrollTop)}><div className="min-w-[1060px]"><div className="sticky top-0 z-20 bg-[#101512]"><Header sort={sort} direction={direction} onSort={changeSort} language={language}/></div><div style={{ height: rows.length * 76, position: "relative" }}><div className="absolute inset-x-0" style={{ top: visibleStart * 76 }}>{visibleRows.map(row => <DesktopRow key={row.userId} row={row} number={n} viewerId={viewerRow?.userId} />)}</div></div></div></div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 px-5 py-4 sm:px-7"><span className="text-xs text-white/45">{t("صفحه", "Page")} {n(page)} / {n(pages)}</span><div className="flex items-center gap-2"><button type="button" disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-white transition hover:border-brand/50 disabled:opacity-30" aria-label={t("صفحه قبل", "Previous page")}><ChevronLeft size={17}/></button><button type="button" disabled={page >= pages} onClick={() => setPage(value => value + 1)} className="grid h-10 w-10 place-items-center rounded-xl border border-brand/30 bg-brand/15 text-brand transition hover:bg-brand/25 disabled:opacity-30" aria-label={t("صفحه بعد", "Next page")}><ChevronRight size={17}/></button></div></div>
    </>}
  </section>;
}

function Header({ sort, direction, onSort, language }: { sort: Sort; direction: "asc" | "desc"; onSort: (sort: Sort) => void; language: "fa" | "en" }) { return <div className="grid grid-cols-[70px_minmax(190px,1.8fr)_90px_80px_100px_90px_100px_105px_80px] items-center gap-2 border-b border-white/10 px-5 py-3 text-[10px] font-black text-white/45 sm:px-7">{(Object.keys(labels) as Sort[]).map(field => <button key={field} type="button" onClick={() => onSort(field)} className={`flex items-center gap-1 text-start transition hover:text-brand ${sort === field ? "text-brand" : ""}`}>{labels[field][language === "fa" ? 0 : 1]}{sort === field ? direction === "asc" ? <ArrowUp size={12}/> : <ArrowDown size={12}/> : <ArrowUpDown size={11}/>}</button>)}</div>; }
function DesktopRow({ row, number, viewerId }: { row: Row; number: (value: number) => string; viewerId?: string }) { const viewer = row.userId === viewerId; const avatarClass = `h-10 w-10 border text-[10px] ${viewer ? "border-brand ring-2 ring-brand/30" : "border-white/10"}`; return <div className={`relative grid h-[76px] grid-cols-[70px_minmax(190px,1.8fr)_90px_80px_100px_90px_100px_105px_80px] items-center gap-2 border-b px-5 text-sm transition sm:px-7 ${viewer ? "border-brand/25 bg-[linear-gradient(90deg,rgba(32,184,121,.18),rgba(232,198,106,.07))]" : "border-white/[.06] hover:bg-brand/[.06]"}`}><span className="font-black text-white/65">#{number(row.rank)} {row.placeChange > 0 && <small className="text-emerald-300">↑{number(row.placeChange)}</small>}{row.placeChange < 0 && <small className="text-red-300">↓{number(Math.abs(row.placeChange))}</small>}</span><span className="sticky start-[10px] z-20 grid h-20 w-20 shrink-0 place-items-center justify-self-start rounded-full border border-white/10 bg-[#101512]/75 shadow-[0_0_0_4px_#101512,0_8px_24px_rgba(0,0,0,.25)] backdrop-blur-md [grid-column:2] [grid-row:1]"><UserAvatar name={row.username} avatarUrl={row.avatarUrl} className={avatarClass} /></span><span className="min-w-0 ps-24 [grid-column:2] [grid-row:1]"><Link href={`/u/${encodeURIComponent(row.username)}`} className="block truncate font-black text-white hover:text-brand">{row.username}</Link>{row.clubId && <Link href={`/club/${row.clubId}`} className="mt-0.5 block truncate text-[10px] text-brand/75 hover:text-brand">{row.clubName || "Group"}</Link>}</span><span className="col-start-3 text-white/70">{number(row.predictions)}</span><span className="col-start-4 font-black text-[#e8c66a]">{number(row.exact)}</span><span className="col-start-5 text-emerald-300">{number(row.correct)}</span><span className="col-start-6 text-red-200/70">{number(row.misses)}</span><span className="col-start-7 font-black text-brand">{number(row.points)}</span><span className="col-start-8 text-white/70">{row.average.toFixed(2)}</span><span className="col-start-9 inline-flex items-center gap-1 text-[#e8c66a]"><Award size={14}/>{number(row.awards)}</span></div>; }
function MobileRow({ row, number, clubId, t }: { row: Row; number: (value: number) => string; clubId?: string; t: (fa: string, en: string) => string }) { return <article className="rounded-2xl border border-white/10 bg-white/[.045] p-4 shadow-[0_12px_30px_rgba(0,0,0,.12)]"><div className="flex items-center gap-3"><span className="text-sm font-black text-white/50">#{number(row.rank)}</span><UserAvatar name={row.username} avatarUrl={row.avatarUrl} className="h-11 w-11 border border-brand/20 text-xs"/><Link href={`/u/${encodeURIComponent(row.username)}`} className="min-w-0 flex-1 truncate font-black text-white">{row.username}</Link><span className="text-end">{row.placeChange > 0 ? <small className="text-emerald-300">↑{number(row.placeChange)}</small> : row.placeChange < 0 ? <small className="text-red-300">↓{number(Math.abs(row.placeChange))}</small> : <small className="text-white/35">—</small>}<b className="mt-1 block text-lg text-brand">{number(row.points)}</b></span></div><div className="mt-4 grid grid-cols-4 gap-2 border-t border-white/[.08] pt-3 text-center"><Stat label={t("پیش‌بینی", "Picks")} value={number(row.predictions)}/><Stat label={t("دقیق", "Exact")} value={number(row.exact)}/><Stat label={t("صحیح", "Correct")} value={number(row.correct)}/><Stat label={t("میانگین", "Avg")} value={row.average.toFixed(2)}/></div><div className="mt-3 flex items-center justify-between text-[10px] text-white/45"><span>{t("از دست‌رفته", "Misses")}: {number(row.misses)}</span><span>{t("افتخارات", "Awards")}: {number(row.awards)}</span>{row.clubId && <Link href={`/club/${row.clubId}`} className="inline-flex items-center gap-1 text-brand">{row.clubName || t("گروه", "Group")}<ExternalLink size={11}/></Link>}</div></article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[.08] bg-black/15 p-3"><span className="block text-[10px] text-white/45">{label}</span><b className="mt-1 block text-lg text-brand">{value}</b></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <span><b className="block text-xs text-white">{value}</b><small className="mt-1 block text-[9px] text-white/40">{label}</small></span>; }
function Skeleton() { return <div className="space-y-2 p-5">{Array.from({ length: 8 }, (_, index) => <div key={index} className="h-16 animate-pulse rounded-xl bg-white/[.06]"/>)}</div>; }
