"use client";
import { useState } from "react";
import { useLanguage } from "@/components/LanguageProvider";
import { PredictionDrawer } from "@/components/PredictionCard";
import { writeGuestPrediction } from "@/lib/predictions/guestStorage";

type Match = { providerMatchId: string; homeTeam: { name: string; logoUrl: string | null }; awayTeam: { name: string; logoUrl: string | null } };
type Prediction = { homeGoals: number; awayGoals: number };
export function GuestPredictionCard({ match, initial, onClose, onSaved }: { match: Match; initial?: Prediction; onClose: () => void; onSaved: (localOnly: boolean, prediction: Prediction) => void }) { const { language, t } = useLanguage(); const [home, setHome] = useState(String(initial?.homeGoals ?? 0)); const [away, setAway] = useState(String(initial?.awayGoals ?? 0)); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [insightsOpen, setInsightsOpen] = useState(false); async function submit() { setBusy(true); setError(""); try { const payload = { matchId: match.providerMatchId, homeGoals: Number(home), awayGoals: Number(away) }; const response = await fetch("/api/predictions/guest", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(t("ثبت پیش‌بینی انجام نشد.", "Prediction could not be saved.")); const prediction = { homeGoals: payload.homeGoals, awayGoals: payload.awayGoals }; onSaved(!writeGuestPrediction({ receipt: data.receipt, ...payload, createdAt: Date.now() }), prediction); } catch (reason) { setError(reason instanceof Error ? reason.message : t("خطایی رخ داد.", "Something went wrong.")); } finally { setBusy(false); } } return <PredictionDrawer home={{ name: match.homeTeam.name, logo: match.homeTeam.logoUrl }} away={{ name: match.awayTeam.name, logo: match.awayTeam.logoUrl }} homeValue={home} awayValue={away} setHome={setHome} setAway={setAway} onClose={onClose} onSubmit={submit} matchId={match.providerMatchId} insightsOpen={insightsOpen} onToggleInsights={() => setInsightsOpen((value) => !value)} busy={busy} saved={false} error={error} language={language}/>; }
