"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { motion } from "motion/react";
import { ArrowUpRight, Crown, LoaderCircle, Medal, Sparkles, Trophy } from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";
import { formatNumber } from "@/lib/text";

type Row = { userId: string; username: string; avatarUrl: string | null; points: number; exact: number; predictions: number; cursor?: { points: number; exact: number; predictions: number; userId: string } };

export function InfiniteLeaderboard({ initialRows, seasonStartYear, leagueCode, lifetime, weekly = false, me }: { initialRows: Row[]; seasonStartYear: number; leagueCode?: string; lifetime?: boolean; weekly?: boolean; me: string | null }) {
  const { language, t } = useLanguage();
  const [rows, setRows] = useState(initialRows);
  const [cursor, setCursor] = useState(initialRows.at(-1)?.cursor ?? null);
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(initialRows.length < 100);
  const sentinel = useRef<HTMLDivElement>(null);
  const params = useMemo(() => { const query = new URLSearchParams({ limit: "40" }); if (weekly) query.set("weekly", "true"); else if (!lifetime) query.set("seasonStartYear", String(seasonStartYear)); if (leagueCode) query.set("leagueCode", leagueCode); return query; }, [seasonStartYear, leagueCode, lifetime, weekly]);
  useEffect(() => { const node = sentinel.current; if (!node) return; const observer = new IntersectionObserver(entries => { if (entries[0]?.isIntersecting && cursor && !loading && !done) loadMore(); }, { rootMargin: "500px" }); observer.observe(node); return () => observer.disconnect(); }, [cursor, loading, done]);
  async function loadMore() { setLoading(true); try { const query = new URLSearchParams(params); query.set("cursor", btoa(JSON.stringify(cursor))); const response = await fetch(`/api/leaderboards?${query}`); if (!response.ok) throw new Error("leaderboard request failed"); const data = await response.json(); const incoming: Row[] = data.rows ?? []; setRows(current => { const ids = new Set(current.map(row => row.userId)); return [...current, ...incoming.filter(row => !ids.has(row.userId))]; }); setCursor(data.nextCursor ? JSON.parse(atob(data.nextCursor)) : null); setDone(!data.nextCursor || incoming.length === 0); } finally { setLoading(false); } }
  const n = (value: number) => formatNumber(value, language);
  const podium = rows.slice(0, 3);
  return <section className="mt-8"><div className="relative overflow-hidden rounded-[2.25rem] border border-brand/20 bg-[radial-gradient(circle_at_50%_-20%,rgba(32,184,121,.34),transparent_48%),linear-gradient(160deg,#142b20,#080d0a)] px-3 pb-5 pt-5 shadow-[0_28px_95px_rgba(0,0,0,.3)] sm:px-6"><div className="pointer-events-none absolute left-1/2 top-0 h-52 w-80 -translate-x-1/2 rounded-full bg-brand/10 blur-3xl"/><div className="relative mb-5 flex items-center justify-between px-2"><div><p className="text-[10px] font-black tracking-[.22em] text-brand">{t("سه رتبه اول", "TOP THREE")}</p><h2 className="mt-1 text-xl font-black text-white sm:text-2xl">{t("قهرمانان جدول", "LEADERBOARD SUMMIT")}</h2></div><div className="grid h-11 w-11 place-items-center rounded-2xl border border-[#e8c66a]/30 bg-[#e8c66a]/10 text-[#e8c66a]"><Trophy size={21}/></div></div><div className="relative grid grid-cols-2 items-end gap-3 md:grid-cols-3 md:gap-5"><div className="order-2 md:order-1">{podium[1] && <PodiumCard row={podium[1]} rank={2} language={language} t={t}/>}</div><div className="order-1 col-span-2 md:order-2 md:col-span-1">{podium[0] && <PodiumCard row={podium[0]} rank={1} language={language} t={t}/>}</div><div className="order-3">{podium[2] && <PodiumCard row={podium[2]} rank={3} language={language} t={t}/>}</div></div></div><div className="mt-5 overflow-hidden rounded-3xl border border-white/10 bg-[#101512]">{rows.map((row, index) => <Link key={row.userId} href={`/u/${encodeURIComponent(row.username)}`} className={`flex items-center gap-3 border-b border-white/[.06] px-4 py-4 transition hover:bg-white/[.03] ${row.userId === me ? "bg-brand/10" : ""}`}><span className="w-7 text-center text-sm font-black text-[var(--muted)]">{index + 1}</span><Avatar row={row}/><span className="min-w-0 flex-1"><b className="block truncate">{row.username}</b><small className="text-[10px] text-[var(--muted)]">{n(row.exact)} {t("دقیق", "exact")} · {n(row.predictions)} {t("پیش‌بینی", "picks")}</small></span><span className="flex items-center gap-2 text-sm font-black text-brand">{n(row.points)}<ArrowUpRight size={15}/></span></Link>)}<div ref={sentinel} className="flex min-h-16 items-center justify-center p-4 text-xs text-[var(--muted)]">{loading ? <LoaderCircle size={18} className="animate-spin text-brand"/> : done ? t("پایان جدول", "End of leaderboard") : <Medal size={18} className="text-brand"/>}</div></div></section>;
}

function PodiumCard({ row, rank, language, t }: { row: Row; rank: number; language: "fa" | "en"; t: (fa: string, en: string) => string }) { const first = rank === 1; const metal = first ? "#e8c66a" : rank === 2 ? "#d8e5e1" : "#c98b60"; return <Link href={`/u/${encodeURIComponent(row.username)}`} className={`group relative block overflow-hidden rounded-[1.6rem] border p-4 text-center transition duration-500 hover:-translate-y-2 ${first ? "border-[#e8c66a]/65 bg-[linear-gradient(160deg,rgba(232,198,106,.24),rgba(232,198,106,.04))] shadow-[0_18px_60px_rgba(232,198,106,.16)] md:-translate-y-4" : "border-white/10 bg-white/[.045]"}`}><span className="absolute inset-x-0 top-0 h-1" style={{ background: metal }}/><span className="pointer-events-none absolute -right-10 -top-10 h-28 w-28 rounded-full blur-2xl" style={{ background: `${metal}22` }}/><div className="relative mx-auto mb-4 grid w-fit place-items-center"><span className="absolute -inset-3 rounded-full border border-dashed opacity-50 transition duration-700 group-hover:rotate-180" style={{ borderColor: metal }}/><Avatar row={row} large/><span className="absolute -bottom-2 grid h-7 w-7 place-items-center rounded-full border-2 border-[#101812] text-[10px] font-black text-[#101812]" style={{ background: metal }}>{rank}</span></div><p className="truncate text-sm font-black text-white">{row.username}</p><p className="mt-1 text-[10px] text-white/50">{n(row.predictions, language)} {t("پیش‌بینی", "picks")} · {n(row.exact, language)} {t("دقیق", "exact")}</p><div className="mt-4 flex items-center justify-center gap-1.5 text-xl font-black text-brand"><Sparkles size={15}/>{n(row.points, language)}<span className="text-[9px] font-bold text-white/40">PTS</span></div></Link>; }
function n(value: number, language: "fa" | "en") { return formatNumber(value, language); }
function Avatar({ row, large = false }: { row: Row; large?: boolean }) { return <span className={`grid shrink-0 place-items-center overflow-hidden rounded-full border-2 bg-brand/15 font-black ${large ? "h-16 w-16 border-white/30 text-lg" : "h-10 w-10 border-white/10 text-[10px]"}`}>{row.avatarUrl ? <img src={row.avatarUrl} alt={row.username} className="h-full w-full object-cover"/> : row.username.slice(0, 2).toUpperCase()}</span>; }
