"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { BarChart3, ChevronDown, History, RefreshCw, Sparkles, X } from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";
import { formatNumber } from "@/lib/text";
import { TeamCrest } from "@/components/TeamCrest";

type Result = { fixtureId: string; date: string; opponent: { id: number; name: string; logoUrl: string | null }; home: boolean; teamGoals: number; opponentGoals: number; outcome: "W" | "D" | "L"; league: string };
type TableRow = { rank: number; team: { id: number; name: string; logoUrl: string | null }; points: number; goalDiff: number; played: number };
export type MatchInsightsData = { home: { id: number; name: string; logoUrl: string | null; form: Result[] }; away: { id: number; name: string; logoUrl: string | null; form: Result[] }; h2h: Array<{ fixtureId: string; date: string; homeTeam: { id: number; name: string; logoUrl: string | null }; awayTeam: { id: number; name: string; logoUrl: string | null }; homeGoals: number; awayGoals: number; league: string }>; standings?: { leagueCode: string; season: number; rows: TableRow[] } | null };

export function MatchInsightsPanel({ matchId }: { matchId: string }) {
  const { language, t } = useLanguage();
  const [data, setData] = useState<MatchInsightsData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { let mounted = true; fetch(`/api/matches/${encodeURIComponent(matchId)}/insights`).then((response) => response.ok ? response.json() : Promise.reject()).then((value) => { if (mounted) setData(value); }).catch(() => { if (mounted) setError(true); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [matchId]);
  const n = (value: number) => formatNumber(value, language);
  if (loading) return <InsightsSkeleton />;
  if (error || !data) return <div className="rounded-2xl border border-dashed border-white/10 p-7 text-center"><RefreshCw className="mx-auto mb-2 text-brand" size={21} /><p className="text-xs text-[var(--muted)]">{t("اطلاعات فرم در همگام‌سازی روزانه آماده می‌شود.", "Form data is prepared during the daily sync.")}</p></div>;
  return <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} className="space-y-4 overflow-hidden"><div className="grid gap-3 sm:grid-cols-2"><FormCard team={data.home} results={data.home.form} language={language} n={n} t={t} /><FormCard team={data.away} results={data.away.form} language={language} n={n} t={t} /></div><H2HCard data={data.h2h} language={language} n={n} t={t} />{data.standings && <StandingsCard data={data.standings} homeId={data.home.id} awayId={data.away.id} language={language} n={n} t={t} />}</motion.div>;
}

export function MatchInsights({ matchId, onClose }: { matchId: string; onClose: () => void }) { const { t } = useLanguage(); return <AnimatePresence><div className="fixed inset-0 z-[95] flex items-end justify-center"><motion.button type="button" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} className="absolute inset-0 bg-black/75 backdrop-blur-md" aria-label={t("بستن", "Close")} /><motion.section initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "100%" }} className="relative max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-[2.25rem] border border-b-0 border-white/10 bg-[#0b100d] px-5 pb-10 pt-14 shadow-2xl"><button type="button" onClick={onClose} className="absolute left-5 top-5 grid h-10 w-10 place-items-center rounded-2xl border border-white/10 bg-white/[.06]" aria-label={t("بستن", "Close")}><X size={18} /></button><div className="mb-5 text-center"><span className="inline-flex items-center gap-2 text-[10px] font-black tracking-[.16em] text-brand"><Sparkles size={13} />{t("فرم و رودررو", "FORM & H2H")}</span><h2 className="mt-2 text-2xl font-black">{t("آخرین نتایج دو تیم", "Recent form and head-to-head")}</h2></div><MatchInsightsPanel matchId={matchId} /></motion.section></div></AnimatePresence>; }

function FormCard({ team, results, language, n, t }: { team: { name: string; logoUrl: string | null }; results: Result[]; language: "fa" | "en"; n: (value: number) => string; t: (fa: string, en: string) => string }) { const summary = useMemo(() => results.reduce((acc, item) => { acc[item.outcome]++; return acc; }, { W: 0, D: 0, L: 0 }), [results]); return <section className="overflow-hidden rounded-[1.35rem] border border-white/[.08] bg-black/20"><div className="flex items-center gap-3 border-b border-white/[.07] bg-white/[.03] p-3.5"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/[.05] p-1.5"><TeamCrest name={team.name} logo={team.logoUrl} /></span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-black">{team.name}</h3><p className="mt-1 text-[9px] text-[var(--muted)]">{t("پنج بازی اخیر", "LAST FIVE")}</p></div><div className="flex gap-1"><Badge type="W" count={summary.W} /><Badge type="D" count={summary.D} /><Badge type="L" count={summary.L} /></div></div><div className="p-3">{results.length ? results.map((item) => <div key={item.fixtureId} className="flex items-center gap-2 border-b border-white/[.05] py-2.5 last:border-0"><span className={`grid h-6 w-6 place-items-center rounded-md text-[9px] font-black ${item.outcome === "W" ? "bg-brand/20 text-brand" : item.outcome === "D" ? "bg-[#eacb70]/15 text-[#eacb70]" : "bg-red-400/15 text-red-300"}`}>{item.outcome}</span><span className="min-w-0 flex-1 truncate text-[11px] text-white/70">{item.opponent.name}</span><b className="text-[11px]">{n(item.teamGoals)} - {n(item.opponentGoals)}</b><time className="w-14 text-end text-[9px] text-[var(--muted)]">{new Date(item.date).toLocaleDateString(language === "fa" ? "fa-IR" : "en-GB", { month: "short", day: "numeric" })}</time></div>) : <p className="p-4 text-center text-xs text-[var(--muted)]">{t("نتیجه‌ای ثبت نشده است.", "No recent results available.")}</p>}</div></section>; }
function Badge({ type, count }: { type: "W" | "D" | "L"; count: number }) { return <span className="rounded-md bg-black/20 px-1.5 py-1 text-[9px] font-black text-white/50">{type}{count}</span>; }
function H2HCard({ data, language, n, t }: { data: MatchInsightsData["h2h"]; language: "fa" | "en"; n: (value: number) => string; t: (fa: string, en: string) => string }) { const summary = data.reduce((acc, item) => { if (item.homeGoals > item.awayGoals) acc.home++; else if (item.homeGoals < item.awayGoals) acc.away++; else acc.draw++; return acc; }, { home: 0, draw: 0, away: 0 }); return <section className="overflow-hidden rounded-[1.35rem] border border-brand/20 bg-[radial-gradient(circle_at_90%_0%,rgba(32,184,121,.16),transparent_45%),rgba(0,0,0,.16)]"><div className="flex items-center gap-3 border-b border-white/[.07] p-3.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand/15 text-brand"><History size={19} /></span><div><h3 className="text-sm font-black">{t("پنج رویارویی آخر", "LAST FIVE MEETINGS")}</h3><p className="mt-1 text-[9px] text-[var(--muted)]">{t("سابقه مستقیم دو تیم", "Direct history between the teams")}</p></div><span className="ms-auto text-[10px] font-black text-[var(--muted)]">{n(data.length)} {t("بازی", "matches")}</span></div><div className="grid grid-cols-3 gap-2 p-3 text-center"><div className="rounded-xl bg-brand/10 p-2"><b className="block text-lg text-brand">{n(summary.home)}</b><small className="text-[9px] text-[var(--muted)]">{t("برد میزبان", "Home wins")}</small></div><div className="rounded-xl bg-white/[.04] p-2"><b className="block text-lg">{n(summary.draw)}</b><small className="text-[9px] text-[var(--muted)]">{t("مساوی", "Draws")}</small></div><div className="rounded-xl bg-red-400/10 p-2"><b className="block text-lg text-red-300">{n(summary.away)}</b><small className="text-[9px] text-[var(--muted)]">{t("برد مهمان", "Away wins")}</small></div></div><div className="px-4 pb-3">{data.length ? data.map((item) => <div key={item.fixtureId} className="flex items-center gap-2 border-t border-white/[.05] py-2.5"><span className="min-w-0 flex-1 truncate text-[11px] font-bold">{item.homeTeam.name}</span><b className="rounded-lg border border-white/10 bg-black/20 px-2.5 py-1.5 text-[11px]">{n(item.homeGoals)} - {n(item.awayGoals)}</b><span className="min-w-0 flex-1 truncate text-end text-[11px] font-bold">{item.awayTeam.name}</span></div>) : <p className="p-4 text-center text-xs text-[var(--muted)]">{t("سابقه رودررو موجود نیست.", "No head-to-head history available.")}</p>}</div></section>; }
function StandingsCard({ data, homeId, awayId, language, n, t }: { data: { leagueCode: string; season: number; rows: TableRow[] }; homeId: number; awayId: number; language: "fa" | "en"; n: (value: number) => string; t: (fa: string, en: string) => string }) { const indexes = [data.rows.findIndex((row) => row.team.id === homeId), data.rows.findIndex((row) => row.team.id === awayId)].filter((index) => index >= 0); if (!indexes.length) return null; const low = Math.min(...indexes); const high = Math.max(...indexes); const visible = high - low > 5 ? [...data.rows.slice(Math.max(0, low - 1), low + 2), null, ...data.rows.slice(Math.max(low + 2, high - 1), Math.min(data.rows.length, high + 2))] : data.rows.slice(Math.max(0, low - 1), Math.min(data.rows.length, high + 2)); return <section className="overflow-hidden rounded-[1.35rem] border border-[#eacb70]/25 bg-[linear-gradient(145deg,rgba(234,203,112,.08),rgba(0,0,0,.15))]"><div className="flex items-center gap-3 border-b border-white/[.07] p-3.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eacb70]/15 text-[#eacb70]"><BarChart3 size={19} /></span><div><h3 className="text-sm font-black">{t("جایگاه در جدول", "LEAGUE TABLE")}</h3><p className="mt-1 text-[9px] text-[var(--muted)]">{t("جایگاه دو تیم و همسایه‌هایشان", "Both teams and the teams around them")}</p></div><span className="ms-auto text-[10px] font-black text-[var(--muted)]">{data.leagueCode}</span></div><div className="p-3">{visible.map((row, index) => row ? <div key={row.team.id} className={`flex items-center gap-2 rounded-xl px-2.5 py-2 ${row.team.id === homeId || row.team.id === awayId ? "bg-brand/15 ring-1 ring-brand/25" : ""}`}><b className="w-5 text-center text-[10px] text-[var(--muted)]">{n(row.rank)}</b><span className="grid h-7 w-7 place-items-center rounded-full bg-white/[.05] p-1"><TeamCrest name={row.team.name} logo={row.team.logoUrl} /></span><span className="min-w-0 flex-1 truncate text-[11px] font-bold">{row.team.name}</span><span className="text-[10px] text-[var(--muted)]">{n(row.played)} {t("بازی", "GP")}</span><b className="w-7 text-end text-xs text-brand">{n(row.points)}</b></div> : <div key={`ellipsis-${index}`} className="py-1 text-center text-xs tracking-[.3em] text-white/35">•••</div>)}</div></section>; }
function InsightsSkeleton() { return <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><div className="h-52 animate-pulse rounded-[1.35rem] bg-white/[.06]" /><div className="h-52 animate-pulse rounded-[1.35rem] bg-white/[.06]" /></div><div className="h-56 animate-pulse rounded-[1.35rem] bg-white/[.06]" /><div className="h-48 animate-pulse rounded-[1.35rem] bg-white/[.06]" /></div>; }
