"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { ArrowLeft, BarChart3, CalendarDays, History, RefreshCw, Sparkles, Trophy, X } from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";
import { formatNumber } from "@/lib/text";
import { TeamCrest } from "@/components/TeamCrest";

type Result = { fixtureId: string; date: string; opponent: { id: number; name: string; logoUrl: string | null }; home: boolean; teamGoals: number; opponentGoals: number; outcome: "W" | "D" | "L"; league: string };
type Data = { home: { id: number; name: string; logoUrl: string | null; form: Result[] }; away: { id: number; name: string; logoUrl: string | null; form: Result[] }; h2h: Array<{ fixtureId: string; date: string; homeTeam: { id: number; name: string; logoUrl: string | null }; awayTeam: { id: number; name: string; logoUrl: string | null }; homeGoals: number; awayGoals: number; league: string }> };

export function MatchInsights({ matchId, onClose }: { matchId: string; onClose: () => void }) {
  const { language, t } = useLanguage();
  const [data, setData] = useState<Data | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  useEffect(() => { let mounted = true; fetch(`/api/matches/${encodeURIComponent(matchId)}/insights`).then((response) => response.ok ? response.json() : Promise.reject()).then((value) => { if (mounted) setData(value); }).catch(() => { if (mounted) setError(true); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [matchId]);
  const n = (value: number) => formatNumber(value, language);
  return <AnimatePresence><div className="fixed inset-0 z-[95] flex items-end justify-center"><motion.button type="button" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} className="absolute inset-0 bg-black/75 backdrop-blur-md" aria-label={t("بستن", "Close")} /><motion.section initial={{ y: "100%", opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: "100%", opacity: 0 }} transition={{ type: "spring", stiffness: 280, damping: 28 }} className="relative max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-[2.25rem] border border-b-0 border-white/10 bg-[linear-gradient(145deg,#14231b,#080d0a)] px-5 pb-10 pt-14 shadow-[0_-30px_100px_rgba(0,0,0,.75)] sm:px-8"><div className="absolute left-1/2 top-3 -translate-x-1/2 text-white/25"><BarChart3 size={26} /></div><button type="button" onClick={onClose} className="absolute left-5 top-5 grid h-10 w-10 place-items-center rounded-2xl border border-white/10 bg-white/[.06] text-white/75 hover:border-brand/50 hover:text-brand" aria-label={t("بستن", "Close")}><X size={18} /></button><div className="text-center"><span className="inline-flex items-center gap-2 rounded-full border border-brand/25 bg-brand/10 px-3 py-1.5 text-[10px] font-black tracking-[.16em] text-brand"><Sparkles size={13} />{t("فرم و رودررو", "FORM & H2H")}</span><h2 className="mt-3 text-2xl font-black">{t("آخرین نتایج دو تیم", "Recent form and head-to-head")}</h2><p className="mt-2 text-xs leading-6 text-white/50">{t("پنج نتیجه اخیر و پنج رویارویی آخر، بر اساس داده‌های روزانه فوتبال.", "The latest five results and five meetings, refreshed with the daily football data sync.")}</p></div>{loading ? <InsightsSkeleton /> : error || !data ? <div className="mt-8 rounded-2xl border border-dashed border-white/10 p-10 text-center"><RefreshCw className="mx-auto mb-3 text-brand" size={24} /><p className="text-sm text-[var(--muted)]">{t("این اطلاعات در همگام‌سازی بعدی آماده می‌شود.", "These insights will be ready after the next daily sync.")}</p></div> : <div className="mt-7 space-y-5"><div className="grid gap-3 sm:grid-cols-2"><FormCard team={data.home} results={data.home.form} language={language} n={n} t={t} /><FormCard team={data.away} results={data.away.form} language={language} n={n} t={t} /></div><H2HCard data={data.h2h} language={language} n={n} t={t} /></div>}</motion.section></div></AnimatePresence>;
}

function FormCard({ team, results, language, n, t }: { team: { name: string; logoUrl: string | null }; results: Result[]; language: "fa" | "en"; n: (value: number) => string; t: (fa: string, en: string) => string }) { const summary = useMemo(() => results.reduce((acc, item) => { acc[item.outcome]++; return acc; }, { W: 0, D: 0, L: 0 }), [results]); return <section className="overflow-hidden rounded-[1.5rem] border border-white/[.08] bg-black/20"><div className="flex items-center gap-3 border-b border-white/[.07] bg-white/[.03] p-4"><span className="grid h-11 w-11 place-items-center rounded-full bg-white/[.05] p-1.5"><TeamCrest name={team.name} logo={team.logoUrl} /></span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-black">{team.name}</h3><p className="mt-1 text-[10px] text-[var(--muted)]">{t("پنج بازی اخیر", "LAST FIVE")}</p></div><div className="flex gap-1"><Badge type="W" count={summary.W} /><Badge type="D" count={summary.D} /><Badge type="L" count={summary.L} /></div></div><div className="p-3">{results.length ? results.map((item) => <ResultRow key={item.fixtureId} item={item} language={language} n={n} />) : <p className="p-5 text-center text-xs text-[var(--muted)]">{t("نتیجه‌ای ثبت نشده است.", "No recent results available.")}</p>}</div></section>; }
function ResultRow({ item, language, n }: { item: Result; language: "fa" | "en"; n: (value: number) => string }) { return <div className="flex items-center gap-2 border-b border-white/[.05] py-2.5 last:border-0"><span className={`grid h-7 w-7 place-items-center rounded-lg text-[10px] font-black ${item.outcome === "W" ? "bg-brand/20 text-brand" : item.outcome === "D" ? "bg-[#eacb70]/15 text-[#eacb70]" : "bg-red-400/15 text-red-300"}`}>{item.outcome}</span><span className="min-w-0 flex-1 truncate text-xs text-white/70">{item.opponent.name}</span><b className="text-xs">{n(item.teamGoals)} - {n(item.opponentGoals)}</b><time className="w-16 text-end text-[9px] text-[var(--muted)]">{new Date(item.date).toLocaleDateString(language === "fa" ? "fa-IR" : "en-GB", { month: "short", day: "numeric" })}</time></div>; }
function Badge({ type, count }: { type: "W" | "D" | "L"; count: number }) { return <span className="rounded-md bg-black/20 px-1.5 py-1 text-[9px] font-black text-white/50">{type}{count}</span>; }
function H2HCard({ data, language, n, t }: { data: Data["h2h"]; language: "fa" | "en"; n: (value: number) => string; t: (fa: string, en: string) => string }) { const summary = data.reduce((acc, item) => { if (item.homeGoals > item.awayGoals) acc.home++; else if (item.homeGoals < item.awayGoals) acc.away++; else acc.draw++; return acc; }, { home: 0, draw: 0, away: 0 }); return <section className="overflow-hidden rounded-[1.5rem] border border-brand/20 bg-[radial-gradient(circle_at_90%_0%,rgba(32,184,121,.16),transparent_45%),rgba(0,0,0,.16)]"><div className="flex items-center gap-3 border-b border-white/[.07] p-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand/15 text-brand"><History size={21} /></span><div><h3 className="text-sm font-black">{t("پنج رویارویی آخر", "LAST FIVE MEETINGS")}</h3><p className="mt-1 text-[10px] text-[var(--muted)]">{t("سابقه مستقیم دو تیم", "Direct history between the teams")}</p></div><span className="ms-auto text-[10px] font-black text-[var(--muted)]">{n(data.length)} {t("بازی", "matches")}</span></div><div className="grid grid-cols-3 gap-2 p-3 text-center"><div className="rounded-xl bg-brand/10 p-2"><b className="block text-lg text-brand">{n(summary.home)}</b><small className="text-[9px] text-[var(--muted)]">{t("برد میزبان", "Home wins")}</small></div><div className="rounded-xl bg-white/[.04] p-2"><b className="block text-lg">{n(summary.draw)}</b><small className="text-[9px] text-[var(--muted)]">{t("مساوی", "Draws")}</small></div><div className="rounded-xl bg-red-400/10 p-2"><b className="block text-lg text-red-300">{n(summary.away)}</b><small className="text-[9px] text-[var(--muted)]">{t("برد مهمان", "Away wins")}</small></div></div><div className="px-4 pb-4">{data.length ? data.map((item) => <div key={item.fixtureId} className="flex items-center gap-2 border-t border-white/[.05] py-3"><span className="min-w-0 flex-1 truncate text-xs font-bold">{item.homeTeam.name}</span><b className="rounded-lg border border-white/10 bg-black/20 px-2.5 py-1.5 text-xs">{n(item.homeGoals)} - {n(item.awayGoals)}</b><span className="min-w-0 flex-1 truncate text-end text-xs font-bold">{item.awayTeam.name}</span></div>) : <p className="p-5 text-center text-xs text-[var(--muted)]">{t("سابقه رودررو موجود نیست.", "No head-to-head history available.")}</p>}</div></section>; }
function InsightsSkeleton() { return <div className="mt-7 animate-pulse space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="h-56 rounded-[1.5rem] bg-white/[.06]" /><div className="h-56 rounded-[1.5rem] bg-white/[.06]" /></div><div className="h-64 rounded-[1.5rem] bg-white/[.06]" /></div>; }
