"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { motion } from "motion/react";
import { BarChart3, Home, LogIn, Trophy } from "lucide-react";

type User = { username: string; avatarUrl: string | null };
const routes = [{ href: "/app", fa: "خانه", en: "Home", icon: Home }, { href: "/leagues/GB1", fa: "لیگ‌ها", en: "Leagues", icon: Trophy }, { href: "/leaderboard", fa: "رتبه‌بندی", en: "Leaders", icon: BarChart3 }];
function initials(name: string) { const parts = name.trim().split(/\s+/).filter(Boolean); const chars = parts.length > 1 ? [parts[0][0], parts[1][0]] : [...(parts[0] ?? "ک")].slice(0, 2); return chars.join("‌").toUpperCase(); }

export function Nav() {
  const pathname = usePathname(); const [user, setUser] = useState<User | null>(null); const [language, setLanguage] = useState<"fa" | "en">("fa");
  const authPage = pathname === "/login" || pathname === "/signup";
  useEffect(() => { const saved = localStorage.getItem("lowblock_language"); if (saved === "en") setLanguage("en"); fetch("/api/auth/me").then((response) => response.json()).then((data) => setUser(data.user ?? null)).catch(() => setUser(null)); }, []);
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = language === "fa" ? "rtl" : "ltr"; localStorage.setItem("lowblock_language", language); }, [language]);
  const labels = useMemo(() => language === "fa" ? { space: "فضای پیش‌بینی", account: "حساب", login: "ورود به حساب", footer: "لوبلاک · پیش‌بینی مسئولانه فوتبال" } : { space: "PREDICTION SPACE", account: "Account", login: "Sign in", footer: "Lowblock · Responsible football predictions" }, [language]);
  const active = (href: string) => href === "/app" ? pathname === "/app" : href === "/leagues/GB1" ? pathname.startsWith("/leagues") : pathname.startsWith(href);
  const avatar = <span className="relative z-10 grid h-7 w-7 place-items-center overflow-hidden rounded-full border border-white/15 bg-brand/20 text-[9px] font-black text-white">{user?.avatarUrl ? <img src={user.avatarUrl} alt={user.username} className="h-full w-full object-cover"/> : user ? initials(user.username) : <LogIn size={14}/>}</span>;
  return <>
    {!authPage && <aside className="fixed inset-y-0 right-0 z-40 hidden w-72 border-l border-white/[.07] bg-[#09090c]/92 px-5 py-7 backdrop-blur-2xl md:block"><div className="mb-14 flex items-center gap-3 px-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand text-xl font-black text-white shadow-[0_0_28px_rgba(18,160,105,.35)]">ل</span><span className="text-xl font-black">لوبلاک<span className="text-brand">.</span></span></div><p className="mb-4 px-3 text-[10px] font-bold tracking-[.22em] text-[var(--muted)]">{labels.space}</p><nav className="space-y-2">{routes.map(({ href, fa, en, icon: Icon }) => <Link key={href} href={href} className={`relative flex items-center gap-3 rounded-2xl px-4 py-3.5 text-sm font-bold transition ${active(href) ? "text-white" : "text-[var(--muted)] hover:bg-white/[.04] hover:text-white"}`}>{active(href) && <motion.span layoutId="active-desktop-nav" className="absolute inset-0 rounded-2xl bg-brand/15" transition={{ type: "spring", stiffness: 380, damping: 32 }}/>} {active(href) && <motion.span layoutId="active-desktop-line" className="absolute right-0 h-7 w-1 rounded-full bg-brand"/>}<span className="relative z-10 flex items-center gap-3"><Icon size={18}/>{language === "fa" ? fa : en}</span></Link>)}</nav><Link href={user ? "/app" : "/login"} className="absolute bottom-14 left-5 right-5 flex items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.03] px-4 py-3 text-sm font-bold text-white">{avatar}<span className="truncate">{user?.username ?? labels.login}</span></Link></aside>}
    <header className={`fixed inset-x-0 top-0 z-50 flex h-[72px] items-center justify-between border-b border-white/[.07] bg-[#07070a]/78 px-5 backdrop-blur-2xl ${authPage ? "md:px-10" : "md:pr-[20rem] md:pl-8"}`}><Link href="/" className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand text-base font-black text-white">ل</span><span className="font-black">لوبلاک<span className="text-brand">.</span></span></Link><div className="flex rounded-xl border border-white/10 bg-white/[.04] p-1 text-[10px] font-black"><button onClick={() => setLanguage("fa")} className={`rounded-lg px-2.5 py-1.5 transition ${language === "fa" ? "bg-brand text-white" : "text-[var(--muted)]"}`}>FA</button><button onClick={() => setLanguage("en")} className={`rounded-lg px-2.5 py-1.5 transition ${language === "en" ? "bg-brand text-white" : "text-[var(--muted)]"}`}>EN</button></div></header>
    {!authPage && <nav className="fixed inset-x-4 bottom-4 z-50 flex items-center justify-around rounded-[26px] border border-white/10 bg-[#111116]/92 px-1.5 py-2 shadow-2xl backdrop-blur-2xl md:hidden">{routes.map(({ href, fa, en, icon: Icon }) => <Link key={href} href={href} className={`relative flex min-w-[64px] flex-col items-center gap-1 rounded-2xl px-2 py-2 text-[10px] font-bold ${active(href) ? "text-white" : "text-[var(--muted)]"}`}>{active(href) && <motion.span layoutId="active-mobile-nav" className="absolute inset-0 rounded-2xl bg-brand/20" transition={{ type: "spring", stiffness: 400, damping: 30 }}/>} {active(href) && <motion.span layoutId="active-mobile-dot" className="absolute -top-1 h-1 w-5 rounded-full bg-brand"/>}<Icon className="relative z-10" size={19}/><span className="relative z-10">{language === "fa" ? fa : en}</span></Link>)}<Link href={user ? "/app" : "/login"} className="relative flex min-w-[64px] flex-col items-center gap-1 rounded-2xl px-2 py-2 text-[10px] font-bold text-[var(--muted)]">{avatar}<span className="max-w-14 truncate">{user ? user.username : labels.account}</span></Link></nav>}
    {!authPage && <footer className="fixed bottom-0 left-0 right-72 z-20 hidden h-8 items-center justify-center border-t border-white/[.05] bg-[#07070a]/80 text-[10px] text-[var(--muted)] backdrop-blur-xl md:flex">{labels.footer}</footer>}
  </>;
}
