"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Goal, Home, LogIn, Trophy, UserRound } from "lucide-react";
import { Brand } from "@/components/Brand";
import { useLanguage } from "@/components/LanguageProvider";
type User = { username: string; avatarUrl: string | null };
const routes = [{ href: "/app", fa: "\u062e\u0627\u0646\u0647", en: "Home", icon: Home }, { href: "/leagues/GB1", fa: "\u0644\u06cc\u06af\u200c\u0647\u0627", en: "Leagues", icon: Trophy }, { href: "/predictions", fa: "\u067e\u06cc\u0634\u200c\u0628\u06cc\u0646\u06cc\u200c\u0647\u0627", en: "Predictions", icon: Goal }, { href: "/leaderboard", fa: "\u0631\u062a\u0628\u0647\u200c\u0628\u0646\u062f\u06cc", en: "Leaders", icon: BarChart3 }];
export function Nav() {
  const pathname = usePathname(); const { language, setLanguage, t } = useLanguage(); const [user, setUser] = useState<User | null>(null); const authPage = pathname === "/login" || pathname === "/signup"; const appPage = pathname !== "/" && !authPage;
  useEffect(() => { fetch("/api/auth/me").then((r) => r.json()).then((data) => setUser(data.user ?? null)).catch(() => setUser(null)); }, [pathname]);
  const active = (href: string) => href === "/app" ? pathname === href : href === "/leagues/GB1" ? pathname.startsWith("/leagues") : pathname.startsWith(href);
  const labels = useMemo(() => ({ login: t("\u0648\u0631\u0648\u062f", "Sign in"), account: t("\u062d\u0633\u0627\u0628", "Account") }), [t]);
  return <><header className="fixed inset-x-0 top-0 z-50 border-b border-white/[.07] bg-[#080b0a]/82 backdrop-blur-2xl"><div className="relative mx-auto flex h-[70px] max-w-7xl items-center justify-between px-5 md:px-8"><div className="w-20 sm:w-36"/><Brand variant="horizontal" className="absolute left-1/2 -translate-x-1/2"/>
    {!authPage && <nav className="hidden items-center gap-1 rounded-xl border border-white/[.07] bg-white/[.025] p-1 lg:flex">{routes.map(({ href, fa, en }) => <Link key={href} href={href} className={`rounded-lg px-4 py-2 text-xs font-bold transition ${active(href) ? "bg-brand text-white shadow-sm" : "text-[var(--muted)] hover:bg-white/[.06] hover:text-white"}`}>{language === "fa" ? t(fa, en) : en}</Link>)}</nav>}
    <div className="flex items-center gap-2"><div className="flex items-center rounded-full border border-white/10 bg-black/25 p-1 text-[10px] font-black shadow-inner"><button aria-label="Persian" onClick={() => setLanguage("fa")} className={`rounded-full px-3 py-1.5 transition ${language === "fa" ? "bg-white text-[#102018]" : "text-[var(--muted)]"}`}>فا</button><button aria-label="English" onClick={() => setLanguage("en")} className={`rounded-full px-3 py-1.5 transition ${language === "en" ? "bg-white text-[#102018]" : "text-[var(--muted)]"}`}>EN</button></div>{!authPage && <Link href={user ? "/profile" : "/login"} aria-label={user ? labels.account : labels.login} className="grid h-9 w-9 place-items-center overflow-hidden rounded-full border border-white/10 bg-white/[.05] text-white transition hover:border-brand/60 hover:text-brand">{user?.avatarUrl ? <img src={user.avatarUrl} alt="" className="h-full w-full object-cover" /> : user ? <span className="text-xs font-black">{user.username.slice(0, 1).toUpperCase()}</span> : <LogIn size={17}/>}</Link>}</div></div></header>
    {appPage && <nav className="fixed inset-x-3 bottom-3 z-50 flex items-center justify-around rounded-xl border border-white/10 bg-[#151b18]/95 px-1 py-1.5 shadow-2xl backdrop-blur-2xl lg:hidden">{routes.map(({ href, icon: Icon }) => <Link key={href} href={href} aria-label={href} className={`grid h-11 w-12 place-items-center rounded-lg transition ${active(href) ? "bg-brand/15 text-brand" : "text-[var(--muted)]"}`}><Icon size={22}/></Link>)}<Link href={user ? "/profile" : "/login"} aria-label={labels.account} className="grid h-11 w-12 place-items-center rounded-lg text-[var(--muted)]"><UserRound size={22}/></Link></nav>}</>;
}
