"use client";

import { useEffect, useState } from "react";
import { Bell, Check, Globe2, Trophy } from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";

type Provider = "telegram" | "bale";
export type TelegramReminderScope = "ALL_MATCHES" | "GLOBAL_LEADERBOARD";

export function TelegramReminderScopeSelector({ scope, onChange, disabled = false }: { scope: TelegramReminderScope; onChange: (scope: TelegramReminderScope) => void; disabled?: boolean }) {
  const { t } = useLanguage();
  return <div className="mt-4 border-t border-white/[.07] pt-4"><p className="text-xs font-bold text-white/70">{t("کدام بازی‌ها یادآوری شوند؟", "Which matches should be reminded?")}</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => onChange("ALL_MATCHES")} disabled={disabled} aria-pressed={scope === "ALL_MATCHES"} className={`flex items-center gap-3 rounded-xl border p-3 text-start transition ${scope === "ALL_MATCHES" ? "border-brand/50 bg-brand/10 text-white" : "border-white/[.08] text-white/55 hover:border-white/20"}`}><Globe2 size={17} className="shrink-0 text-brand"/><span className="min-w-0 flex-1"><b className="block text-xs">{t("همه بازی‌ها", "All matches")}</b><small className="mt-1 block text-[10px] text-[var(--muted)]">{t("تمام مسابقه‌های موجود", "Every available fixture")}</small></span>{scope === "ALL_MATCHES" && <Check size={15} className="shrink-0 text-brand"/>}</button><button type="button" onClick={() => onChange("GLOBAL_LEADERBOARD")} disabled={disabled} aria-pressed={scope === "GLOBAL_LEADERBOARD"} className={`flex items-center gap-3 rounded-xl border p-3 text-start transition ${scope === "GLOBAL_LEADERBOARD" ? "border-brand/50 bg-brand/10 text-white" : "border-white/[.08] text-white/55 hover:border-white/20"}`}><Trophy size={17} className="shrink-0 text-brand"/><span className="min-w-0 flex-1"><b className="block text-xs">{t("فقط جدول جهانی", "Leaderboard matches only")}</b><small className="mt-1 block text-[10px] text-[var(--muted)]">{t("بازی‌های محاسبه‌شده در جدول جهانی", "Matches included in the global leaderboard")}</small></span>{scope === "GLOBAL_LEADERBOARD" && <Check size={15} className="shrink-0 text-brand"/>}</button></div></div>;
}

export function PlatformNotificationToggle({ provider, username }: { provider: Provider; username: string | null }) {
  const { t } = useLanguage(); const [enabled, setEnabled] = useState(true); const [connected, setConnected] = useState(true); const [scope, setScope] = useState<TelegramReminderScope>("ALL_MATCHES"); const [busy, setBusy] = useState(false); const name = provider === "telegram" ? "Telegram" : "Bale";
  useEffect(() => { fetch("/api/notifications/preferences").then(r => r.ok ? r.json() : null).then(data => { if (!data) return; setConnected(data.connected?.[provider] === true); setEnabled(data.providers?.[provider] !== false); if (provider === "telegram") setScope(data.telegramReminderScope === "GLOBAL_LEADERBOARD" ? "GLOBAL_LEADERBOARD" : "ALL_MATCHES"); }).catch(() => undefined); }, [provider]);
  async function toggle() { setBusy(true); const response = await fetch("/api/notifications/preferences", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider, enabled: !enabled }) }); const data = await response.json().catch(() => null); if (response.ok) setEnabled(data?.enabled === true); setBusy(false); }
  async function changeScope(nextScope: TelegramReminderScope) { if (provider !== "telegram" || !enabled || busy || nextScope === scope) return; setBusy(true); const response = await fetch("/api/notifications/preferences", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider, reminderScope: nextScope }) }); if (response.ok) setScope(nextScope); setBusy(false); }
  return <div className="mt-5 rounded-2xl border border-white/[.08] bg-black/15 p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3"><Bell size={18} className="mt-0.5 shrink-0 text-brand"/><div className="min-w-0"><b className="text-sm text-white">{t(`یادآوری پیش‌بینی در ${name}`, `${name} prediction reminders`)}</b><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{t(`اگر پیش‌بینی ثبت نکرده باشید، ۳۰ دقیقه قبل از بازی در ${name} یادآوری می‌شوید.`, `Get a ${name} reminder 30 minutes before a match when you are missing a pick.`)}{username ? ` · @${username}` : ""}</p></div></div><button type="button" onClick={toggle} disabled={!connected || busy} aria-pressed={enabled} aria-label={t("فعال‌سازی یادآوری‌ها", "Toggle prediction reminders")} dir="ltr" className={`relative h-8 w-14 shrink-0 rounded-full border transition ${enabled ? "border-brand bg-brand" : "border-white/15 bg-white/10"}`}><span className={`absolute left-1 top-1 h-6 w-6 rounded-full bg-white shadow-md transition-transform ${enabled ? "translate-x-6" : "translate-x-0"}`}/></button></div>{provider === "telegram" && enabled && <TelegramReminderScopeSelector scope={scope} disabled={busy} onChange={changeScope}/>} {!connected && <p className="mt-3 text-xs text-brand">{t(`${name} متصل نیست.`, `${name} is not connected.`)}</p>}</div>;
}
