"use client";
import { CheckCircle2, Clock3, Target, Trophy } from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";
import { teamName } from "@/lib/football/team-names";
import { formatIranDate, formatIranTime } from "@/lib/football/time";
import { TeamCrest } from "@/components/TeamCrest";
type Row={matchId:string;kickoffAt:string;homeTeam:{id:number;name:string;logoUrl:string|null};awayTeam:{id:number;name:string;logoUrl:string|null};predictedHome:number;predictedAway:number;actualHome:number|null;actualAway:number|null;points:number;category:string};
export function PredictionHistory({rows}:{rows:Row[]}){const{language,t}=useLanguage();const total=rows.reduce((sum,row)=>sum+row.points,0);const exact=rows.filter(row=>row.category==="EXACT_SCORE").length;return <main className="min-h-screen px-4 pb-28 pt-24 md:px-8 md:pt-32"><div className="mx-auto max-w-5xl"><section className="rounded-2xl border border-white/[.09] bg-[linear-gradient(135deg,#17261f,#0c100e)] p-6 md:p-8"><p className="text-xs font-black tracking-[.18em] text-brand">{t("\u067e\u06cc\u0634\u200c\u0628\u06cc\u0646\u06cc\u200c\u0647\u0627\u06cc \u0645\u0646","MY PREDICTIONS")}</p><div className="mt-2 flex items-end justify-between gap-6"><h1 className="text-3xl font-black md:text-5xl">{t("\u0633\u0627\u0628\u0642\u0647 \u0634\u0645\u0627","Your history")}</h1><div className="flex gap-5"><Stat icon={<Trophy/>} value={total} label={t("\u0627\u0645\u062a\u06cc\u0627\u0632","Points")}/><Stat icon={<Target/>} value={exact} label={t("\u062f\u0642\u06cc\u0642","Exact")}/></div></div></section>{rows.length?<div className="mt-5 space-y-3">{rows.map(row=><HistoryCard key={row.matchId} row={row} language={language}/>)}</div>:<div className="mt-6 rounded-xl border border-dashed border-white/15 p-14 text-center"><CheckCircle2 className="mx-auto mb-3 text-brand"/><h2 className="font-black">{t("\u0647\u0646\u0648\u0632 \u067e\u06cc\u0634\u200c\u0628\u06cc\u0646\u06cc \u0646\u062f\u0627\u0631\u06cc\u062f","No predictions yet")}</h2></div>}</div></main>;}
function HistoryCard({row,language}:{row:Row;language:"fa"|"en"}){const{t}=useLanguage();const home=teamName(language,row.homeTeam.id,row.homeTeam.name),away=teamName(language,row.awayTeam.id,row.awayTeam.name);return <article className="grid gap-4 rounded-xl border border-white/[.08] bg-[#101512] p-4 md:grid-cols-[1fr_auto_auto] md:items-center"><div><div className="flex items-center justify-center gap-4 md:justify-start"><Team name={home} source={row.homeTeam.name} logo={row.homeTeam.logoUrl}/><span className="text-xs font-bold text-[var(--muted)]">VS</span><Team name={away} source={row.awayTeam.name} logo={row.awayTeam.logoUrl}/></div><p className="mt-3 flex items-center justify-center gap-1 text-[11px] text-[var(--muted)] md:justify-start"><Clock3 size={12}/>{formatIranDate(row.kickoffAt,language==="fa"?"fa-IR":"en-GB")} · {formatIranTime(row.kickoffAt,language==="fa"?"fa-IR":"en-GB")}</p></div><div className="flex items-center justify-center gap-5 rounded-lg bg-black/20 px-5 py-3 text-center"><Score label={t("\u067e\u06cc\u0634\u200c\u0628\u06cc\u0646\u06cc","Pick")} value={`${row.predictedHome} - ${row.predictedAway}`}/><span className="h-8 w-px bg-white/10"/><Score label={t("\u0646\u062a\u06cc\u062c\u0647","Result")} value={row.actualHome==null?"—":`${row.actualHome} - ${row.actualAway}`}/></div><div className="text-center"><b className="text-2xl font-black text-brand">+{row.points}</b><p className="text-[10px] text-[var(--muted)]">{category(row.category,language)}</p></div></article>;}
function Team({name,source,logo}:{name:string;source:string;logo:string|null}){return <div className="flex min-w-0 items-center gap-2"><span className="grid h-10 w-10 shrink-0 place-items-center"><TeamCrest name={source} logo={logo}/></span><b className="max-w-28 truncate text-sm">{name}</b></div>};function Score({label,value}:{label:string;value:string}){return <span><small className="block text-[9px] text-[var(--muted)]">{label}</small><b className="mt-1 block text-lg">{value}</b></span>};function Stat({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <span><span className="text-brand">{icon}</span><b className="mt-1 block text-xl">{value}</b><small className="text-[10px] text-[var(--muted)]">{label}</small></span>};function category(value:string,language:"fa"|"en"){const l:Record<string,[string,string]>={EXACT_SCORE:["\u0646\u062a\u06cc\u062c\u0647 \u062f\u0642\u06cc\u0642","Exact score"],CORRECT_GOAL_DIFFERENCE:["\u062a\u0641\u0627\u0636\u0644 \u0635\u062d\u06cc\u062d","Goal difference"],CORRECT_OUTCOME:["\u0646\u062a\u06cc\u062c\u0647 \u0635\u062d\u06cc\u062d","Correct outcome"],PARTICIPATION:["\u0627\u0645\u062a\u06cc\u0627\u0632 \u0645\u0634\u0627\u0631\u06a9\u062a","Participation"],NO_PREDICTION:["\u062f\u0631 \u0627\u0646\u062a\u0638\u0627\u0631 \u0646\u062a\u06cc\u062c\u0647","Pending"]};return l[value]?.[language==="fa"?0:1]??value;}
