"use client";
import { useState } from "react";
import { motion } from "motion/react";
import { Check, Clock3, Crown, Sparkles } from "lucide-react";
import { formatIranDate, formatIranTime } from "@/lib/football/time";
import { TeamCrest } from "./TeamCrest";

type Props = { match: { providerMatchId: string; kickoffAt: Date | string; status: string; homeTeam: { name: string; logoUrl: string | null }; awayTeam: { name: string; logoUrl: string | null } }; initial?: { homeGoals: number; awayGoals: number }; index?: number };
export function PredictionCard({ match, initial, index = 0 }: Props) {
  const [home, setHome] = useState(initial?.homeGoals?.toString() ?? ""); const [away, setAway] = useState(initial?.awayGoals?.toString() ?? ""); const [saved, setSaved] = useState(Boolean(initial)); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const theme = index % 2 === 0 ? "from-[#0f9b66] via-[#08754d] to-[#06432f]" : "from-[#183c32] via-[#102a24] to-[#091915]";
  const submit = async () => { if (home === "" || away === "") return; setBusy(true); setError(""); try { const response = await fetch("/api/predictions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ matchId: match.providerMatchId, homeGoals: Number(home), awayGoals: Number(away) }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "ذخیره پیش‌بینی انجام نشد"); setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "ذخیره پیش‌بینی انجام نشد"); } finally { setBusy(false); } };
  return <motion.article initial={{ opacity: 0, y: 22, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .5, delay: index * .065, ease: [0.22, 1, .36, 1] }} whileHover={{ y: -6, scale: 1.008 }} className={`group relative overflow-hidden rounded-[28px] border border-white/15 bg-gradient-to-br ${theme} p-[1px] shadow-[0_24px_70px_rgba(0,0,0,.38)]`}>
    <div className="pointer-events-none absolute -left-12 -top-16 h-44 w-44 rounded-full bg-white/15 blur-3xl"/><div className="pointer-events-none absolute inset-x-12 top-0 h-px bg-gradient-to-r from-transparent via-white/70 to-transparent"/>
    <div className="relative rounded-[27px] bg-gradient-to-b from-white/[.09] to-black/[.08] p-[18px] backdrop-blur-xl md:p-5">
      <div className="mb-3 flex items-center justify-between text-[10px] font-bold text-white/70"><span className="inline-flex items-center gap-1.5"><Crown size={13} className="text-[#e8c66a]"/> مسابقه رسمی</span><span className="inline-flex items-center gap-1.5"><Clock3 size={13}/>{formatIranDate(match.kickoffAt)} · {formatIranTime(match.kickoffAt)}</span></div>
      <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><Team name={match.homeTeam.name} logo={match.homeTeam.logoUrl}/><div className="text-center"><div className="mb-2 text-[9px] font-black tracking-wide text-white/65">پیش‌بینی شما</div><div className="flex items-center gap-1.5 rounded-2xl border border-white/20 bg-black/25 p-1.5 shadow-inner backdrop-blur-md"><input aria-label={`گل ${match.homeTeam.name}`} value={home} onChange={(event) => { setSaved(false); setHome(event.target.value.replace(/\D/g, "").slice(0, 2)); }} className="h-10 w-10 rounded-xl bg-white/95 text-center text-xl font-black text-[#0b211a] outline-none transition focus:ring-2 focus:ring-[#e8c66a]"/><b className="text-white/70">:</b><input aria-label={`گل ${match.awayTeam.name}`} value={away} onChange={(event) => { setSaved(false); setAway(event.target.value.replace(/\D/g, "").slice(0, 2)); }} className="h-10 w-10 rounded-xl bg-white/95 text-center text-xl font-black text-[#0b211a] outline-none transition focus:ring-2 focus:ring-[#e8c66a]"/></div><span className="mt-2 block text-[9px] text-white/60">{match.status === "FINISHED" ? "پایان‌یافته" : "پیش از شروع مسابقه"}</span></div><Team name={match.awayTeam.name} logo={match.awayTeam.logoUrl}/></div>
      <div className="mt-4 grid grid-cols-3 gap-2 text-center text-[9px]"><Mini label="برد میزبان" value="۱"/><Mini label="مساوی" value="X"/><Mini label="برد مهمان" value="۲"/></div>
      {error && <p role="alert" className="mt-3 rounded-xl border border-red-200/30 bg-red-950/25 p-2 text-center text-[10px] text-red-100">{error}</p>}
      <button disabled={busy || home === "" || away === ""} onClick={submit} className="mx-auto mt-4 flex min-w-40 items-center justify-center gap-2 rounded-full border border-white/15 bg-[#080d0b] px-5 py-2.5 text-xs font-black text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-black disabled:cursor-wait disabled:opacity-45">{saved ? <><Check size={14} className="text-brand"/> ذخیره شد</> : <><Sparkles size={14} className="text-[#e8c66a]"/> {busy ? "در حال ثبت…" : "ثبت پیش‌بینی"}</>}</button>
    </div>
  </motion.article>;
}
function Team({ name, logo }: { name: string; logo: string | null }) { return <div className="flex min-w-0 flex-col items-center gap-2 text-center"><div className="grid h-16 w-16 place-items-center rounded-full border border-white/25 bg-white/95 p-2 shadow-[0_10px_30px_rgba(0,0,0,.25)]"><TeamCrest name={name} logo={logo}/></div><span className="line-clamp-2 max-w-28 text-xs font-black text-white">{name}</span></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-black/15 px-2 py-2 text-white/65"><b className="mb-0.5 block text-xs text-white">{value}</b>{label}</div>; }
