"use client";
import { useEffect, useState } from "react";
import { motion } from "motion/react";
import { Check, ChevronDown, Clock3, Crown, Minus, Plus, Radio, Sparkles, X } from "lucide-react";
import { formatIranDate, formatIranTime } from "@/lib/football/time";
import { teamName } from "@/lib/football/team-names";
import { useLanguage } from "@/components/LanguageProvider";
import { TeamCrest } from "./TeamCrest";
type Team = { id: number; name: string; logoUrl: string | null };
type Props = { match: { providerMatchId: string; kickoffAt: Date | string; status: string; homeGoals?: number | null; awayGoals?: number | null; homeTeam: Team; awayTeam: Team }; initial?: { homeGoals: number; awayGoals: number }; index?: number };
export function PredictionCard({ match, initial, index = 0 }: Props) {
  const { language, t } = useLanguage(); const [now, setNow] = useState(Date.now()); const [home, setHome] = useState(initial?.homeGoals?.toString() ?? ""); const [away, setAway] = useState(initial?.awayGoals?.toString() ?? ""); const [saved, setSaved] = useState(Boolean(initial)); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [drawerOpen, setDrawerOpen] = useState(false);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const kickoff = new Date(match.kickoffAt).getTime(); const estimatedEnd = kickoff + 120 * 60_000; const hasResult = match.homeGoals !== null && match.homeGoals !== undefined && match.awayGoals !== null && match.awayGoals !== undefined; const finished = match.status === "FINISHED" || (now >= estimatedEnd && match.status !== "POSTPONED"); const live = !finished && (match.status === "LIVE" || (now >= kickoff && now < estimatedEnd)); const locked = live || finished; const theme = index % 2 === 0 ? "from-[#11a36c] via-[#08734c] to-[#043b29]" : "from-[#1d4f41] via-[#102d25] to-[#071a14]"; const homeName = teamName(language, match.homeTeam.id, match.homeTeam.name); const awayName = teamName(language, match.awayTeam.id, match.awayTeam.name); const statusText = live ? "LIVE" : finished ? `FT${hasResult ? ` · ${match.homeGoals} - ${match.awayGoals}` : ""}` : "UPCOMING";
  const submit = async () => { if (home === "" || away === "" || locked) return; setBusy(true); setError(""); try { const response = await fetch("/api/predictions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ matchId: match.providerMatchId, homeGoals: Number(home), awayGoals: Number(away) }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? t("ذخیره پیش‌بینی انجام نشد", "Prediction could not be saved")); setSaved(true); setDrawerOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : t("ذخیره پیش‌بینی انجام نشد", "Prediction could not be saved")); } finally { setBusy(false); } };
  const openMobileDrawer = () => { if (!locked) setDrawerOpen(true); };
  return <><motion.article initial={{ opacity: 0, y: 22, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .5, delay: index * .06, ease: [0.22, 1, .36, 1] }} whileHover={{ y: -6, scale: 1.006 }} onClick={(event) => { if (window.innerWidth < 768 && !(event.target instanceof HTMLInputElement || event.target instanceof HTMLButtonElement)) openMobileDrawer(); }} className={`match-card-notch group relative mb-5 overflow-hidden rounded-[28px] border border-white/15 bg-gradient-to-br ${theme} px-[1px] pt-[1px] shadow-[0_24px_70px_rgba(0,0,0,.38)]`}>
    <div className="pointer-events-none absolute -left-12 -top-16 h-44 w-44 rounded-full bg-white/15 blur-3xl"/><div className="pointer-events-none absolute inset-x-12 top-0 h-px bg-gradient-to-r from-transparent via-white/70 to-transparent"/>
    <div className="relative rounded-[27px] bg-gradient-to-b from-white/[.1] to-black/[.08] px-[18px] pb-14 pt-[18px] backdrop-blur-xl md:px-5 md:pt-5">
      <div className="mb-3 flex items-center justify-between text-[10px] font-bold text-white/75"><span className="inline-flex items-center gap-1.5"><Crown size={13} className="text-[#e8c66a]"/>{t("مسابقه رسمی", "Official match")}</span><span className={`${live ? "rounded-full bg-red-500 px-2.5 py-1 text-white shadow-[0_0_18px_rgba(239,68,68,.45)]" : "rounded-full bg-black/25 px-2.5 py-1"}`}>{live && <i className="mr-1 inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-white"/>}{statusText}</span></div>
      <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><TeamBlock name={homeName} sourceName={match.homeTeam.name} logo={match.homeTeam.logoUrl}/><div className="text-center"><div className="mb-2 text-[9px] font-black tracking-wide text-white/65">{t("پیش‌بینی شما", "YOUR PICK")}</div><div className="hidden items-center gap-1.5 rounded-2xl border border-white/20 bg-black/25 p-1.5 shadow-inner md:flex"><ScoreInput value={home} setValue={(value) => { setSaved(false); setHome(value); }} disabled={locked}/><b className="text-white/70">:</b><ScoreInput value={away} setValue={(value) => { setSaved(false); setAway(value); }} disabled={locked}/></div><button type="button" onClick={openMobileDrawer} className="flex min-w-32 flex-col items-center rounded-2xl border border-white/15 bg-black/20 px-3 py-2 text-[10px] font-bold text-white/80 md:hidden">{!live && !finished ? <><Clock3 size={15} className="mb-1"/><Countdown remaining={kickoff-now} language={language}/></> : <>{live ? <><Radio size={15} className="mb-1 animate-pulse text-red-300"/>LIVE</> : <><span className="text-lg font-black">{hasResult ? `${match.homeGoals} - ${match.awayGoals}` : "FT"}</span><span>{t("نتیجه نهایی", "Full time")}</span></>}</>}<ChevronDown size={13} className="mt-1 text-white/50"/></button></div><TeamBlock name={awayName} sourceName={match.awayTeam.name} logo={match.awayTeam.logoUrl}/></div>
      <div className="mt-4 flex items-center justify-center rounded-xl border border-white/10 bg-black/15 px-3 py-2 text-[10px] font-bold text-white/75">{!live && !finished ? <><Clock3 size={13} className="ml-1.5"/><Countdown remaining={kickoff-now} language={language}/></> : <span>{formatIranDate(match.kickoffAt, language === "fa" ? "fa-IR" : "en-GB")} · {formatIranTime(match.kickoffAt, language === "fa" ? "fa-IR" : "en-GB")}</span>}</div>{error && <p role="alert" className="mt-3 rounded-xl border border-red-200/30 bg-red-950/25 p-2 text-center text-[10px] text-red-100">{error}</p>}
    </div><button disabled={busy || home === "" || away === "" || locked} onClick={submit} className="absolute bottom-0 left-1/2 z-20 hidden min-w-40 -translate-x-1/2 items-center justify-center gap-2 rounded-full border border-white/15 bg-[#050706] px-5 py-2.5 text-xs font-black text-white shadow-lg transition hover:-translate-y-0.5 disabled:cursor-wait disabled:opacity-60 md:flex">{locked ? statusText : saved ? <><Check size={14} className="text-brand"/>{t("ذخیره شد", "Saved")}</> : <><Sparkles size={14} className="text-[#e8c66a]"/>{busy ? t("در حال ثبت…", "Saving…") : t("ثبت پیش‌بینی", "Save prediction")}</>}</button>
  </motion.article>{drawerOpen && <PredictionDrawer homeName={homeName} awayName={awayName} home={home} away={away} setHome={setHome} setAway={setAway} onClose={() => setDrawerOpen(false)} onSubmit={submit} busy={busy} saved={saved} error={error} locked={locked} language={language}/>}</>;
}
function TeamBlock({ name, sourceName, logo }: { name: string; sourceName: string; logo: string | null }) { return <div className="flex min-w-0 flex-col items-center gap-2 text-center"><div className="grid h-16 w-16 place-items-center"><TeamCrest name={sourceName} logo={logo}/></div><span className="line-clamp-2 max-w-28 text-xs font-black text-white">{name}</span></div>; }
function ScoreInput({ value, setValue, disabled }: { value: string; setValue: (value: string) => void; disabled: boolean }) { return <input disabled={disabled} value={value} onChange={(event) => setValue(event.target.value.replace(/\D/g, "").slice(0, 2))} className="h-10 w-10 rounded-xl bg-white/95 text-center text-xl font-black text-[#0b211a] outline-none transition focus:ring-2 focus:ring-[#e8c66a] disabled:opacity-65"/>; }
function Countdown({ remaining, language }: { remaining: number; language: "fa" | "en" }) { const seconds = Math.max(0, Math.floor(remaining/1000)); const value = `${String(Math.floor(seconds/3600)).padStart(2,"0")}:${String(Math.floor((seconds%3600)/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`; return <span>{language === "fa" ? "تا شروع " : "Starts in "}{value}</span>; }
function PredictionDrawer({ homeName, awayName, home, away, setHome, setAway, onClose, onSubmit, busy, saved, error, locked, language }: { homeName:string;awayName:string;home:string;away:string;setHome:(v:string)=>void;setAway:(v:string)=>void;onClose:()=>void;onSubmit:()=>void;busy:boolean;saved:boolean;error:string;locked:boolean;language:"fa"|"en" }) { const t = (fa:string,en:string)=>language === "fa" ? fa : en; return <div className="fixed inset-0 z-[80] md:hidden"><button aria-label={t("بستن","Close")} onClick={onClose} className="absolute inset-0 bg-black/70 backdrop-blur-sm"/><motion.div initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "100%" }} className="absolute bottom-0 inset-x-0 rounded-t-[30px] border-t border-white/10 bg-[#111116] p-5 pb-8 shadow-[0_-20px_80px_rgba(0,0,0,.55)]"><div className="mx-auto mb-5 h-1 w-10 rounded-full bg-white/20"/><div className="mb-5 flex items-center justify-between"><div><p className="text-xs text-brand">{t("ثبت پیش‌بینی","MAKE YOUR PICK")}</p><h2 className="mt-1 text-lg font-black">{homeName} <span className="text-[var(--muted)]">×</span> {awayName}</h2></div><button onClick={onClose} className="rounded-full bg-white/5 p-2 text-[var(--muted)]"><X size={18}/></button></div><div className="space-y-3"><Stepper name={homeName} value={home} setValue={setHome} disabled={locked}/><Stepper name={awayName} value={away} setValue={setAway} disabled={locked}/></div>{error&&<p role="alert" className="mt-3 text-center text-xs text-red-300">{error}</p>}<button disabled={busy||home===""||away===""||locked} onClick={onSubmit} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-brand py-3.5 text-sm font-black disabled:opacity-50">{saved?<><Check size={15}/>{t("ذخیره شد","Saved")}</>:busy?t("در حال ثبت…","Saving…"):t("ثبت پیش‌بینی","Save prediction")}</button></motion.div></div>; }
function Stepper({name,value,setValue,disabled}:{name:string;value:string;setValue:(v:string)=>void;disabled:boolean}){const number=Number(value||0);return <div className="flex items-center justify-between rounded-2xl border border-white/10 bg-black/20 p-3"><span className="max-w-[55%] truncate text-sm font-bold">{name}</span><div className="flex items-center gap-3"><button disabled={disabled||number<=0} onClick={()=>setValue(String(Math.max(0,number-1)))} className="grid h-9 w-9 place-items-center rounded-xl bg-white/10 disabled:opacity-30"><Minus size={15}/></button><span className="w-7 text-center text-2xl font-black">{value||"0"}</span><button disabled={disabled} onClick={()=>setValue(String(Math.min(20,number+1)))} className="grid h-9 w-9 place-items-center rounded-xl bg-white/10"><Plus size={15}/></button></div></div>; }
