"use client";
import { useEffect, useState } from "react";
import { motion } from "motion/react";
import { Check, Clock3, Crown, Radio, Sparkles } from "lucide-react";
import { formatIranDate, formatIranTime } from "@/lib/football/time";
import { teamName } from "@/lib/football/team-names";
import { useLanguage } from "@/components/LanguageProvider";
import { TeamCrest } from "./TeamCrest";
type Team = { id: number; name: string; logoUrl: string | null };
type Props = { match: { providerMatchId: string; kickoffAt: Date | string; status: string; homeGoals?: number | null; awayGoals?: number | null; homeTeam: Team; awayTeam: Team }; initial?: { homeGoals: number; awayGoals: number }; index?: number };
export function PredictionCard({ match, initial, index = 0 }: Props) {
  const { language, t } = useLanguage(); const [now, setNow] = useState(Date.now()); const [home, setHome] = useState(initial?.homeGoals?.toString() ?? ""); const [away, setAway] = useState(initial?.awayGoals?.toString() ?? ""); const [saved, setSaved] = useState(Boolean(initial)); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const kickoff = new Date(match.kickoffAt).getTime(); const estimatedEnd = kickoff + 120 * 60_000; const hasResult = match.homeGoals !== null && match.homeGoals !== undefined && match.awayGoals !== null && match.awayGoals !== undefined; const finished = match.status === "FINISHED" || (now >= estimatedEnd && match.status !== "POSTPONED"); const live = !finished && (match.status === "LIVE" || (now >= kickoff && now < estimatedEnd)); const locked = live || finished; const theme = index % 2 === 0 ? "from-[#11a36c] via-[#08734c] to-[#043b29]" : "from-[#1d4f41] via-[#102d25] to-[#071a14]"; const homeName = teamName(language, match.homeTeam.id, match.homeTeam.name); const awayName = teamName(language, match.awayTeam.id, match.awayTeam.name);
  const submit = async () => { if (home === "" || away === "" || locked) return; setBusy(true); setError(""); try { const response = await fetch("/api/predictions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ matchId: match.providerMatchId, homeGoals: Number(home), awayGoals: Number(away) }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? t("ذخیره پیش‌بینی انجام نشد", "Prediction could not be saved")); setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : t("ذخیره پیش‌بینی انجام نشد", "Prediction could not be saved")); } finally { setBusy(false); } };
  return <motion.article initial={{ opacity: 0, y: 22, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .5, delay: index * .06, ease: [0.22, 1, .36, 1] }} whileHover={{ y: -6, scale: 1.006 }} className={`match-card-notch group relative mb-5 overflow-hidden rounded-[28px] border border-white/15 bg-gradient-to-br ${theme} px-[1px] pt-[1px] shadow-[0_24px_70px_rgba(0,0,0,.38)]`}>
    <div className="pointer-events-none absolute -left-12 -top-16 h-44 w-44 rounded-full bg-white/15 blur-3xl"/><div className="pointer-events-none absolute inset-x-12 top-0 h-px bg-gradient-to-r from-transparent via-white/70 to-transparent"/>
    <div className="relative rounded-[27px] bg-gradient-to-b from-white/[.1] to-black/[.08] px-[18px] pb-14 pt-[18px] backdrop-blur-xl md:px-5 md:pt-5">
      <div className="mb-3 flex items-center justify-between text-[10px] font-bold text-white/75"><span className="inline-flex items-center gap-1.5"><Crown size={13} className="text-[#e8c66a]"/>{t("مسابقه رسمی", "Official match")}</span><MatchState live={live} finished={finished} hasResult={hasResult} homeGoals={match.homeGoals} awayGoals={match.awayGoals} elapsed={Math.max(1, Math.min(90, Math.floor((now-kickoff)/60_000)))}/></div>
      <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><TeamBlock name={homeName} sourceName={match.homeTeam.name} logo={match.homeTeam.logoUrl}/><div className="text-center"><div className="mb-2 text-[9px] font-black tracking-wide text-white/65">{t("پیش‌بینی شما", "YOUR PICK")}</div><div className="flex items-center gap-1.5 rounded-2xl border border-white/20 bg-black/25 p-1.5 shadow-inner"><input disabled={locked} aria-label={`${t("گل", "Goals")} ${homeName}`} value={home} onChange={(event) => { setSaved(false); setHome(event.target.value.replace(/\D/g, "").slice(0, 2)); }} className="h-10 w-10 rounded-xl bg-white/95 text-center text-xl font-black text-[#0b211a] outline-none transition focus:ring-2 focus:ring-[#e8c66a] disabled:opacity-65"/><b className="text-white/70">:</b><input disabled={locked} aria-label={`${t("گل", "Goals")} ${awayName}`} value={away} onChange={(event) => { setSaved(false); setAway(event.target.value.replace(/\D/g, "").slice(0, 2)); }} className="h-10 w-10 rounded-xl bg-white/95 text-center text-xl font-black text-[#0b211a] outline-none transition focus:ring-2 focus:ring-[#e8c66a] disabled:opacity-65"/></div></div><TeamBlock name={awayName} sourceName={match.awayTeam.name} logo={match.awayTeam.logoUrl}/></div>
      <div className="mt-4 flex items-center justify-center rounded-xl border border-white/10 bg-black/15 px-3 py-2 text-[10px] font-bold text-white/75">{!live && !finished ? <><Clock3 size={13} className="ml-1.5"/><Countdown remaining={kickoff-now} language={language}/></> : <span>{formatIranDate(match.kickoffAt, language === "fa" ? "fa-IR" : "en-GB")} · {formatIranTime(match.kickoffAt, language === "fa" ? "fa-IR" : "en-GB")}</span>}</div>
      {error && <p role="alert" className="mt-3 rounded-xl border border-red-200/30 bg-red-950/25 p-2 text-center text-[10px] text-red-100">{error}</p>}
    </div>
    <button disabled={busy || home === "" || away === "" || locked} onClick={submit} className="absolute bottom-0 left-1/2 z-20 flex min-w-40 -translate-x-1/2 items-center justify-center gap-2 rounded-full border border-white/15 bg-[#050706] px-5 py-2.5 text-xs font-black text-white shadow-lg transition hover:-translate-y-0.5 disabled:cursor-wait disabled:opacity-60">{locked ? <>{finished ? "FT" : <><Radio size={13} className="animate-pulse text-red-400"/> LIVE</>}</> : saved ? <><Check size={14} className="text-brand"/>{t("ذخیره شد", "Saved")}</> : <><Sparkles size={14} className="text-[#e8c66a]"/>{busy ? t("در حال ثبت…", "Saving…") : t("ثبت پیش‌بینی", "Save prediction")}</>}</button>
  </motion.article>;
}
function TeamBlock({ name, sourceName, logo }: { name: string; sourceName: string; logo: string | null }) { return <div className="flex min-w-0 flex-col items-center gap-2 text-center"><div className="grid h-16 w-16 place-items-center rounded-full border border-white/25 bg-white/95 p-2 shadow-[0_10px_30px_rgba(0,0,0,.25)]"><TeamCrest name={sourceName} logo={logo}/></div><span className="line-clamp-2 max-w-28 text-xs font-black text-white">{name}</span></div>; }
function Countdown({ remaining, language }: { remaining: number; language: "fa" | "en" }) { const seconds = Math.max(0, Math.floor(remaining/1000)); const days = Math.floor(seconds/86400); const hours = Math.floor((seconds%86400)/3600); const minutes = Math.floor((seconds%3600)/60); const secs = seconds%60; const value = `${days ? `${days}${language === "fa" ? "ر " : "d "}` : ""}${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(secs).padStart(2,"0")}`; return <span>{language === "fa" ? "تا شروع: " : "Starts in: "}{value}</span>; }
function MatchState({ live, finished, hasResult, homeGoals, awayGoals, elapsed }: { live: boolean; finished: boolean; hasResult: boolean; homeGoals?: number | null; awayGoals?: number | null; elapsed: number }) { if (live) return <span className="inline-flex items-center gap-1.5 rounded-full bg-red-500 px-2.5 py-1 font-black text-white shadow-[0_0_18px_rgba(239,68,68,.45)]"><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-white"/>LIVE · {elapsed}&apos;</span>; if (finished) return <span className="rounded-full bg-black/30 px-2.5 py-1 font-black text-white">FT{hasResult ? ` · ${homeGoals} - ${awayGoals}` : ""}</span>; return <span className="rounded-full border border-white/15 bg-white/10 px-2.5 py-1">UPCOMING</span>; }
