"use client";
import Link from "next/link";
import { CheckCircle2, Clock3, Pencil, Target, Trophy } from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";
import { teamName } from "@/lib/football/team-names";
import { formatIranDate, formatIranTime } from "@/lib/football/time";
import { TeamCrest } from "@/components/TeamCrest";
type Row={matchId:string;kickoffAt:string;homeTeam:{id:number;name:string;logoUrl:string|null};awayTeam:{id:number;name:string;logoUrl:string|null};predictedHome:number;predictedAway:number;actualHome:number|null;actualAway:number|null;points:number;category:string};
export function PredictionHistory({rows}:{rows:Row[]}){const{language,t}=useLanguage();const total=rows.reduce((sum,row)=>sum+row.points,0),exact=rows.filter(row=>row.category==="EXACT_SCORE").length;return <main className="min-h-screen px-4 pb-28 pt-24 md:px-8 md:pt-32"><div className="mx-auto max-w-5xl"><section className="rounded-2xl border border-white/[.09] bg-[linear-gradient(135deg,#17261f,#0c100e)] p-6 md:p-8"><p className="text-xs font-black tracking-[.18em] text-brand">{t("پیش‌بینی‌های من","MY PREDICTIONS")}</p><div className="mt-2 flex items-end justify-between gap-6"><h1 className="text-3xl font-black md:text-5xl">{t("سابقه شما","Your history")}</h1><div className="flex gap-5"><Stat icon={<Trophy/>} value={total} label={t("امتیاز","Points")}/><Stat icon={<Target/>} value={exact} label={t("دقیق","Exact")}/></div></div></section>{rows.length?<div className="mt-5 space-y-3">{rows.map(row=><HistoryCard key={row.matchId} row={row} language={language}/>)}</div>:<div className="mt-6 rounded-xl border border-dashed border-white/15 p-14 text-center"><CheckCircle2 className="mx-auto mb-3 text-brand"/><h2 className="font-black">{t("هنوز پیش‌بینی ندارید","No predictions yet")}</h2></div>}</div></main>;}
function HistoryCard({row,language}:{row:Row;language:"fa"|"en"}){const{t}=useLanguage(),home=teamName(language,row.homeTeam.id,row.homeTeam.name),away=teamName(language,row.awayTeam.id,row.awayTeam.name),editable=new Date(row.kickoffAt).getTime()>Date.now();return <article className="grid gap-4 rounded-xl border border-white/[.08] bg-[#101512] p-4 md:grid-cols-[1fr_auto_auto] md:items-center"><div><div className="flex items-start justify-center gap-4 md:justify-start"><Team name={home} source={row.homeTeam.name} logo={row.homeTeam.logoUrl}/><span className="mt-5 text-xs font-bold text-[var(--muted)]">VS</span><Team name={away} source={row.awayTeam.name} logo={row.awayTeam.logoUrl}/></div><p className="mt-3 flex items-center justify-center gap-1 text-[11px] text-[var(--muted)] md:justify-start"><Clock3 size={12}/>{formatIranDate(row.kickoffAt,language==="fa"?"fa-IR":"en-GB")} · {formatIranTime(row.kickoffAt,language==="fa"?"fa-IR":"en-GB")}</p></div><div className="flex items-center justify-center gap-5 rounded-lg bg-black/20 px-5 py-3 text-center"><Score label={t("پیش‌بینی","Pick")} value={`${row.predictedHome} - ${row.predictedAway}`}/><span className="h-8 w-px bg-white/10"/><Score label={t("نتیجه","Result")} value={row.actualHome==null?"—":`${row.actualHome} - ${row.actualAway}`}/></div><div className="flex items-center justify-center gap-3 text-center"><div><b className="text-2xl font-black text-brand">+{row.points}</b><p className="text-[10px] text-[var(--muted)]">{row.category}</p></div>{editable&&<Link href={`/matches?edit=${encodeURIComponent(row.matchId)}`} className="inline-flex items-center gap-1 rounded-lg border border-brand/40 px-2.5 py-2 text-xs font-bold text-brand hover:bg-brand/10"><Pencil size={13}/>{t("ویرایش","Edit")}</Link>}</div></article>;}
function Team({name,source,logo}:{name:string;source:string;logo:string|null}){return <div className="flex w-24 shrink-0 flex-col items-center gap-1 text-center"><span className="grid h-11 w-11 place-items-center"><TeamCrest name={source} logo={logo}/></span><b className="line-clamp-2 min-h-8 text-xs font-bold">{name}</b></div>};function Score({label,value}:{label:string;value:string}){return <span><small className="block text-[9px] text-[var(--muted)]">{label}</small><b className="mt-1 block text-lg">{value}</b></span>};function Stat({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <span><span className="text-brand">{icon}</span><b className="mt-1 block text-xl">{value}</b><small className="text-[10px] text-[var(--muted)]">{label}</small></span>}
