"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Share2, Trophy, X } from "lucide-react";
import { sharePublicAward } from "@/lib/awards/share";
import { useLanguage } from "@/components/LanguageProvider";
import DepthCarousel from "@/components/DepthCarousel";

type Award = { id: string; type?: string; scope?: string; competitionName?: string; roundNumber?: number | null; periodId?: string | null; trophyUrl?: string | null; assetAvailable?: boolean };
function awardTitle(award: Award, language: "fa" | "en") { const club = award.scope === "CLUB" || award.type?.startsWith("CLUB_"); const weekly = award.type?.includes("WEEKLY"); if (language === "fa") return club ? (weekly ? "قهرمان هفتگی باشگاه" : "قهرمان دور باشگاه") : (weekly ? "قهرمان هفتگی" : "قهرمان دور"); return club ? (weekly ? "Club Weekly Winner" : "Club Round Winner") : (weekly ? "Weekly Winner" : "Round Winner"); }
function awardMeta(award: Award, language: "fa" | "en") { if (award.type?.includes("WEEKLY")) return award.periodId ?? (language === "fa" ? "هفته" : "Weekly"); if (!award.roundNumber) return ""; return language === "fa" ? `راند ${award.roundNumber}` : `MD${String(award.roundNumber).padStart(2, "0")}`; }

export function PublicAwardsSection({ username }: { username: string }) {
  const { t, language } = useLanguage(); const [awards, setAwards] = useState<Award[]>([]); const [details, setDetails] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch(`/api/profiles/${encodeURIComponent(username)}/awards`).then(r => r.ok ? r.json() : null).then(d => setAwards(d?.awards ?? [])).catch(() => undefined); }, [username]);
  useEffect(() => { if (!details) return; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setDetails(false); }; document.addEventListener("keydown", closeOnEscape); return () => { document.body.style.overflow = previousOverflow; document.removeEventListener("keydown", closeOnEscape); }; }, [details]);
  const shareableAwards = useMemo(() => awards.filter(a => a.trophyUrl), [awards]);
  const slides = useMemo(() => shareableAwards.map(a => ({ image: a.trophyUrl!, alt: `${a.competitionName ?? "LowBlock"} ${awardTitle(a, language)}`, title: `${awardTitle(a, language)} · ${a.competitionName ?? "LowBlock"} ${awardMeta(a, language)}`, shareLabel: t("اشتراک‌گذاری جایزه", "Share award") })), [shareableAwards, language, t]);
  async function share(award: Award) { try { const result = await sharePublicAward(`/api/profiles/${encodeURIComponent(username)}/awards/${award.id}/share-image`, language, award.id); setMessage(result === "saved" ? t("تصویر ذخیره شد؛ لینک LowBlock کپی شد.", "Image saved; contextual LowBlock link copied.") : t("با موفقیت به اشتراک گذاشته شد.", "Shared successfully.")); } catch { setMessage(t("اشتراک‌گذاری در دسترس نیست.", "Sharing is unavailable.")); } }
  if (!awards.length) return null;
  return <section className="my-[21px] rounded-[1.75rem] border border-[#e8c66a]/20 bg-[#101512] p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8c66a]/10 text-[#e8c66a]"><Trophy size={19}/></span><div><p className="text-[10px] font-black tracking-[.2em] text-[#e8c66a]">{t("جوایز", "AWARDS")}</p><h2 className="mt-1 text-xl font-black">{t("افتخارات بازیکن", "Player honours")}</h2></div></div><button type="button" onClick={() => { setMessage(""); setDetails(true); }} className="rounded-xl border border-[#e8c66a]/35 px-3 py-2 text-xs font-black text-[#e8c66a]">{t("مشاهده همه", "SEE ALL")}</button></div><div className="mt-5 flex gap-3 overflow-x-auto px-2 pb-2">{awards.map(award => <button key={award.id} type="button" onClick={() => { setMessage(""); setDetails(true); }} className="shrink-0 rounded-2xl p-1" title={`${awardTitle(award, language)} · ${award.competitionName ?? "LowBlock"}`} aria-label={`${awardTitle(award, language)} · ${award.competitionName ?? "LowBlock"}`}>{award.trophyUrl ? <img src={award.trophyUrl} alt="" loading="lazy" className="h-24 w-20 rounded-xl bg-black/30 object-contain"/> : <span className="grid h-24 w-20 place-items-center rounded-xl bg-black/30 text-[#e8c66a]"><Trophy size={24}/></span>}</button>)}</div>{message && <p className="mt-4 text-xs text-brand">{message}</p>}<AnimatePresence>{details && <motion.div className="fixed inset-0 z-[100] flex items-end bg-black/90" role="presentation" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .2 }} onClick={() => setDetails(false)}><motion.aside className="relative max-h-[94vh] w-full overflow-hidden rounded-t-[2rem] border border-b-0 border-[#e8c66a]/30 bg-[#09100c] p-2 shadow-[0_-24px_80px_rgba(0,0,0,.65)] sm:p-5" role="dialog" aria-modal="true" aria-label={t("جزئیات افتخارات", "Award details")} initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "100%" }} transition={{ type: "spring", stiffness: 360, damping: 34, mass: .8 }} onClick={event => event.stopPropagation()}><div className="mx-auto mb-2 h-1 w-12 rounded-full bg-white/20"/><button type="button" onClick={() => setDetails(false)} aria-label={t("بستن", "Close")} className="absolute right-4 top-4 z-[4000] grid h-10 w-10 place-items-center rounded-full border border-white/15 bg-black/60 text-white"><X size={18}/></button>{slides.length ? <DepthCarousel items={slides} rtl={language === "fa"} depth={150} spread={70} tilt={18} perspective={1400} visibleCards={3} cardWidth={300} cardHeight={460} radius={16} duration={700} showControls showIndicators onShare={index => { const award = shareableAwards[index]; if (award) void share(award); }}/> : <div className="grid min-h-[60vh] place-items-center text-sm text-white/60">{t("تصویر جوایز در دسترس نیست.", "Award artwork is unavailable.")}</div>}</motion.aside></motion.div>}</AnimatePresence></section>;
}
