"use client";

import { useEffect, useState } from "react";
import { Check, LockKeyhole } from "lucide-react";
import Link from "next/link";
import { motion, useReducedMotion } from "motion/react";
import { useLanguage } from "@/components/LanguageProvider";
import { TeamCrest } from "@/components/TeamCrest";
import { PredictionCard } from "@/components/PredictionCard";
import { GuestPredictionCard } from "@/components/GuestPredictionCard";

type Match = { providerMatchId:string; kickoffAt:string; status:string; homeTeam:{id:number;name:string;logoUrl:string|null}; awayTeam:{id:number;name:string;logoUrl:string|null} };
type Winner = { name:string; avatarUrl:string|null; clubName:string|null; clubImageUrl:string|null; points:number };
type Props = { token:string; award:{competitionName:string;competitionId:string;seasonStartYear:number;roundNumber:number}; winner:Winner; match:Match|null; initial:{homeGoals:number;awayGoals:number}|null; authenticated:boolean; imageUrl:string };

export function SharedPredictionExperience({token,award,winner,match,initial,authenticated,imageUrl}:Props){
  const {language,t}=useLanguage();
  const [open,setOpen]=useState(false);
  const [saved,setSaved]=useState(Boolean(initial));
  const [localOnly,setLocalOnly]=useState(false);
  return <main className="shared-award-page min-h-screen px-4 pb-10 pt-20 text-white md:px-8 md:pt-24"><div className="mx-auto flex max-w-5xl flex-col items-center gap-3 lg:grid lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)] lg:items-center lg:gap-8"><AwardPanel imageUrl={imageUrl} award={award} winner={winner} t={t} language={language}/>{match?<section className="flex w-full max-w-md flex-col items-center">{!open&&<MatchSummary match={match} t={t} onClick={()=>setOpen(true)} language={language}/>} {open&&(authenticated?<PredictionCard match={match} initial={initial??undefined} openOnMount onPredictionSaved={()=>{setSaved(true);setOpen(false)}}/>:<GuestPredictionCard match={match} onClose={()=>setOpen(false)} onSaved={(only)=>{setSaved(true);setLocalOnly(only);setOpen(false)}}/>)}{saved&&!authenticated&&<JoinPrompt token={token} localOnly={localOnly} t={t}/>} {saved&&authenticated&&<Link href="/predictions" className="sr-only">{t("تاریخچه من","MY HISTORY")}</Link>}</section>:null}</div></main>
}

function MatchSummary({match,t,onClick,language}:{match:Match;t:(fa:string,en:string)=>string;onClick:()=>void;language:"fa"|"en"}){
  const reduced=useReducedMotion();
  const lines=language==="fa"?["ثابت کن تو قویتری","تاج بعدی برای توئه"]:["Prove that CROWN is yours.","Take the next crown."];
  const [lineIndex,setLineIndex]=useState(0);
  const [typed,setTyped]=useState("");
  useEffect(()=>{if(reduced){setTyped(lines[lineIndex]);return}setTyped("");let index=0;const timer=window.setInterval(()=>{index+=1;setTyped(lines[lineIndex].slice(0,index));if(index>=lines[lineIndex].length)window.clearInterval(timer)},58);return()=>window.clearInterval(timer)},[lineIndex,language,reduced]);
  useEffect(()=>{if(reduced)return;const timer=window.setInterval(()=>setLineIndex((value)=>(value+1)%lines.length),6500);return()=>window.clearInterval(timer)},[reduced,lines.length]);
  return <motion.button type="button" onClick={onClick} aria-label={t("باز کردن پیش‌بینی مسابقه","Open match prediction")} className="group relative isolate grid w-full max-w-md grid-cols-[1fr_auto_1fr] items-center gap-4 overflow-hidden rounded-[1.45rem] border border-brand/50 bg-[#09140f] px-5 py-4 text-start shadow-[0_18px_55px_rgba(0,0,0,.32),inset_0_1px_0_rgba(255,255,255,.08)]" style={{backgroundImage:"linear-gradient(110deg,rgba(32,184,121,.18),rgba(8,14,10,.92),rgba(232,198,106,.16),rgba(32,184,121,.18))",backgroundSize:"240% 100%"}} animate={reduced?undefined:{backgroundPosition:["0% 50%","100% 50%","0% 50%"]}} transition={{duration:5,repeat:Infinity,ease:"linear"}} whileTap={reduced?undefined:{scale:.985}}><span className="pointer-events-none absolute inset-px -z-10 rounded-[1.38rem] border border-white/[.04]"/><span className="pointer-events-none absolute -inset-10 -z-10 bg-[radial-gradient(circle_at_50%_0%,rgba(32,184,121,.18),transparent_55%)]"/><div className="flex justify-center transition-transform duration-200 group-hover:scale-105"><TeamCrest name={match.homeTeam.name} logo={match.homeTeam.logoUrl} className="h-14 w-14"/></div><span className="grid h-11 w-11 place-items-center rounded-full border border-[#e8c66a]/55 bg-[#e8c66a]/10 text-[10px] font-black tracking-widest text-[#e8c66a]">VS</span><div className="flex justify-center transition-transform duration-200 group-hover:scale-105"><TeamCrest name={match.awayTeam.name} logo={match.awayTeam.logoUrl} className="h-14 w-14"/></div><span className="col-span-3 h-5 text-center text-[11px] font-black tracking-[.08em] text-white/75">{typed}{!reduced&&<span className="ms-0.5 text-brand">▌</span>}</span></motion.button>
}

function AwardPanel({imageUrl,award,winner,t,language}:{imageUrl:string;award:Props["award"];winner:Winner;t:(fa:string,en:string)=>string;language:"fa"|"en"}){return <div className="flex w-full max-w-md flex-col items-center"><img src={imageUrl} alt={`${award.competitionName} Round Winner`} className="max-h-[38vh] w-full object-contain drop-shadow-[0_24px_70px_rgba(0,0,0,.5)] md:max-h-[52vh]"/><div className="relative mt-1 w-full overflow-hidden rounded-2xl border border-[#e8c66a]/30 bg-[linear-gradient(120deg,rgba(232,198,106,.12),rgba(32,184,121,.08)_45%,rgba(0,0,0,.22))] p-3"><div className="pointer-events-none absolute inset-0 opacity-25 [background-image:linear-gradient(135deg,transparent_0%,rgba(255,255,255,.2)_45%,transparent_46%),linear-gradient(45deg,transparent_0%,rgba(32,184,121,.18)_50%,transparent_51%)]"/><div className="relative flex items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-xl border border-[#e8c66a]/45 bg-[#e8c66a]/15 text-sm font-black text-[#f4d982]">{winner.avatarUrl?<img src={winner.avatarUrl} alt={winner.name} className="h-full w-full object-cover"/>:winner.name.trim().slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="text-[9px] font-black tracking-[.16em] text-[#e8c66a]">{t("قهرمان این کارت","CARD WINNER")}</p><p className="truncate text-sm font-black text-white">{winner.name}</p><div className="mt-0.5 flex items-center gap-1.5 text-[10px] font-bold text-white/55">{winner.clubImageUrl?<img src={winner.clubImageUrl} alt={winner.clubName??"Club"} className="h-4 w-4 rounded-full object-cover"/>:winner.clubName?<span className="grid h-4 w-4 place-items-center rounded-full bg-brand/20 text-[7px] font-black text-brand">{winner.clubName.slice(0,2).toUpperCase()}</span>:<LockKeyhole size={11}/>}<span className="truncate">{winner.clubName??t("بدون باشگاه","No club")}</span></div></div><div className="shrink-0 border-s border-white/10 ps-3 text-end"><p className="text-[9px] font-black tracking-[.13em] text-white/45">{t("امتیاز راند","ROUND POINTS")}</p><p className="text-xl font-black text-[#e8c66a]">{new Intl.NumberFormat(language==="fa"?"fa-IR":"en-US").format(winner.points)}</p></div></div></div></div>}

function JoinPrompt({token,localOnly,t}:{token:string;localOnly:boolean;t:(fa:string,en:string)=>string}){return <div className="mt-3 w-full max-w-md overflow-hidden rounded-2xl border border-brand/30 bg-[linear-gradient(135deg,rgba(32,184,121,.16),rgba(8,17,12,.9))] p-4 text-center"><p className="flex items-center justify-center gap-2 text-sm font-black text-brand"><Check size={17}/>{localOnly?t("روی این دستگاه ذخیره شد","Saved on this device"):t("پیش‌بینی ذخیره شد","Prediction saved")}</p><p className="mt-2 text-xs text-white/65">{t("به بازی ملحق شو و امتیازت را حفظ کن.","Join the game and keep your points.")}</p><Link href={`/signup?returnTo=${encodeURIComponent(`/s/${token}`)}`} className="mt-3 flex min-h-11 items-center justify-center rounded-xl bg-brand text-xs font-black text-[#06120c]">{t("ساخت پروفایل","JOIN LOWBLOCK")}</Link></div>}
