import { createHash, randomBytes } from "node:crypto";
import { NextResponse } from "next/server";
import { ObjectId } from "mongodb";
import { currentUserId } from "@/lib/auth/session";
import { getDb } from "@/lib/db/mongo";
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const makeToken = () => randomBytes(5).toString("base64url").replace(/[-_]/g, "").slice(0, 7);
async function ownerClub(clubId: string, ownerId: string) { if (!ObjectId.isValid(clubId)) return null; return (await getDb()).collection<any>("clubs").findOne({ _id: new ObjectId(clubId), ownerId }); }
export async function GET(_req: Request, { params }: { params: Promise<{ clubId: string }> }) { const ownerId = await currentUserId(); const { clubId } = await params; if (!ownerId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!(await ownerClub(clubId, ownerId))) return NextResponse.json({ error: "Owner permission required" }, { status: 403 }); const invite = await (await getDb()).collection<any>("clubInvitations").findOne({ clubId, kind: "CLUB_LINK", status: "ACTIVE" }, { projection: { token: 1 } }); return NextResponse.json({ active: Boolean(invite), inviteToken: invite?.token ?? null }); }
export async function POST(_req: Request, { params }: { params: Promise<{ clubId: string }> }) { const ownerId = await currentUserId(); const { clubId } = await params; if (!ownerId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!(await ownerClub(clubId, ownerId))) return NextResponse.json({ error: "Owner permission required" }, { status: 403 }); const db = await getDb(); const active = await db.collection<any>("clubInvitations").findOne({ clubId, kind: "CLUB_LINK", status: "ACTIVE" }); if (active) return NextResponse.json({ ok: true, inviteToken: active.token, reused: true }); const inviteToken = makeToken(); const now = new Date(); try { await db.collection("clubInvitations").insertOne({ clubId, kind: "CLUB_LINK", token: inviteToken, tokenHash: hash(inviteToken), status: "ACTIVE", createdAt: now, updatedAt: now, createdBy: ownerId }); } catch (error) { if (!(error && typeof error === "object" && "code" in error && (error as { code?: number }).code === 11000)) throw error; const existing = await db.collection<any>("clubInvitations").findOne({ clubId, kind: "CLUB_LINK", status: "ACTIVE" }); if (existing) return NextResponse.json({ ok: true, inviteToken: existing.token, reused: true }); throw error; } return NextResponse.json({ ok: true, inviteToken }); }
export async function DELETE(_req: Request, { params }: { params: Promise<{ clubId: string }> }) { const ownerId = await currentUserId(); const { clubId } = await params; if (!ownerId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!(await ownerClub(clubId, ownerId))) return NextResponse.json({ error: "Owner permission required" }, { status: 403 }); await (await getDb()).collection("clubInvitations").updateOne({ clubId, kind: "CLUB_LINK", status: "ACTIVE" }, { $set: { status: "REVOKED", revokedAt: new Date(), revokedBy: ownerId, updatedAt: new Date() } }); return NextResponse.json({ ok: true }); }
