import { createHash, randomBytes } from "node:crypto";
import { NextResponse } from "next/server";
import { ObjectId } from "mongodb";
import { currentUserId } from "@/lib/auth/session";
import { getDb } from "@/lib/db/mongo";
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const makeToken = () => randomBytes(5).toString("base64url").replace(/[-_]/g, "").slice(0, 7);
export async function POST(_req: Request, { params }: { params: Promise<{ clubId: string }> }) { const ownerId = await currentUserId(); const { clubId } = await params; if (!ownerId || !ObjectId.isValid(clubId)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const db = await getDb(); const club = await db.collection<any>("clubs").findOne({ _id: new ObjectId(clubId), ownerId }); if (!club) return NextResponse.json({ error: "Owner permission required" }, { status: 403 }); const active = await db.collection<any>("clubInvitations").findOne({ clubId, kind: "CLUB_LINK", status: "ACTIVE" }); if (active) return NextResponse.json({ ok: true, inviteToken: active.token, reused: true }); const inviteToken = makeToken(); const now = new Date(); await db.collection("clubInvitations").insertOne({ clubId, kind: "CLUB_LINK", token: inviteToken, tokenHash: hash(inviteToken), status: "ACTIVE", createdAt: now, updatedAt: now, createdBy: ownerId }); return NextResponse.json({ ok: true, inviteToken }); }
export async function DELETE(_req: Request, { params }: { params: Promise<{ clubId: string }> }) { const ownerId = await currentUserId(); const { clubId } = await params; if (!ownerId || !ObjectId.isValid(clubId)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const db = await getDb(); const club = await db.collection<any>("clubs").findOne({ _id: new ObjectId(clubId), ownerId }); if (!club) return NextResponse.json({ error: "Owner permission required" }, { status: 403 }); await db.collection("clubInvitations").updateOne({ clubId, kind: "CLUB_LINK", status: "ACTIVE" }, { $set: { status: "REVOKED", revokedAt: new Date(), revokedBy: ownerId, updatedAt: new Date() } }); return NextResponse.json({ ok: true }); }
