import { notFound } from "next/navigation";
import { ObjectId } from "mongodb";
import { getDb } from "@/lib/db/mongo";
import { currentUserId } from "@/lib/auth/session";
import { requireClubMember } from "@/lib/domain/clubs";
import { getLeague } from "@/lib/football/leagues";
import { getCanonicalLeaderboard } from "@/lib/domain/leaderboards";
import { LeagueRoundRail } from "@/components/LeagueRoundRail";
import { T } from "@/components/LanguageProvider";
export const dynamic = "force-dynamic";
export default async function ClubLeaguePage({ params }: { params: Promise<{ clubId: string; code: string }> }) { const { clubId, code } = await params; const league = getLeague(code); if (!league || !ObjectId.isValid(clubId)) notFound(); const userId = await currentUserId(); if (!userId) notFound(); const db = await getDb(); let club; try { ({ club } = await requireClubMember(db, clubId, userId)); } catch { notFound(); } const year = Number((await db.collection("matches").findOne({ leagueCode: code }, { sort: { seasonStartYear: -1 }, projection: { seasonStartYear: 1 } }))?.seasonStartYear ?? new Date().getUTCFullYear()); const rows = await getCanonicalLeaderboard(db, { clubId, leagueCode: code, seasonStartYear: year }, 100); const rounds = await db.collection<any>("rounds").find({ leagueCode: code, seasonId: String(year) }).sort({ number: 1 }).toArray(); return <main className="min-h-screen px-4 pb-28 pt-24 md:px-8 md:pt-32"><div className="mx-auto max-w-5xl"><section className="rounded-[2rem] border border-white/[.08] bg-[radial-gradient(circle_at_90%_0%,rgba(32,184,121,.22),transparent_38%),linear-gradient(145deg,#14251c,#0a0f0c)] p-7"><p className="text-xs font-black tracking-[.2em] text-brand">{club.name}</p><h1 className="mt-2 text-3xl font-black"><T fa={league.faName} en={league.enName}/></h1><p className="mt-2 text-sm text-white/60"><T fa={`فصل ${year}/${String(year + 1).slice(-2)}`} en={`Season ${year}/${String(year + 1).slice(-2)}`}/></p></section><LeagueRoundRail code={code} basePath={`/club/${clubId}/league/${code}`} rounds={rounds.map(round => ({ number: round.number, count: round.eligibleFixtures, active: round.status === "LIVE", completed: round.status === "FINAL" }))}/><section className="mt-6 rounded-3xl border border-white/10 bg-[#101512] p-5"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[.16em] text-brand">STANDINGS</p><h2 className="mt-1 text-2xl font-black"><T fa="جدول باشگاه" en="Club standings"/></h2></div><span className="rounded-full bg-brand/10 px-3 py-1 text-xs font-bold text-brand">{rows.length} players</span></div><div className="mt-4 space-y-2">{rows.map(row => <div key={row.userId} className="flex items-center justify-between rounded-xl bg-black/20 p-3"><span className="flex items-center gap-3"><b className="w-5 text-[var(--muted)]">{row.rank}</b><span>{row.username}</span></span><b className="text-brand">{row.points}</b></div>)}</div></section></div></main>; }
