import * as cheerio from "cheerio";
import { createHash } from "node:crypto";
import { resolveTeamName } from "@/lib/football/team-names.fa";
import type { MatchStatus } from "./types";

const clean=(value:string)=>value.replace(/\s+/g," ").trim();
const teamId=(href:string)=>href.match(/\/verein\/(\d+)/)?.[1];
function parseDateTime(dateText:string,timeText:string){const d=dateText.match(/(\d{1,2})\/(\d{1,2})\/(\d{2,4})/);if(!d)return null;const year=Number(d[3].length===2?`20${d[3]}`:d[3]);const hour=timeText.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);let h=hour?Number(hour[1]):0;if(hour?.[3].toUpperCase()==="PM"&&h<12)h+=12;if(hour?.[3].toUpperCase()==="AM"&&h===12)h=0;return new Date(Date.UTC(year,Number(d[2])-1,Number(d[1]),h,hour?Number(hour[2]):0));}
export function parseSeason(html:string){const $=cheerio.load(html);const selected=$("select[name*=saison] option[selected], select[name*=season] option[selected]").first().attr("value");const label=clean($("select[name*=saison] option[selected], select[name*=season] option[selected]").first().text());const year=Number(selected||label.match(/(20\d{2})/)?.[1]);return {seasonStartYear:Number.isFinite(year)?year:new Date().getUTCFullYear(),seasonLabel:label||String(year)};}
export function parseTeams(html:string){const $=cheerio.load(html);const teams=[] as Array<{providerTeamId:string;sourceName:string;faName:string;crestUrl?:string;profileUrl?:string}>; $("a[href*='/verein/']").each((_,el)=>{const href=$(el).attr("href")??"";const id=teamId(href);const sourceName=clean($(el).attr("title")||$(el).text());if(id&&sourceName&&!teams.some(t=>t.providerTeamId===id))teams.push({providerTeamId:id,sourceName,faName:resolveTeamName(id,sourceName),crestUrl:$(el).find("img").attr("src"),profileUrl:href});});return teams;}
export function parseFixtures(html:string,leagueCode:string,seasonStartYear:number,matchday:number){const $=cheerio.load(html);const fixtures=[] as Array<Record<string,unknown>>;$('tr').each((_,row)=>{const matchHref=$(row).find('a[href*="/spielbericht/"]').attr("href");if(!matchHref)return;const matchId=matchHref.match(/spielbericht\/(\d+)/)?.[1];const teamLinks=$(row).find('a[href*="/spielplan/verein/"]');if(!matchId||teamLinks.length<2)return;const homeHref=teamLinks.eq(0).attr("href")??"",awayHref=teamLinks.eq(1).attr("href")??"";const homeId=teamId(homeHref),awayId=teamId(awayHref);if(!homeId||!awayId)return;const cells=$(row).find("td");const dateText=clean(cells.eq(0).text()),timeText=clean(cells.eq(1).text());const kickoffAt=parseDateTime(dateText,timeText);if(!kickoffAt)return;const scoreText=clean($(row).find('a[href*="/spielbericht/"]').text());const score=scoreText.match(/(\d+)\s*[:\-]\s*(\d+)/);const status:MatchStatus=score?"FINISHED":/postponed|abgesagt/i.test(scoreText)?"POSTPONED":"SCHEDULED";const providerMatchId=matchId||createHash("sha256").update(`${leagueCode}|${seasonStartYear}|${matchday}|${homeId}|${awayId}|${kickoffAt.toISOString()}`).digest("hex");fixtures.push({provider:"transfermarkt",providerMatchId,leagueCode,seasonStartYear,matchday,homeTeamProviderId:homeId,awayTeamProviderId:awayId,kickoffAt,status,homeGoals:score?Number(score[1]):null,awayGoals:score?Number(score[2]):null,sourceUrl:`https://www.transfermarkt.com${matchHref}`});});return fixtures;}
