export const LOWBLOCK_HOME = "https://lowblock.ir";
type ShareLink = { url: string; message: string };

async function contextualUrl(awardId: string, language: "fa" | "en"): Promise<ShareLink> { const response = await fetch(`/api/awards/${awardId}/share-link?locale=${language}`, { method: "POST" }); if (!response.ok) throw new Error("Share link unavailable"); return await response.json() as ShareLink; }
async function shareBlob(blob: Blob, link: ShareLink) { const file = new File([blob], "lowblock-round-winner.png", { type: blob.type || "image/png" }); const text = `${link.message}\n\n${link.url}`; if (navigator.share && navigator.canShare?.({ files: [file] })) { try { await navigator.share({ files: [file], text }); return "shared" as const; } catch { /* Fall back when browser share loses user activation or is cancelled. */ } } const objectUrl = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = objectUrl; anchor.download = file.name; anchor.click(); URL.revokeObjectURL(objectUrl); await navigator.clipboard?.writeText(link.url).catch(() => undefined); return "saved" as const; }
async function shareImage(imageUrl: string, language: "fa" | "en", link: ShareLink) { const response = await fetch(imageUrl); if (!response.ok) throw new Error("Share image unavailable"); return shareBlob(await response.blob(), link); }
async function shareImageWithContext(imageUrl: string, language: "fa" | "en", awardId: string) { const [link, response] = await Promise.all([contextualUrl(awardId, language), fetch(imageUrl)]); if (!response.ok) throw new Error("Share image unavailable"); return shareBlob(await response.blob(), link); }
export async function shareAward(awardId: string, language: "fa" | "en" = document.documentElement.lang === "fa" ? "fa" : "en") { const id = awardId.includes("/share-image") ? awardId.split("/")[3] : awardId; return shareImageWithContext(`/api/awards/${id}/share-image`, language, id); }
export async function sharePublicAward(imageUrl: string, language: "fa" | "en", awardId?: string) { if (!awardId) return shareImage(imageUrl, language, { url: LOWBLOCK_HOME, message: "" }); return shareImageWithContext(imageUrl, language, awardId); }
