/**
 * Persian football names used by Iranian sports media.
 * Keys are provider/central source names; values are display names only.
 * Provider IDs remain in centralTeams.providerIds and are never replaced.
 */
const NAMES: Record<string, string> = {
  "Bucheon FC 1995": "بوچئون ۱۹۹۵",
  "Jeju United FC": "ججو یونایتد",
  "Ulsan Hyundai FC": "اولسان هیوندای",
  "FC Seoul": "اف‌سی سئول",
  "Incheon United": "اینچئون یونایتد",
  "Levski Sofia": "لِفسکی صوفیه",
  "Red Bull Salzburg": "ردبول سالزبورگ",
  OFI: "اُفی",
  "Ferencvarosi TC": "فرنتس‌واروش",
  "Lech Poznan": "لخ پوزنان",
  "NEC Nijmegen": "ان‌ای‌سی نایمخن",
  Lillestrom: "لیلستروم",
  Torreense: "تورنزه",
  Plzen: "پلژن",
  "Union St. Gilloise": "یونیون سن ژیلواز",
  "Amasyaspor 1968": "آماسیااسپور ۱۹۶۸",
  Cankirigucu: "چانکیری‌گوچو",
  "Orduspor 1967": "اوردواسپور ۱۹۶۷",
  "Torul Belediye Genclik": "تورول بلدیه گنچلیک",
  "Darlington 1883": "دارلینگتون ۱۸۸۳",
  "Merthyr Town": "مرثیر تاون",
  "Walton & Hersham": "والتون اند هرشام",
  Israel: "اسرائیل",
  "Rep. Of Ireland": "جمهوری ایرلند",
  "Solomon Islands": "جزایر سلیمان",
  Vanuatu: "وانواتو",
  "Papua New Guinea": "پاپوآ گینه نو",
  "New Caledonia": "کالدونیای جدید",
  Turkmenistan: "ترکمنستان",
  "Netherlands U19": "هلند زیر ۱۹ سال",
  "Belgium U19": "بلژیک زیر ۱۹ سال",
  "Romania U19": "رومانی زیر ۱۹ سال",
  "Hungary U19": "مجارستان زیر ۱۹ سال",
  "Japan U18": "ژاپن زیر ۱۸ سال",
  "Ukraine U18": "اوکراین زیر ۱۸ سال",
  "Finland U17": "فنلاند زیر ۱۷ سال",
  "France U17": "فرانسه زیر ۱۷ سال",
  "Sao Tome and Principe": "سائوتومه و پرنسیپ",
  "France U21": "فرانسه زیر ۲۱ سال",
  "Austria U18": "اتریش زیر ۱۸ سال",
  "England U17": "انگلیس زیر ۱۷ سال",
  "Republic of Ireland U17": "جمهوری ایرلند زیر ۱۷ سال",
  "FYR Macedonia": "مقدونیه شمالی",
  Anaitasuna: "آنایتاسونا",
  Tedeón: "تدئون",
  "Atletico Calatayud": "اتلتیکو کالاتایود",
  Baztán: "بازتان",
  Lebrijana: "لبریخانا",
  "Ceuta 6 de Junio": "سئوتا ۶ دِ خوئن‌یو",
  "Ribadesella CF": "ریبادیسیا",
  Noja: "نوخا",
  Pinatar: "پیناتار",
  Auriense: "آوریِنسه",
  "CD San Jose": "سن‌خوزه",
  Hortaleza: "اورتالسا",
  Güímar: "گوئی‌مار",
  "San Rafael": "سن رافائل",
  Prat: "پرات",
  Alcazar: "آلکازار",
  Talayuela: "تالایولا",
  Maracena: "ماراسِنا",
  Tavernes: "تاوِرنس",
  "Congo DR": "کنگو دموکراتیک",
  Uganda: "اوگاندا",
  Namibia: "نامیبیا",
  "Burkina Faso": "بورکینافاسو",
  Comoros: "کومور",
  "CD Anaitasuna FT": "آنایتاسونا اف‌تی",
  "CD Baztan": "بازتان",
  "UB Lebrijana": "یو‌بی لبریخانا",
  "CD 6 de Junio": "سئودی ۶ دِ خوئن‌یو",
  "CD Tedeon": "سئودی تدئون",
  "Atlético Unión Güímar": "اتلتیکو یونیون گوئی‌مار",
  "Sporting Hortaleza": "اسپورتینگ اورتالسا",
  "AE Prat": "اِی‌ای پرات",
  "CF Sant Rafel": "سان رافائل",
  "CD San José de Soria": "سن‌خوزه دِ سوریا",
  "Noja SD": "نوخا اس‌دی",
  "Auriense Cented Academy": "آوریِنسه سنتد آکادمی",
  "Sporting de Alcazar CF": "اسپورتینگ آلکازار",
  "CP Talayuela": "سی‌پی تالایولا",
  "UE Tavernes": "اوئه تاوِرنس",
  "UD Maracena": "او‌ده ماراسِنا",
  "Atletico Melilla CF": "اتلتیکو ملیا",
  "UD Pinatar": "او‌ده پیناتار",
  Mali: "مالی",
  "DR Congo": "کنگو دموکراتیک",
  Rwanda: "رواندا",
  Kenya: "کنیا",
  "1964 Silifke Spor": "سیلیفکه‌اسپور ۱۹۶۴",
  "Kırklarelispor": "قرقلرایلی‌اسپور",
  "Bitlis 1916 FSK": "بیتلیس ۱۹۱۶",
  Sakaryaspor: "ساکاریاسپور",
  "Arıt Kayadibispor": "آریت کایادیبی‌اسپور",
  "Karşıyaka": "کارشیاکا",
  "1923 Afyonkarahisar SK": "آفیون‌کاراحیسار ۱۹۲۳",
  Niger: "نیجر",
  Benin: "بنین",
  "Adana Adaletgücü": "آدانا عدالت‌گوچو",
  "Adana Demirspor": "آدانا دمیرسپـور",
  Hatayspor: "هاتای‌اسپور",
  "Karaköprü Belediyespor": "کاراکوپرو بلدیه‌اسپور",
  "Kars 36 Spor": "قارص ۳۶ اسپور",
  "Fatsa Belediyespor": "فاتسا بلدیه‌اسپور",
  "Mazıdağı Fosfat SK": "مازی‌داغی فسفات",
  "Niğde Belediyesi Spor": "نیغده بلدیه‌اسپور",
  "Kırşehir FK": "قرشهر اف‌کی",
  "Ağrı 1970 SK": "آغری ۱۹۷۰",
  "Osmaniyespor FK": "عثمانیه‌اسپور",
  "Yeni Mersin İdman Yurdu AŞ": "ینی مرسین ایدمان یوردو",
  Pazarspor: "پازاراسپور",
  Erbaaspor: "ارباآاسپور",
  "Alanya 1221 FK": "آلانیا ۱۲۲۱",
  Somaspor: "سومااسپور",
  "TokatBelediye Plevne": "توکات بلدیه پلونه",
  "Etimesgut Spor Kulübü": "اتیمسگوت اسپور",
  "Zonguldakspor FK": "زونگولدک‌اسپور",
  "Düzcespor": "دوزجه‌اسپور",
  Bigaspor: "بیگاسپور",
  "Balıkesirspor": "بالیک‌اسیرسپـور",
  "Bursa Yıldırımspor": "بورسا ییلدیریم‌اسپور",
  "Eskişehir Anadolu Spor Faaliyetleri": "اسکی‌شهیر آنادولو",
  "Amasyaspor FK": "آماسیااسپور",
  "Antalya Kepezspor": "آنتالیا کِپزاسپور",
  "Gemlik Sümerbey Futbol": "گملیک سومربِی فوتبال",
  "Uşakspor": "اوشاک‌اسپور",
  "Gölcükspor": "گولجوک‌اسپور",
  "Yozgat Belediye Bozokspor": "یوزگات بلدیه بوزوک‌اسپور",
  "Karacabey Belediye Spor": "کاراجابی بلدیه‌اسپور",
  "Galata SK": "گالاتا",
  "Küçükçekmece Sinop Spor": "کوچوک‌چکمجه سینوپ‌اسپور",
  "Büyükçekmece Gücü Fk Spor a.ş.": "بویوک‌چکمجه گوچو",
  Silivrispor: "سیلیوری‌اسپور",
  Bulvarspor: "بولواراسپور",
  "Söke 1970 Spor": "سوکه ۱۹۷۰",
  "Ayvalıkgücü Belediyespor": "آیوالیک‌گوچو بلدیه‌اسپور",
  "Gaziemir GOG Spor Yatırımları": "غازی‌امیر گوگ اسپور",
  Fethiyespor: "فتحیه‌اسپور",
  "Karabük İdman Yurdu FK": "کارابوک ایدمان یوردو",
  "Beykoz Anadolu Spor A.Ş.": "بیکوز آنادولو اسپور",
  "Bitlis Özgüzelderespor": "بیتلیس اوزگو‌زلره‌اسپور",
  "Silifke Belediyespor": "سیلیفکه بلدیه‌اسپور",
  Karsiyaka: "کارشیاکا",
  "Malatya Yeşilyurt Belediyespor": "مالاتیا یشیل‌یورت بلدیه‌اسپور",
  "Siirt Futbol SK": "سیرت فوتبال",
  "Eskişehirspor": "اسکی‌شهیرسپـور",
  "Erciyes 38 FSK": "ارکییس ۳۸",
  "1922 Akşehir": "آق‌شهیر ۱۹۲۲",
  "Kahta 02": "کاهتا ۰۲",
  "Malavan Bandar Anzali FC": "ملوان بندرانزلی",
  "Gol Gohar Sirjan": "گل‌گهر سیرجان",
  "Denizli İdman Yurdu 1959 SK": "دنیزلی ایدمان یوردو ۱۹۵۹",
  "Serikspor A.Ş.": "سریک‌اسپور",
  "Foolad Khuzestan": "فولاد خوزستان",
  "Karadeniz Ereğli 1980 SK": "کارادنیز ارغلی ۱۹۸۰",
  "Mes Shahr Babak": "مس شهر بابک",
  "Sepahan S.C.": "سپاهان",
  "Chador Malu Yazd": "چادرملو اردکان",
  "Sanat Naft Abadan": "صنعت نفت آبادان",
  "SV Werder Bremen": "وردربرمن",
  "RC Lens": "لانس",
  "Olympique Lyonnais": "لیون",
  "Málaga CF": "مالاگا",
  "Queens Park Rangers": "کوئینز پارک رنجرز",
  "Gençlerbirliği": "گنچلربیرلیغی",
  "Amed Sportif Faaliyetler": "آمد اسپورتیف",
  "Charlton Athletic": "چارلتون اتلتیک",
  "Swansea City": "سوانزی سیتی",
  "Norwich City": "نورویچ سیتی",
  "West Bromwich Albion": "وست برومویچ آلبیون",
  "Birmingham City": "بیرمنگام سیتی",
  "1. FC Union Berlin": "یونیون برلین",
  "SV 07 Elversberg": "الورزبرگ",
  "1. FSV Mainz 05": "ماینتس",
  "Bayer 04 Leverkusen": "بایر لورکوزن",
  "TSG Hoffenheim": "هافنهایم",
  "Leeds United": "لیدز یونایتد",
  "Brighton & Hove Albion": "برایتون",
  "Blackburn Rovers": "بلکبرن روورز",
  "Cardiff City": "کاردیف سیتی",
  "Bolton Wanderers": "بولتون واندررز",
  "Derby County": "دربی کانتی",
  "Preston North End": "پرستون نورث اند",
  "Sheffield United": "شفیلد یونایتد",
  "Lincoln City": "لینکلن سیتی",
  "Deportivo Alavés": "آلاوس",
  "Çaykur Rizespor": "چایکور ریزه‌اسپور",
  "AS Monaco": "موناکو",
  "Stade Brestois": "برست",
  "Başakşehir FK": "باشاک‌شهیر",
  "RC Strasbourg": "استراسبورگ",
  "Borussia M'gladbach": "بوروسیا مونشن‌گلادباخ",
  "Deportivo de A Coruña": "دپورتیوو لاکرونیا",
  "Stade Rennais": "رن",
  "Beşiktaş JK": "بشیکتاش",
  Troyes: "تروا",
  "Olympique de Marseille": "مارسی",
  "Real Racing Club": "رئال ریسینگ",
  "Braintree Town": "برینتری تاون",
  "Barton Town": "بارتون تاون",
  "Dover Athletic": "دوور اتلتیک",
  Darlington: "دارلینگتون",
  "Berkhamsted Town": "برکامستد تاون",
  "Torquay United": "تورکی یونایتد",
  "SE Døns FC": "اس‌ای دونز",
};

const key = (value: string) =>
  value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "");

const byKey = new Map(Object.entries(NAMES).map(([name, fa]) => [key(name), fa]));

export function reviewedPersianTeamName(sourceName: string): string | undefined {
  return NAMES[sourceName] || byKey.get(key(sourceName));
}
