import { access } from "node:fs/promises";
import { ObjectId } from "mongodb";
import { getDb, closeMongo } from "../lib/db/mongo";
import { normalizeUsername } from "../lib/auth/username";
import { getRoundWinnerAsset, LOWBLOCK_SCOPE, ROUND_WINNER_TYPE } from "../lib/awards/config";
const usernameArg = process.argv.find(arg => !arg.startsWith("--") && arg !== process.argv[0] && arg !== process.argv[1]) ?? "@ashkan";
const remove = process.argv.includes("--remove");
const demoRounds = [{ competitionId: "GB1", competitionName: "Premier League", seasonId: "2026", roundId: "GB1:2026:1", seasonStartYear: 2026, roundNumber: 1 }, { competitionId: "ES1", competitionName: "LaLiga", seasonId: "2026", roundId: "ES1:2026:2", seasonStartYear: 2026, roundNumber: 2 }];
async function main() { if (process.env.NODE_ENV === "production") throw new Error("Demo awards are disabled in production."); const username = usernameArg.replace(/^@/, ""); const db = await getDb(); const user = await db.collection<{ _id: ObjectId; username: string }>("users").findOne({ normalizedUsername: normalizeUsername(username) }, { projection: { username: 1 } }); if (!user) throw new Error(`User @${username} was not found.`); for (const demo of demoRounds) { const asset = getRoundWinnerAsset(demo.competitionId, demo.seasonStartYear, demo.roundNumber); if (!asset) throw new Error(`Demo asset mapping is missing for ${demo.competitionId}.`); await access(asset.trophy); await access(asset.shareCard); const filter = { userId: String(user._id), type: ROUND_WINNER_TYPE, scope: LOWBLOCK_SCOPE, competitionId: demo.competitionId, seasonId: demo.seasonId, roundId: demo.roundId, demo: true }; if (remove) { const result = await db.collection("awards").deleteOne(filter); console.log(result.deletedCount ? `Removed ${demo.competitionName} demo award.` : `No ${demo.competitionName} demo award found.`); } else { const result = await db.collection("awards").updateOne(filter, { $set: { revealedAt: null }, $setOnInsert: { ...filter, competitionName: demo.competitionName, seasonStartYear: demo.seasonStartYear, roundNumber: demo.roundNumber, awardedAt: new Date() } }, { upsert: true }); console.log(result.upsertedCount ? `Seeded ${demo.competitionName} demo award.` : `Reset ${demo.competitionName} demo award.`); } } await closeMongo(); }
main().catch(async error => { console.error(error instanceof Error ? error.message : error); await closeMongo(); process.exit(1); });
