import { NextResponse } from "next/server";
import { ObjectId } from "mongodb";
import { currentUserId } from "@/lib/auth/session";
import { getDb } from "@/lib/db/mongo";
import { refreshClubState, transferOwnership } from "@/lib/domain/clubs";

export async function GET(_req: Request, { params }: { params: Promise<{ clubId: string }> }) { const viewer = await currentUserId(); const { clubId } = await params; if (!viewer || !ObjectId.isValid(clubId)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const db = await getDb(); const membership = await db.collection<any>("clubMemberships").findOne({ clubId, userId: viewer, leftAt: null }); const club = await db.collection<any>("clubs").findOne({ _id: new ObjectId(clubId) }, { projection: { name: 1, ownerId: 1, state: 1, discoveryMode: 1, visibility: 1, imageUrl: 1 } }); if (!club || !membership) return NextResponse.json({ error: "Club membership required" }, { status: 403 }); const members = await db.collection<any>("clubMemberships").aggregate([{ $match: { clubId, leftAt: null } }, { $sort: { role: -1, joinedAt: 1 } }, { $lookup: { from: "users", let: { userId: "$userId" }, pipeline: [{ $match: { $expr: { $eq: [{ $toString: "$_id" }, "$$userId"] } } }, { $project: { username: 1, avatarUrl: 1 } }], as: "user" } }, { $unwind: { path: "$user", preserveNullAndEmptyArrays: true } }]).toArray(); return NextResponse.json({ club, members, isOwner: club.ownerId === viewer }); }

export async function DELETE(req: Request, { params }: { params: Promise<{ clubId: string }> }) { const actor = await currentUserId(); const { clubId } = await params; if (!actor || !ObjectId.isValid(clubId)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const data = await req.json().catch(() => ({})); const userId = typeof data.userId === "string" ? data.userId : actor; const db = await getDb(); const club = await db.collection<any>("clubs").findOne({ _id: new ObjectId(clubId) }); if (!club) return NextResponse.json({ error: "Club not found" }, { status: 404 }); if (club.ownerId === userId) return NextResponse.json({ error: "TRANSFER_OWNERSHIP_FIRST" }, { status: 409 }); const isOwner = club.ownerId === actor; if (userId !== actor && !isOwner) return NextResponse.json({ error: "Owner permission required" }, { status: 403 }); await db.collection("clubMemberships").updateOne({ clubId, userId, leftAt: null }, { $set: { leftAt: new Date() } }); await refreshClubState(db, clubId); return NextResponse.json({ ok: true }); }

export async function PATCH(req: Request, { params }: { params: Promise<{ clubId: string }> }) { const actor = await currentUserId(); const { clubId } = await params; if (!actor || !ObjectId.isValid(clubId)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const data = await req.json().catch(() => ({})); if (data.action !== "TRANSFER" || typeof data.userId !== "string") return NextResponse.json({ error: "Invalid ownership transfer" }, { status: 400 }); try { await transferOwnership(await getDb(), clubId, actor, data.userId); return NextResponse.json({ ok: true }); } catch (error) { const code = error instanceof Error ? error.message : "TRANSFER_FAILED"; return NextResponse.json({ error: code }, { status: 409 }); } }

