import { NextResponse } from "next/server";
import { ObjectId } from "mongodb";
import { z } from "zod";
import { currentUserId } from "@/lib/auth/session";
import { getDb } from "@/lib/db/mongo";
import { currentMembership, refreshClubState } from "@/lib/domain/clubs";
const body = z.object({ action: z.enum(["ACCEPT", "DECLINE", "CANCEL"]), requestId: z.string().min(1), confirmSwitch: z.boolean().default(false) });
export async function POST(req: Request, { params }: { params: Promise<{ clubId: string }> }) { const actor = await currentUserId(); const { clubId } = await params; if (!actor || !ObjectId.isValid(clubId)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const parsed = body.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid request" }, { status: 400 }); const db = await getDb(); const request = await db.collection<any>("clubJoinRequests").findOne({ _id: new ObjectId(parsed.data.requestId), clubId }); if (!request) return NextResponse.json({ error: "Request not found" }, { status: 404 }); const club = await db.collection<any>("clubs").findOne({ _id: new ObjectId(clubId) }); if (!club) return NextResponse.json({ error: "Club not found" }, { status: 404 }); if (parsed.data.action === "CANCEL") { if (request.userId !== actor) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); await db.collection("clubJoinRequests").updateOne({ _id: request._id, status: "PENDING" }, { $set: { status: "CANCELLED", updatedAt: new Date() } }); return NextResponse.json({ ok: true }); } if (club.ownerId !== actor) return NextResponse.json({ error: "Owner permission required" }, { status: 403 }); if (parsed.data.action === "DECLINE") { await db.collection("clubJoinRequests").updateOne({ _id: request._id, status: "PENDING" }, { $set: { status: "DECLINED", updatedAt: new Date() } }); return NextResponse.json({ ok: true }); } const existing = await currentMembership(db, request.userId); if (existing && !parsed.data.confirmSwitch) return NextResponse.json({ requiresSwitchConfirmation: true, currentClubId: existing.clubId, message: "Joining this Club will leave the current Club." }, { status: 409 }); if (existing) { const currentClub = await db.collection<any>("clubs").findOne({ _id: new ObjectId(existing.clubId) }); if (currentClub?.ownerId === request.userId) return NextResponse.json({ error: "TRANSFER_OWNERSHIP_FIRST" }, { status: 409 }); await db.collection("clubMemberships").updateOne({ _id: existing._id, leftAt: null }, { $set: { leftAt: new Date() } }); } const now = new Date(); await db.collection("clubMemberships").insertOne({ clubId, userId: request.userId, role: "MEMBER", joinedAt: now, leftAt: null }); await db.collection("clubJoinRequests").updateOne({ _id: request._id, status: "PENDING" }, { $set: { status: "ACCEPTED", updatedAt: now } }); const members = await refreshClubState(db, clubId); return NextResponse.json({ ok: true, members }); }

export async function GET(_req: Request, { params }: { params: Promise<{ clubId: string }> }) { const actor = await currentUserId(); const { clubId } = await params; if (!actor || !ObjectId.isValid(clubId)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const db = await getDb(); const club = await db.collection<any>("clubs").findOne({ _id: new ObjectId(clubId) }); if (!club || club.ownerId !== actor) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); return NextResponse.json({ requests: await db.collection("clubJoinRequests").find({ clubId, status: "PENDING" }).sort({ createdAt: 1 }).toArray() }); }

