import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getDb } from "@/lib/db/mongo";
import { getRoundWinnerAsset } from "@/lib/awards/config";
import { hashAwardShareToken } from "@/lib/awards/shareToken";
export const dynamic = "force-dynamic";
async function loadAward(token: string) { if (!/^[A-Za-z0-9_-]{40,60}$/.test(token)) return null; return (await getDb()).collection<any>("awards").findOne({ shareTokenHash: hashAwardShareToken(token), scope: "LOWBLOCK" }); }
export async function generateMetadata({ params }: { params: Promise<{ token: string }> }): Promise<Metadata> { const { token } = await params; const award = await loadAward(token); if (!award) return { title: "LowBlock Award" }; const title = `${award.competitionName} Round Winner | LowBlock`; return { title, description: "A LowBlock player won this round. Can you top the leaderboard?", openGraph: { title, description: "Make your prediction and climb the LowBlock leaderboard.", type: "website", images: [`/api/awards/share/${token}/image`] }, twitter: { card: "summary_large_image", title, description: "Make your prediction and climb the LowBlock leaderboard.", images: [`/api/awards/share/${token}/image`] } }; }
export default async function AwardSharePage({ params }: { params: Promise<{ token: string }> }) { const { token } = await params; const award = await loadAward(token); const asset = award && getRoundWinnerAsset(award.competitionId, award.seasonStartYear, award.roundNumber); if (!award || !asset) notFound(); return <main className="min-h-screen bg-[#070a08] px-5 py-10 text-white"><div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-md flex-col items-center justify-center text-center"><p className="text-xs font-black tracking-[.22em] text-brand">LOWBLOCK AWARD</p><h1 className="mt-3 text-3xl font-black">{award.competitionName} Round Winner</h1><img src={`/api/awards/share/${token}/image`} alt={`${award.competitionName} Round Winner share card`} className="mt-8 w-full rounded-2xl shadow-[0_30px_90px_rgba(0,0,0,.55)]"/><p className="mt-7 text-base font-bold text-white/75">Someone just took the top spot. Think you can beat the leaderboard?</p><Link href="/matches" className="mt-6 rounded-xl bg-brand px-7 py-3.5 text-sm font-black text-[#06120c]">MAKE YOUR PREDICTION</Link><Link href="/" className="mt-4 text-xs font-bold text-white/45">Explore LowBlock</Link></div></main>; }
