import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getDb } from "@/lib/db/mongo";
import { getRoundWinnerAsset } from "@/lib/awards/config";
import { hashAwardShareToken } from "@/lib/awards/shareToken";
import { currentUserId } from "@/lib/auth/session";
import { SharedPredictionExperience } from "@/components/SharedPredictionExperience";

export const dynamic = "force-dynamic";
async function load(token:string){if(!/^[A-Za-z0-9_-]{40,60}$/.test(token))return null;const db=await getDb();const award=await db.collection<any>("awards").findOne({shareTokenHash:hashAwardShareToken(token),scope:"LOWBLOCK"});if(!award)return null;const asset=getRoundWinnerAsset(award.competitionId,award.seasonStartYear,award.roundNumber);if(!asset)return null;const now=new Date();const query={provider:"football-api",rawApiResponse:{$exists:true},status:{$nin:["VOID","CANCELLED"]},kickoffAt:{$gt:now}};const same=await db.collection<any>("matches").find({...query,leagueCode:award.competitionId}).sort({kickoffAt:1}).limit(1).toArray();const fallback=same.length?same:await db.collection<any>("matches").find(query).sort({kickoffAt:1}).limit(1).toArray();const match=fallback[0]??null;const userId=await currentUserId();const prediction=userId&&match?await db.collection<any>("predictions").findOne({userId,matchId:match.providerMatchId}):null;return {award:{competitionName:award.competitionName,competitionId:award.competitionId,seasonStartYear:award.seasonStartYear,roundNumber:award.roundNumber},match:match?{providerMatchId:match.providerMatchId,kickoffAt:new Date(match.kickoffAt).toISOString(),status:match.status,homeTeam:match.homeTeam,awayTeam:match.awayTeam}:null,initial:prediction?{homeGoals:prediction.homeGoals,awayGoals:prediction.awayGoals}:null,authenticated:Boolean(userId),imageUrl:`/api/awards/share/${token}/image`};}
export async function generateMetadata({params}:{params:Promise<{token:string}>}):Promise<Metadata>{const {token}=await params;const data=await load(token);return {title:data?`${data.award.competitionName} Round Winner | LowBlock`:"LowBlock Award",description:"Think you can take the next crown? Make your prediction."};}
export default async function AwardSharePage({params}:{params:Promise<{token:string}>}){const {token}=await params;const data=await load(token);if(!data)notFound();return <SharedPredictionExperience token={token} {...data}/>;}
